"""
Anade 60 preguntas nuevas al CSV de Transformada de Laplace.
- 12 nuevas: Resolucion de EDOs con Laplace (4 facil + 6 medio + 2 dificil)
- 12 nuevas: Traslaciones y convolucion (2 facil + 4 medio + 6 dificil)
- 16 nuevas: Multiplicacion por t y funciones periodicas (6 facil + 6 medio + 4 dificil)
- 20 nuevas: Sistemas y ecuaciones con coeficientes variables (6 facil + 8 medio + 6 dificil)

Uso: python append_laplace_questions.py
"""
import csv
import os

CSV = os.path.join(
    os.path.dirname(__file__),
    "..",
    "docs",
    "cursos",
    "generales",
    "ecuaciones-diferenciales",
    "4. Transformada de Laplace",
    "Preguntas",
    "transformada_laplace.csv",
)

CAP = "Transformada de Laplace"

# --- RESOLUCION DE EDOs CON LAPLACE (12 nuevas) ---
RESOL = "Resolución de EDOs con Laplace"
resol_rows = [
    (RESOL, "facil",
     r"¿Cuál es el primer paso para resolver el PVI $y' + 2y = 0$, $y(0)=5$ usando transformada de Laplace?",
     r"Aplicar transformada inversa", r"Aplicar Laplace a ambos lados de la EDO",
     r"Resolver por separación de variables", r"Multiplicar por un factor integrante", "B",
     r"El método consiste en aplicar $\mathcal{L}$ a ambos lados, convirtiendo la EDO en una ecuación algebraica para $Y(s)$."),
    (RESOL, "facil",
     r"Tras aplicar Laplace a $y' + 2y = 0$ con $y(0)=5$, ¿qué ecuación algebraica resulta?",
     r"$sY(s) - 5 + 2Y(s) = 0$", r"$sY(s) + 2Y(s) = 5$",
     r"$Y(s) = -2 + 5$", r"$sY(s) - 2Y(s) - 5 = 0$", "A",
     r"$\mathcal{L}\{y'\} = sY(s) - y(0) = sY(s) - 5$. Por linealidad: $sY-5+2Y=0$."),
    (RESOL, "facil",
     r"$\mathcal{L}\{y'''(t)\}$ en términos de $Y(s)$ es:",
     r"$s^3 Y(s) - s^2 y(0) - s\,y'(0) - y''(0)$", r"$s^3 Y(s) + s^2 y(0) + s\,y'(0) + y''(0)$",
     r"$s Y(s) - y(0) - y'(0) - y''(0)$", r"$Y'''(s)$", "A",
     r"Generalizando la propiedad de la derivada: $\mathcal{L}\{y^{(n)}\} = s^n Y - s^{n-1}y(0) - \cdots - y^{(n-1)}(0)$."),
    (RESOL, "facil",
     r"El método de Laplace para resolver un PVI lineal con coeficientes constantes convierte:",
     r"una EDO en una integral", r"una EDO en una ecuación algebraica para $Y(s)$",
     r"una ecuación algebraica en una EDO", r"una EDO en otra EDO de menor orden", "B",
     r"La transformada lleva derivadas a multiplicaciones por $s$, transformando la EDO en una ecuación algebraica."),
    (RESOL, "medio",
     r"Resuelva $y' + 3y = 0$, $y(0) = 2$.",
     r"$y(t) = 2e^{3t}$", r"$y(t) = 2e^{-3t}$", r"$y(t) = 3e^{-2t}$", r"$y(t) = 2 + 3t$", "B",
     r"$sY - 2 + 3Y = 0 \Rightarrow Y(s+3) = 2 \Rightarrow Y = 2/(s+3) \Rightarrow y(t) = 2e^{-3t}$."),
    (RESOL, "medio",
     r"Resuelva $y'' - y = 0$, $y(0) = 0$, $y'(0) = 1$.",
     r"$y(t) = \cosh(t)$", r"$y(t) = \sinh(t)$", r"$y(t) = \sin(t)$", r"$y(t) = e^{-t}$", "B",
     r"$s^2 Y - 0 - 1 - Y = 0 \Rightarrow Y = 1/(s^2-1) \Rightarrow y(t) = \sinh(t)$."),
    (RESOL, "medio",
     r"Resuelva $y'' + 4y = 0$, $y(0) = 0$, $y'(0) = 6$.",
     r"$y = 3\sin(2t)$", r"$y = 6\cos(2t)$", r"$y = 3\cos(2t)$", r"$y = 6\sin(2t)$", "A",
     r"$s^2 Y - 6 + 4Y = 0 \Rightarrow Y = 6/(s^2+4) = 3\cdot 2/(s^2+4) \Rightarrow y = 3\sin(2t)$."),
    (RESOL, "medio",
     r"Resuelva $y' - y = e^{2t}$, $y(0) = 0$.",
     r"$y(t) = e^{2t} - e^t$", r"$y(t) = e^t - e^{2t}$", r"$y(t) = \tfrac{1}{2}(e^{2t} - e^t)$", r"$y(t) = e^{2t}$", "A",
     r"$sY - Y = 1/(s-2) \Rightarrow Y = 1/[(s-2)(s-1)]$. Fracciones parciales: $1/(s-2) - 1/(s-1)$. Inversa: $e^{2t} - e^t$."),
    (RESOL, "medio",
     r"Resuelva $y' + y = \sin(t)$, $y(0) = 0$.",
     r"$y = \sin t - \cos t + e^{-t}$", r"$y = \tfrac{1}{2}(\sin t - \cos t + e^{-t})$",
     r"$y = \tfrac{1}{2}(\sin t + \cos t - e^{-t})$", r"$y = e^{-t}\sin t$", "B",
     r"$sY + Y = 1/(s^2+1) \Rightarrow Y = 1/[(s+1)(s^2+1)]$. Fracciones parciales: $Y = \tfrac{1}{2}\big[\tfrac{1}{s+1} - \tfrac{s}{s^2+1} + \tfrac{1}{s^2+1}\big]$. Inversa: $\tfrac{1}{2}(e^{-t} - \cos t + \sin t)$."),
    (RESOL, "medio",
     r"Resuelva $y'' + y = 0$, $y(0) = 2$, $y'(0) = -3$.",
     r"$y = 2\cos t - 3\sin t$", r"$y = 2\cos t + 3\sin t$", r"$y = -3\cos t + 2\sin t$", r"$y = 2\sin t - 3\cos t$", "A",
     r"$s^2 Y - 2s + 3 + Y = 0 \Rightarrow Y(s^2+1) = 2s - 3 \Rightarrow Y = 2s/(s^2+1) - 3/(s^2+1) \Rightarrow y = 2\cos t - 3\sin t$."),
    (RESOL, "dificil",
     r"Resuelva $y'' + 2y' + 5y = 0$, $y(0) = 1$, $y'(0) = 0$.",
     r"$y = e^{-t}\big(\cos 2t + \tfrac{1}{2}\sin 2t\big)$", r"$y = e^{-t}\cos 2t$",
     r"$y = e^{t}(\cos 2t + 2\sin 2t)$", r"$y = e^{-2t}\cos t$", "A",
     r"$s^2Y - s + 2(sY-1) + 5Y = 0 \Rightarrow Y(s^2+2s+5) = s+2 \Rightarrow Y = \tfrac{s+1}{(s+1)^2+4} + \tfrac{1}{(s+1)^2+4}$. Inversa: $e^{-t}\cos(2t) + \tfrac{1}{2}e^{-t}\sin(2t)$."),
    (RESOL, "dificil",
     r"Resuelva $y'' - 3y' + 2y = e^t$, $y(0) = 0$, $y'(0) = 0$ (caso resonante).",
     r"$y = -t e^t + e^{2t} - e^t$", r"$y = (e^{2t} - 1)/2$",
     r"$y = e^{2t} - e^t - t e^t$", r"$y = t e^t$", "C",
     r"$Y(s^2 - 3s + 2) = 1/(s-1) \Rightarrow Y = 1/[(s-1)^2(s-2)]$. Fracciones parciales: $Y = -1/(s-1) - 1/(s-1)^2 + 1/(s-2)$. Inversa: $-e^t - te^t + e^{2t} = e^{2t} - e^t - te^t$."),
]

# --- TRASLACIONES Y CONVOLUCION (12 nuevas) ---
TRASL = "Traslaciones y convolución"
trasl_rows = [
    (TRASL, "facil",
     r"Calcule $\mathcal{L}\{u(t-3)\}$ donde $u$ es la función escalón unitario.",
     r"$1/s$", r"$e^{-3s}/s$", r"$e^{3s}/s$", r"$3e^{-s}/s$", "B",
     r"$\mathcal{L}\{u(t-a)\} = e^{-as}/s$. Con $a=3$: $e^{-3s}/s$."),
    (TRASL, "facil",
     r"La convolución $f*g$ de dos funciones se define como:",
     r"$\int_0^t f(\tau)\,g(t-\tau)\,d\tau$", r"$f(t)\cdot g(t)$",
     r"$f(t) + g(t)$", r"$\int_0^\infty f(\tau)\,g(\tau)\,d\tau$", "A",
     r"La convolución $f*g$ se define como $\int_0^t f(\tau) g(t-\tau)\,d\tau$ y satisface $\mathcal{L}\{f*g\} = F(s)G(s)$."),
    (TRASL, "medio",
     r"Calcule $\mathcal{L}\{e^{2t}\sin(3t)\}$.",
     r"$3/[(s-2)^2 + 9]$", r"$3/(s^2 + 9) - 2$",
     r"$(s-2)/[(s-2)^2 + 9]$", r"$3/(s^2 - 2s + 13)$", "A",
     r"$\mathcal{L}\{\sin 3t\} = 3/(s^2+9)$. Por traslación en $s$ con $a=2$: $3/[(s-2)^2 + 9]$."),
    (TRASL, "medio",
     r"Calcule $\mathcal{L}\{u(t-\pi)\sin(t-\pi)\}$.",
     r"$e^{-\pi s}/(s^2+1)$", r"$\sin(t-\pi)$", r"$e^{\pi s}/(s^2+1)$", r"$-1/(s^2+1)$", "A",
     r"$\mathcal{L}\{u(t-a)f(t-a)\} = e^{-as}F(s)$. Con $f(t)=\sin t$, $F(s)=1/(s^2+1)$ y $a=\pi$: $e^{-\pi s}/(s^2+1)$."),
    (TRASL, "medio",
     r"Usando convolución, calcule $\mathcal{L}^{-1}\big\{\tfrac{1}{s(s-1)}\big\}$.",
     r"$e^t - 1$", r"$1 - e^t$", r"$t e^t$", r"$e^t + 1$", "A",
     r"$\mathcal{L}^{-1}\{1/s\}=1$ y $\mathcal{L}^{-1}\{1/(s-1)\}=e^t$. Convolución: $\int_0^t e^{t-\tau}\,d\tau = e^t - 1$."),
    (TRASL, "medio",
     r"Calcule la convolución $1*1$, donde $f(t)=g(t)=1$.",
     r"$1$", r"$t$", r"$t^2$", r"$1/2$", "B",
     r"$1*1 = \int_0^t 1\cdot 1\,d\tau = t$."),
    (TRASL, "dificil",
     r"Usando convolución, calcule $(t)*(e^t)$.",
     r"$e^t - t - 1$", r"$t e^t$", r"$e^t - 1$", r"$t^2 e^t/2$", "A",
     r"$(t)*(e^t) = \int_0^t \tau e^{t-\tau}d\tau = e^t\int_0^t \tau e^{-\tau}d\tau$. Por partes: $\int_0^t \tau e^{-\tau}d\tau = 1 - (t+1)e^{-t}$. Multiplicando por $e^t$: $e^t - (t+1) = e^t - t - 1$."),
    (TRASL, "dificil",
     r"Resuelva el PVI $y' + y = u(t-1)$, $y(0) = 0$.",
     r"$y(t) = u(t-1)\big(1 - e^{-(t-1)}\big)$", r"$y(t) = 1 - e^{-t}$",
     r"$y(t) = u(t-1)$", r"$y(t) = e^{-t}$", "A",
     r"$sY + Y = e^{-s}/s \Rightarrow Y = e^{-s}/[s(s+1)]$. Como $1/[s(s+1)] = 1/s - 1/(s+1)$, su inversa es $1 - e^{-t}$. Por traslación en $t$ con $a=1$: $u(t-1)(1 - e^{-(t-1)})$."),
    (TRASL, "dificil",
     r"Calcule $\mathcal{L}^{-1}\big\{\tfrac{s+3}{(s+3)^2 + 4}\big\}$.",
     r"$e^{3t}\cos(2t)$", r"$e^{-3t}\cos(2t)$", r"$e^{-3t}\sin(2t)$", r"$\cos(2t)$", "B",
     r"$\mathcal{L}^{-1}\{s/(s^2+4)\} = \cos(2t)$. Por traslación inversa con $a=-3$: $e^{-3t}\cos(2t)$."),
    (TRASL, "dificil",
     r"Calcule $\mathcal{L}^{-1}\big\{\tfrac{e^{-2s}}{s^2+1}\big\}$.",
     r"$u(t-2)\sin(t-2)$", r"$\sin(t-2)$", r"$u(t-2)\cos(t-2)$", r"$u(t-2)$", "A",
     r"$\mathcal{L}^{-1}\{1/(s^2+1)\} = \sin(t)$. Con factor $e^{-2s}$ aplicamos traslación en $t$ con $a=2$: $u(t-2)\sin(t-2)$."),
    (TRASL, "dificil",
     r"Calcule $\mathcal{L}\{(\sin t)*(\cos t)\}$ usando el teorema de convolución.",
     r"$1/(s^2+1)^2$", r"$s/(s^2+1)^2$", r"$(s+1)/(s^2+1)^2$", r"$1/(s^2+1)$", "B",
     r"$\mathcal{L}\{f*g\} = F(s)G(s) = \tfrac{1}{s^2+1}\cdot\tfrac{s}{s^2+1} = \tfrac{s}{(s^2+1)^2}$."),
    (TRASL, "dificil",
     r"Calcule $\mathcal{L}^{-1}\big\{\tfrac{1}{(s-2)(s+1)}\big\}$ por convolución.",
     r"$(e^{2t} - e^{-t})/3$", r"$(e^{2t} + e^{-t})/3$", r"$e^{2t} - e^{-t}$", r"$e^{-t} - e^{2t}$", "A",
     r"$\mathcal{L}^{-1}\{1/(s-2)\} = e^{2t}$ y $\mathcal{L}^{-1}\{1/(s+1)\} = e^{-t}$. Convolución: $\int_0^t e^{2\tau} e^{-(t-\tau)}d\tau = e^{-t}\int_0^t e^{3\tau}d\tau = (e^{2t} - e^{-t})/3$."),
]

# --- MULTIPLICACION POR t Y FUNCIONES PERIODICAS (16 nuevas) ---
MULT = "Multiplicación por t y funciones periódicas"
mult_rows = [
    (MULT, "facil",
     r"$\mathcal{L}\{t f(t)\}$ es igual a:",
     r"$-F'(s)$", r"$F'(s)$", r"$sF(s)$", r"$F(s)/s$", "A",
     r"Por la propiedad de derivación de transformadas: $\mathcal{L}\{t^n f(t)\} = (-1)^n F^{(n)}(s)$. Con $n=1$: $-F'(s)$."),
    (MULT, "facil",
     r"$\mathcal{L}\{t^2 f(t)\}$ es igual a:",
     r"$-F''(s)$", r"$F''(s)$", r"$s^2 F(s)$", r"$-2F'(s)$", "B",
     r"$\mathcal{L}\{t^n f(t)\} = (-1)^n F^{(n)}(s)$. Con $n=2$: $(-1)^2 F''(s) = F''(s)$."),
    (MULT, "facil",
     r"$\mathcal{L}\{t e^{at}\}$ es igual a:",
     r"$1/(s-a)$", r"$1/(s-a)^2$", r"$1/(s+a)^2$", r"$a/(s-a)^2$", "B",
     r"$F(s) = \mathcal{L}\{e^{at}\} = 1/(s-a)$. Entonces $\mathcal{L}\{te^{at}\} = -F'(s) = 1/(s-a)^2$."),
    (MULT, "facil",
     r"Una función $f(t)$ es periódica con período $T>0$ si:",
     r"$f(t+T) = f(t)$ para todo $t \geq 0$", r"$f(T) = 0$",
     r"$f(t) = e^{-Tt}$", r"$f$ es continua en $[0,T]$", "A",
     r"Por definición, $f$ es periódica con período $T$ cuando $f(t+T) = f(t)$ para todo $t$ en el dominio."),
    (MULT, "facil",
     r"Si $f$ es periódica con período $T$, su transformada de Laplace es:",
     r"$\tfrac{1}{T}\int_0^T f(t)\,dt$", r"$\tfrac{1}{1-e^{-sT}}\int_0^T e^{-st}f(t)\,dt$",
     r"$\tfrac{1}{T}\int_0^\infty e^{-st}f(t)\,dt$", r"$T\cdot F(s)$", "B",
     r"La fórmula de funciones periódicas es $\mathcal{L}\{f\} = \tfrac{1}{1-e^{-sT}}\int_0^T e^{-st}f(t)\,dt$, válida para $s>0$."),
    (MULT, "facil",
     r"Sea $F(s) = 1/(s^2+1)$. Calcule $-F'(s)$, que corresponde a $\mathcal{L}\{t\sin t\}$.",
     r"$2s/(s^2+1)^2$", r"$-2s/(s^2+1)^2$", r"$1/(s^2+1)^2$", r"$-1/(s^2+1)^2$", "A",
     r"$F'(s) = -2s/(s^2+1)^2$. Por lo tanto $-F'(s) = 2s/(s^2+1)^2$."),
    (MULT, "medio",
     r"Calcule $\mathcal{L}\{t e^{2t}\}$.",
     r"$1/(s-2)^2$", r"$1/(s+2)^2$", r"$2/(s-2)^2$", r"$e^{2t}/s^2$", "A",
     r"$F(s) = 1/(s-2)$. $\mathcal{L}\{te^{2t}\} = -F'(s) = 1/(s-2)^2$."),
    (MULT, "medio",
     r"Calcule $\mathcal{L}\{t\cos(t)\}$.",
     r"$(s^2-1)/(s^2+1)^2$", r"$-2s/(s^2+1)^2$", r"$s/(s^2+1)^2$", r"$1/(s^2+1)^2$", "A",
     r"$F(s) = s/(s^2+1)$. $F'(s) = (1-s^2)/(s^2+1)^2$. $\mathcal{L}\{t\cos t\} = -F'(s) = (s^2-1)/(s^2+1)^2$."),
    (MULT, "medio",
     r"Calcule $\mathcal{L}\{t^2 e^{3t}\}$.",
     r"$2/(s-3)^3$", r"$1/(s-3)^3$", r"$6/(s-3)^4$", r"$2/(s+3)^3$", "A",
     r"$\mathcal{L}\{t^2\} = 2/s^3$. Por traslación en $s$ con $a=3$: $2/(s-3)^3$."),
    (MULT, "medio",
     r"Calcule $\mathcal{L}^{-1}\big\{1/(s+2)^2\big\}$.",
     r"$t e^{-2t}$", r"$t e^{2t}$", r"$e^{-2t}$", r"$t^2 e^{-2t}$", "A",
     r"$\mathcal{L}\{te^{-2t}\} = 1/(s+2)^2$. Por unicidad, $\mathcal{L}^{-1}\{1/(s+2)^2\} = te^{-2t}$."),
    (MULT, "medio",
     r"Sea $f(t)$ la onda cuadrada con período $T=2$, $f(t)=1$ en $[0,1)$ y $f(t)=0$ en $[1,2)$. Calcule $\int_0^2 e^{-st} f(t)\,dt$.",
     r"$(1 - e^{-s})/s$", r"$1/s$", r"$(1 + e^{-s})/s$", r"$e^{-s}/s$", "A",
     r"$\int_0^2 e^{-st}f(t)\,dt = \int_0^1 e^{-st}\,dt = [-e^{-st}/s]_0^1 = (1 - e^{-s})/s$."),
    (MULT, "medio",
     r"Si $\mathcal{L}\{f(t)\} = F(s)$ y $f(0^+)$ es finito, entonces $\mathcal{L}\{f(t)/t\}$ es:",
     r"$\int_0^s F(\sigma)\,d\sigma$", r"$\int_s^\infty F(\sigma)\,d\sigma$",
     r"$-F'(s)$", r"$F(s)/s$", "B",
     r"Por la propiedad de integración de transformadas: $\mathcal{L}\{f(t)/t\} = \int_s^\infty F(\sigma)\,d\sigma$, válida cuando $\lim_{t\to 0^+} f(t)/t$ existe."),
    (MULT, "dificil",
     r"Calcule $\mathcal{L}\{t^2\sin(t)\}$ usando derivación de transformadas.",
     r"$(6s^2 - 2)/(s^2+1)^3$", r"$-2/(s^2+1)^3$", r"$-2s/(s^2+1)^2$", r"$2(s^2-1)/(s^2+1)^2$", "A",
     r"$F(s) = 1/(s^2+1)$. $F'(s) = -2s/(s^2+1)^2$. $F''(s) = (6s^2 - 2)/(s^2+1)^3$. $\mathcal{L}\{t^2\sin t\} = (-1)^2 F''(s) = (6s^2 - 2)/(s^2+1)^3$."),
    (MULT, "dificil",
     r"La transformada de la onda cuadrada $f(t)$ periódica con $T=2$, $f(t)=1$ en $[0,1)$, $f(t)=0$ en $[1,2)$, es:",
     r"$1/s$", r"$(1-e^{-s})/[s(1-e^{-2s})]$", r"$e^{-s}/s$", r"$(1+e^{-s})/s$", "B",
     r"$\mathcal{L}\{f\} = \tfrac{1}{1-e^{-sT}}\int_0^T e^{-st}f(t)\,dt = \tfrac{(1-e^{-s})/s}{1-e^{-2s}}$."),
    (MULT, "dificil",
     r"Calcule $\mathcal{L}^{-1}\big\{2s/(s^2+1)^2\big\}$.",
     r"$t\sin(t)$", r"$t\cos(t)$", r"$\sin t - t\cos t$", r"$\sin t + t\cos t$", "A",
     r"$\mathcal{L}\{t\sin t\} = -d/ds[1/(s^2+1)] = 2s/(s^2+1)^2$. Por unicidad, la inversa es $t\sin t$."),
    (MULT, "dificil",
     r"Para $f(t) = t$ en $[0,T)$ extendida con período $T$ (diente de sierra), calcule $\int_0^T t\,e^{-st}\,dt$.",
     r"$1/s^2 - (T+1)e^{-sT}/s^2$", r"$1/s^2 - e^{-sT}(1/s^2 + T/s)$",
     r"$T/s$", r"$(1 - e^{-sT})/s^2$", "B",
     r"Integrando por partes con $u=t$, $dv=e^{-st}dt$: $\int_0^T t e^{-st}dt = -Te^{-sT}/s + (1-e^{-sT})/s^2 = 1/s^2 - e^{-sT}(1/s^2 + T/s)$."),
]

# --- SISTEMAS Y ECUACIONES CON COEFICIENTES VARIABLES (20 nuevas) ---
SIST = "Sistemas y ecuaciones con coeficientes variables"
sist_rows = [
    (SIST, "facil",
     r"Para resolver el sistema $x'(t) = ax + by$, $y'(t) = cx + dy$ con Laplace, ¿qué se hace primero?",
     r"Aplicar Laplace a ambas ecuaciones por separado", r"Sumar las dos ecuaciones",
     r"Restar las dos ecuaciones", r"Aplicar la transformada inversa", "A",
     r"El método consiste en transformar cada ecuación, obteniendo un sistema algebraico lineal en $X(s)$ y $Y(s)$."),
    (SIST, "facil",
     r"Tras aplicar Laplace al sistema $x' = y$, $y' = x$ con $x(0)=1$, $y(0)=0$, las ecuaciones algebraicas son:",
     r"$sX = Y,\;\;sY = X$", r"$sX - 1 = Y,\;\;sY = X$",
     r"$sX + 1 = Y,\;\;sY - 1 = X$", r"$X = Y,\;\;Y = X$", "B",
     r"$\mathcal{L}\{x'\} = sX - x(0) = sX - 1$ y $\mathcal{L}\{y'\} = sY - y(0) = sY$."),
    (SIST, "facil",
     r"Para una EDO con coeficiente variable $t y'(t)$, ¿qué propiedad se usa al aplicar Laplace?",
     r"$\mathcal{L}\{tf(t)\} = -F'(s)$", r"$\mathcal{L}\{tf(t)\} = sF(s)$",
     r"$\mathcal{L}\{tf(t)\} = F(s)/s$", r"$\mathcal{L}\{tf(t)\} = F(s) - f(0)$", "A",
     r"La propiedad de derivación de transformadas: la multiplicación por $t$ en el dominio $t$ corresponde a $-d/ds$ en el dominio $s$."),
    (SIST, "facil",
     r"Para resolver una EDO con coeficientes variables como $t y'' + 2y' + ty = 0$, la transformada de Laplace produce típicamente:",
     r"una ecuación algebraica simple", r"una nueva EDO en $Y(s)$",
     r"una integral impropia", r"una serie de potencias", "B",
     r"Como $\mathcal{L}\{tf(t)\} = -F'(s)$, los coeficientes en $t$ producen derivadas de $Y(s)$, generando otra EDO en $Y(s)$."),
    (SIST, "facil",
     r"$\mathcal{L}\{t y'(t)\}$ en términos de $Y(s)$ y sus derivadas es:",
     r"$-sY'(s) - Y(s)$", r"$sY(s)$", r"$-Y'(s)$", r"$tY(s)$", "A",
     r"$\mathcal{L}\{ty'\} = -\tfrac{d}{ds}\mathcal{L}\{y'\} = -\tfrac{d}{ds}[sY(s) - y(0)] = -sY'(s) - Y(s)$."),
    (SIST, "facil",
     r"En un sistema lineal $x'=Ax$ resuelto con Laplace, la solución para $X(s)$ involucra:",
     r"$(sI - A)^{-1}\,x(0)$", r"$A\,x(0)$", r"$s\,x(0)$", r"$x(0)/s$", "A",
     r"Aplicando Laplace: $sX - x(0) = AX \Rightarrow (sI - A)X = x(0) \Rightarrow X = (sI-A)^{-1}x(0)$."),
    (SIST, "medio",
     r"Resuelva el sistema $x' = y$, $y' = -x$ con $x(0)=1$, $y(0)=0$ usando Laplace.",
     r"$x = \cos t,\;\;y = -\sin t$", r"$x = \sin t,\;\;y = \cos t$",
     r"$x = e^t,\;\;y = -e^t$", r"$x = \cos t,\;\;y = \sin t$", "A",
     r"$sX-1 = Y$ y $sY = -X$. Sustituyendo: $s(sX-1) = -X \Rightarrow X(s^2+1) = s \Rightarrow X = s/(s^2+1)$, así $x = \cos t$. Luego $Y = sX - 1 = -1/(s^2+1)$, $y = -\sin t$."),
    (SIST, "medio",
     r"Aplicando Laplace al sistema $x' = -x + y$, $y' = -y$, con $x(0)=0$, $y(0)=1$, ¿cuál es $Y(s)$?",
     r"$1/(s+1)$", r"$1/s$", r"$1/(s^2+1)$", r"$s/(s^2+1)$", "A",
     r"$sY - 1 = -Y \Rightarrow Y(s+1) = 1 \Rightarrow Y = 1/(s+1)$. La inversa $y(t) = e^{-t}$."),
    (SIST, "medio",
     r"Continuando con $x' = -x + y$, $y' = -y$, $x(0)=0$, $y(0)=1$, ¿cuál es $x(t)$?",
     r"$x(t) = e^{-t}$", r"$x(t) = t e^{-t}$", r"$x(t) = 1 - e^{-t}$", r"$x(t) = \sin(t) e^{-t}$", "B",
     r"$sX = -X + Y = -X + 1/(s+1) \Rightarrow X(s+1) = 1/(s+1) \Rightarrow X = 1/(s+1)^2$. Inversa: $te^{-t}$."),
    (SIST, "medio",
     r"Para la EDO con coeficiente variable $ty' - y = 0$, ¿qué EDO en $Y(s)$ resulta tras aplicar Laplace?",
     r"$sY'(s) + 2Y(s) = 0$", r"$-sY' = Y$", r"$sY' = 0$", r"$Y' = 0$", "A",
     r"$\mathcal{L}\{ty'\} = -sY' - Y$ y $\mathcal{L}\{y\} = Y$. Entonces $-sY' - Y - Y = 0 \Rightarrow sY' + 2Y = 0$."),
    (SIST, "medio",
     r"Resuelva la EDO separable $sY'(s) + 2Y(s) = 0$ para $Y(s)$.",
     r"$Y(s) = C/s^2$", r"$Y(s) = Cs^2$", r"$Y(s) = Ce^{-2s}$", r"$Y(s) = Cs$", "A",
     r"$\tfrac{dY}{Y} = -\tfrac{2\,ds}{s} \Rightarrow \ln|Y| = -2\ln|s| + C_1 \Rightarrow Y = C/s^2$."),
    (SIST, "medio",
     r"Si $Y(s) = C/s^2$, ¿cuál es $y(t) = \mathcal{L}^{-1}\{Y(s)\}$?",
     r"$y(t) = Ct$", r"$y(t) = C$", r"$y(t) = C/t$", r"$y(t) = Ct^2$", "A",
     r"$\mathcal{L}^{-1}\{1/s^2\} = t$, luego $y(t) = Ct$. Verificación directa: $y = Ct$ satisface $ty' - y = Ct - Ct = 0$."),
    (SIST, "medio",
     r"Para el sistema $x' = 2x$, $y' = x + 2y$ con $x(0)=1$, $y(0)=0$, ¿cuál es $X(s)$?",
     r"$1/(s-2)$", r"$1/(s+2)$", r"$s/(s-2)$", r"$1/s$", "A",
     r"$sX - 1 = 2X \Rightarrow X(s-2) = 1 \Rightarrow X = 1/(s-2)$."),
    (SIST, "medio",
     r"En el sistema anterior $x'=2x$, $y'=x+2y$ con $x(0)=1$, $y(0)=0$, ¿cuál es $y(t)$?",
     r"$te^{2t}$", r"$e^{2t}$", r"$\sin(2t)$", r"$1 - e^{2t}$", "A",
     r"$sY = X + 2Y \Rightarrow Y(s-2) = X = 1/(s-2) \Rightarrow Y = 1/(s-2)^2$. Inversa: $te^{2t}$."),
    (SIST, "dificil",
     r"La ecuación de Bessel de orden cero $ty'' + y' + ty = 0$, con $y(0)=1$, al aplicar Laplace produce:",
     r"$(s^2+1)Y'(s) + sY(s) = 0$", r"$(s^2+1)Y(s) = 0$",
     r"$Y'(s) = -sY(s)$", r"$-sY(s) = 1$", "A",
     r"$\mathcal{L}\{ty''\} = -\tfrac{d}{ds}[s^2Y - sy(0) - y'(0)] = -2sY - s^2Y' + 1$. $\mathcal{L}\{y'\} = sY - 1$. $\mathcal{L}\{ty\} = -Y'$. Sumando: $-2sY - s^2Y' + 1 + sY - 1 - Y' = 0 \Rightarrow (s^2+1)Y' + sY = 0$."),
    (SIST, "dificil",
     r"Resuelva $(s^2+1)Y'(s) + sY(s) = 0$ por separación de variables.",
     r"$Y(s) = C/\sqrt{s^2+1}$", r"$Y(s) = Cs$", r"$Y(s) = Ce^{-s}$", r"$Y(s) = C(s^2+1)$", "A",
     r"$\tfrac{dY}{Y} = -\tfrac{s\,ds}{s^2+1} \Rightarrow \ln|Y| = -\tfrac{1}{2}\ln(s^2+1) + C_1 \Rightarrow Y = C/(s^2+1)^{1/2}$."),
    (SIST, "dificil",
     r"Sabiendo que $\mathcal{L}\{J_0(t)\} = 1/\sqrt{s^2+1}$, ¿cuál es la solución de la ecuación de Bessel $ty'' + y' + ty = 0$ con $y(0)=1$?",
     r"$y(t) = J_0(t)$", r"$y(t) = J_1(t)$", r"$y(t) = \cos(t)$", r"$y(t) = e^{-t}$", "A",
     r"De $Y(s) = C/\sqrt{s^2+1}$ con $y(0)=1$ se obtiene $C=1$ (vía teorema del valor inicial). Por unicidad, $y(t) = J_0(t)$."),
    (SIST, "dificil",
     r"Para el sistema $x' = x + 2y$, $y' = 4x + 3y$ con $x(0)=1$, $y(0)=0$, los valores propios de la matriz son:",
     r"$\lambda = 5$ y $\lambda = -1$", r"$\lambda = 1$ y $\lambda = 3$",
     r"$\lambda = 2$ y $\lambda = 4$", r"$\lambda = -5$ y $\lambda = 1$", "A",
     r"$\det(A - \lambda I) = (1-\lambda)(3-\lambda) - 8 = \lambda^2 - 4\lambda - 5 = (\lambda-5)(\lambda+1)$. Raíces: $5$ y $-1$."),
    (SIST, "dificil",
     r"Para resolver $x' = Ax + f(t)$ con Laplace, la fórmula explícita de $X(s)$ es:",
     r"$(sI - A)^{-1}\,x(0) + (sI - A)^{-1} F(s)$", r"$s\,x(0) + A\,F(s)$",
     r"$e^{At}\,x(0) + F(s)$", r"$A^{-1}\,x(0)$", "A",
     r"$sX - x(0) = AX + F(s) \Rightarrow (sI-A)X = x(0) + F(s) \Rightarrow X = (sI-A)^{-1}[x(0) + F(s)]$."),
    (SIST, "dificil",
     r"Para la EDO de Laguerre $ty'' + (1-t)y' + ny = 0$ con condición inicial dada, al aplicar Laplace se obtiene:",
     r"una EDO de primer orden en $Y(s)$", r"una ecuación algebraica simple",
     r"una serie de potencias", r"una EDO de segundo orden en $Y(s)$", "A",
     r"$\mathcal{L}\{ty''\}$ y $\mathcal{L}\{ty'\}$ generan derivadas de $Y(s)$ (a lo más $Y'(s)$); los términos sin $t$ producen $Y(s)$. La ecuación resultante es de primer orden en $Y$."),
]


def main():
    new_rows = resol_rows + trasl_rows + mult_rows + sist_rows
    counts = {
        RESOL: 12,
        TRASL: 12,
        MULT: 16,
        SIST: 20,
    }
    expected = sum(counts.values())
    if len(new_rows) != expected:
        raise ValueError(f"Esperaba {expected} preguntas, obtuve {len(new_rows)}")

    # Verificacion de balance por dificultad
    from collections import Counter
    diff_count = Counter((row[0], row[1]) for row in new_rows)
    print("Distribucion nueva:")
    for k in sorted(diff_count):
        print(f"  {diff_count[k]:3}  {k}")

    with open(CSV, "a", encoding="utf-8", newline="") as f:
        writer = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
        for row in new_rows:
            writer.writerow([CAP] + list(row))

    print(f"\nAgregadas {len(new_rows)} preguntas al CSV.")


if __name__ == "__main__":
    main()
