import { useState } from "react";

// ═══════════════════════════════════════════════════════════════
// DATOS VERIFICADOS - Investigación Ramos PUCV
// Pontificia Universidad Católica de Valparaíso · V Región
// Tier 3 · Complemento UTFSM
//
// Hallazgo estructural: PUCV NO tiene un Plan Común único como UCH/USACH.
// Cada Escuela de Ingeniería es carrera independiente, pero comparten un
// núcleo de matemáticas y física. Coexisten DOS esquemas de códigos:
//   - Plan vigente EIC (Escuela de Ingeniería Civil, 2019/2023): MAT1001-1005
//   - Códigos PUCV-wide (otras Escuelas + Lic/Ped Mat/Fís): MAT1115/1118/1127/1129/1210/1220/1221
// Esta investigación usa MAT1001-1005 para "Plan Común" (es el más
// documentado oficialmente) y MAT11xx/12xx para Lic. Física y Pedagogías
// (donde están verificados por syllabus oficial fis.ucv.cl).
//
// Fuentes:
//   - Escuela de Ingeniería Civil (plan vigente, PDFs oficiales):
//     · eic.pucv.cl/estudia-con-nosotros/plan-de-estudios/
//     · MAT1001 Fundamentos: eic.pucv.cl/wp-content/uploads/2023/01/1-MAT1001-Fundamentos-de-Matematicas-para-Ingenieria-FIN.pdf
//     · MAT1002 Cálculo Dif e Int: eic.pucv.cl/wp-content/uploads/2023/01/2-MAT1002-Calculo-diferencial-e-integral-FIN.pdf
//     · MAT1003 Cálculo VV: eic.pucv.cl/wp-content/uploads/2023/01/3-MAT1003-Calculo-en-varias-variables-FIN.pdf
//     · MAT1004 Álgebra Lineal: eic.pucv.cl/wp-content/uploads/2023/01/2-MAT1004-Algebra-Lineal-FIN.pdf
//     · FIS1002 / FIS1035 / CIV-1006: idem repo eic.pucv.cl/wp-content/uploads/2023/01/
//   - Ingeniería Comercial (Escuela de Negocios y Economía):
//     · pucv.cl/uuaa/negocioseconomia/malla-curricular
//     · negociosyeconomia.pucv.cl/ingenieria-comercial
//     · pucv.cl/uuaa/site/docs/20181122/20181122213126/malla_ingenieria_comercial.pdf
//   - Instituto de Matemáticas (IMA) — Licenciatura y Pedagogía:
//     · ima.ucv.cl/programas/licenciatura/
//     · ima.ucv.cl/programas/pedagogia/
//     · Malla 2022 Lic: static.ima.ucv.cl.s3.amazonaws.com/wp-content/uploads/2013/08/Malla-Licenciatura-en-Matematicas-2022_prerrequisitos.png
//   - Instituto de Física (IF) — Licenciatura y Pedagogía:
//     · fis.ucv.cl/licenciatura-en-fisica/
//     · fis.ucv.cl/pedagogia-en-fisica-3/
//     · Syllabus MAT1115/1118 públicos: fis.ucv.cl/wp-content/uploads/2020/11/
//   - Studocu (códigos cruzados y materiales): studocu.com/cl/institution/pontificia-universidad-catolica-de-valparaiso/
// Fecha de investigación: Mayo 2026
// ═══════════════════════════════════════════════════════════════

// ─── CATÁLOGO BASE SE REMONTA (9 cursos, ids fijos) ──────────────
const seRemontaCursos = [
  { id: "precalculo-cero", nombre: "Precálculo desde Cero", tipo: "general", modulos: 68, precio: 40000, color: "#8B5CF6",
    contenidos: ["Conjuntos y números", "Álgebra de expresiones", "Ecuaciones e inecuaciones", "Funciones", "Trigonometría", "Geometría analítica"] },
  { id: "nivelacion-ing", nombre: "Nivelación Ingeniería", tipo: "general", modulos: 43, precio: 20000, color: "#7C3AED",
    contenidos: ["Repaso números reales", "Funciones elementales", "Trigonometría aplicada", "Vectores y geometría", "Lógica e inducción", "Polinomios"] },
  { id: "algebra-lineal-gen", nombre: "Álgebra Lineal", tipo: "general", modulos: 52, precio: 40000, color: "#6366F1",
    contenidos: ["Espacio", "Sistemas de Ecuaciones", "Álgebra de Matrices", "Determinantes", "Espacios y Subespacios Vectoriales", "Valores y Vectores Propios", "Ortogonalidad", "Matrices Simétricas"] },
  { id: "calculo-1var-gen", nombre: "Cálculo en una Variable", tipo: "general", modulos: 85, precio: 40000, color: "#3B82F6",
    contenidos: ["Límites y continuidad", "Derivadas", "Aplicaciones de la derivada", "Integrales", "Técnicas de integración", "Aplicaciones de la integral"] },
  { id: "calculo-dif-gen", nombre: "Cálculo Diferencial", tipo: "general", modulos: 52, precio: 35000, color: "#0EA5E9",
    contenidos: ["Números reales e inecuaciones", "Funciones (dominio, recorrido, transformaciones, polinomiales, exp, log)", "Límites y continuidad", "Derivadas y reglas de derivación", "Aplicaciones de la derivada (TVM, L'Hôpital, optimización, graficación)"] },
  { id: "calculo-int-gen", nombre: "Cálculo Integral", tipo: "general", modulos: 48, precio: 35000, color: "#06B6D4",
    contenidos: ["Antiderivadas e integral indefinida", "Teorema Fundamental del Cálculo", "Técnicas (sustitución, partes, fracciones parciales, sustitución trigonométrica)", "Aplicaciones (área, volúmenes, longitud de arco, parametrizadas, polares)", "Integrales impropias", "Sucesiones y series (criterios, Taylor, potencias)"] },
  { id: "calculo-vvar-gen", nombre: "Cálculo en Varias Variables", tipo: "general", modulos: 41, precio: 40000, color: "#14B8A6",
    contenidos: ["Funciones de varias variables", "Derivadas parciales y gradiente", "Máximos y mínimos", "Multiplicadores de Lagrange", "Integrales dobles y triples", "Coordenadas curvilíneas"] },
  { id: "calculo-vec-gen", nombre: "Cálculo Vectorial", tipo: "general", modulos: 31, precio: 40000, color: "#10B981",
    contenidos: ["Curvas paramétricas y vectoriales", "Integrales de línea (escalares y vectoriales)", "Teorema de Green", "Rotacional y divergencia", "Integrales de superficie", "Teorema de Stokes", "Teorema de la divergencia"] },
  { id: "ec-dif-gen", nombre: "Ecuaciones Diferenciales", tipo: "general", modulos: 42, precio: 40000, color: "#EAB308",
    contenidos: ["EDO primer orden (separable, lineal, exacta, factor integrante, homogénea, Bernoulli)", "EDO segundo orden (coef constantes, Cauchy-Euler, coef indeterminados, variación parámetros)", "Sistemas de ED", "Transformada de Laplace (propiedades, traslación, escalón, convolución, Dirac)", "Soluciones por series (Bessel, Frobenius)", "Aplicaciones (mecánica, circuitos, modelos)"] },
];

// ─── CARRERAS PUCV ───────────────────────────────────────────────
const carreras = [
  // ═══════════════════════════════════════
  // CARRERA 1 — Plan Común Ingeniería Civil (Escuela de Ingeniería Civil EIC)
  // ═══════════════════════════════════════
  {
    id: "plan-comun-ing-civil",
    nombre: "Plan Común Ingeniería Civil (EIC)",
    facultad: "Facultad de Ingeniería · Escuela de Ingeniería Civil (EIC)",
    duracion: "12 semestres totales (4 semestres ciencias básicas + ciclo profesional)",
    mallaUrl: "https://eic.pucv.cl/estudia-con-nosotros/plan-de-estudios/",
    nota: "Acreditación institucional vigente · Plan vigente desde 2019/2023 con códigos MAT1001-1005 · PUCV NO tiene Plan Común único entre escuelas; cada Escuela de Ingeniería es carrera independiente (Civil, Industrial, Informática, Eléctrica, Mecánica, Química, Bioquímica, Construcción, Transporte, Minas/Metalúrgica, Ciencia de Datos) pero comparten ciencias básicas con códigos variables. Esta entrada cubre el plan EIC (Civil obras/hidráulica/estructuras), que es el más documentado.",
    especialidades: [
      "Ing. Civil (obras civiles, hidráulica, estructuras)",
      "Ing. Civil Industrial",
      "Ing. Civil Informática",
      "Ing. Civil Eléctrica",
      "Ing. Civil Electrónica",
      "Ing. Civil Telecomunicaciones",
      "Ing. Civil Mecánica",
      "Ing. Civil Química",
      "Ing. Civil Bioquímica",
      "Ing. Civil en Construcción",
      "Ing. Civil de Transporte",
      "Ing. Civil de Minas",
      "Ing. Civil Metalúrgica",
      "Ing. Civil en Ciencia de Datos",
    ],
    ramos: [
      // ── SEMESTRE 1 ──
      {
        nombre: "MAT1001 Fundamentos de Matemáticas para Ingeniería",
        codigo: "MAT1001",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos (ingreso a carrera)",
        fuenteContenido: "https://eic.pucv.cl/wp-content/uploads/2023/01/1-MAT1001-Fundamentos-de-Matematicas-para-Ingenieria-FIN.pdf",
        contenidos: [
          "Transición matemática escolar a universitaria: números reales, valor absoluto, intervalos, inecuaciones",
          "Álgebra elemental: potencias, raíces, productos notables, factorización, ecuaciones",
          "Funciones: definición, dominio y recorrido, composición, inversa, polinomiales, racionales",
          "Funciones exponenciales y logarítmicas: propiedades, ecuaciones",
          "Trigonometría: razones, identidades, ecuaciones trigonométricas, teoremas seno/coseno",
          "Geometría analítica: recta, circunferencia, parábola, elipse, hipérbola",
        ],
        match: ["precalculo-cero", "nivelacion-ing"],
        matchLevel: "alto",
        splitDesde: "Precálculo desde Cero (68 mód) cubre prácticamente el syllabus completo: conjuntos, álgebra, funciones, trigonometría, geometría analítica. Nivelación Ingeniería (43 mód) refuerza el ángulo ingeniería. Match combinado ~90%.",
        nota: "Ramo de nivelación obligatorio. Texto guía institucional PUCV (libro propio de la Facultad de Ingeniería: Astudillo, Silva, González, López y otros — uno de los cinco libros de la serie de Ingeniería PUCV).",
      },
      {
        nombre: "FIS1035 Introducción a la Física",
        codigo: "FIS1035",
        area: "física",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://eic.pucv.cl/wp-content/uploads/2023/01/1-FIS1035-Introduccion-a-la-Fisica-FIS.pdf",
        contenidos: [
          "Nivelación en física: unidades, magnitudes, sistema internacional",
          "Vectores: suma, producto punto y cruz, descomposición",
          "Cinemática 1D y 2D",
          "Dinámica básica: leyes de Newton",
          "Energía, trabajo y potencia",
          "Uso de herramientas TIC (calculadoras, software básico de física)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Ramo de física de nivelación. Sin curso base en catálogo Se Remonta. Útil para producción futura de 'Física Universitaria Básica' (vectores + cinemática + dinámica) — coincidencia alta con currículo de física de primer año en ingeniería chilena.",
        nota: "Obligatorio. Área Ciencias Básicas. Buen candidato para curso de física básica próximo a producir.",
      },
      // ── SEMESTRE 2 ──
      {
        nombre: "MAT1002 Cálculo Diferencial e Integral",
        codigo: "MAT1002",
        area: "matemáticas",
        semestre: 2,
        prereqs: "MAT1001 Fundamentos de Matemáticas para Ingeniería",
        fuenteContenido: "https://eic.pucv.cl/wp-content/uploads/2023/01/2-MAT1002-Calculo-diferencial-e-integral-FIN.pdf",
        contenidos: [
          "Límites y continuidad de funciones reales de variable real",
          "Derivadas: definición, reglas, regla de la cadena, derivación implícita",
          "Aplicaciones de la derivada: optimización, razón de cambio, análisis de funciones, L'Hôpital",
          "Integral indefinida y técnicas (sustitución, partes, fracciones parciales, sustitución trigonométrica)",
          "Integral definida: Teorema Fundamental del Cálculo",
          "Aplicaciones de la integral: áreas, volúmenes de revolución, longitud de arco",
        ],
        match: ["calculo-1var-gen", "calculo-dif-gen", "calculo-int-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en una Variable (85 mód) cubre completo el ramo. También Cálculo Diferencial (52 mód) + Cálculo Integral (48 mód) por separado para split modular. Match ~90%.",
        nota: "6 créditos (6h teóricas + 4h taller + 8h estudio personal). Bibliografía típica: Stewart Cálculo de una variable, Larson.",
      },
      {
        nombre: "MAT1004 Álgebra Lineal",
        codigo: "MAT1004",
        area: "matemáticas",
        semestre: 2,
        prereqs: "MAT1001 Fundamentos de Matemáticas para Ingeniería",
        fuenteContenido: "https://eic.pucv.cl/wp-content/uploads/2023/01/2-MAT1004-Algebra-Lineal-FIN.pdf",
        contenidos: [
          "Matrices y sistemas de ecuaciones lineales: Gauss-Jordan, matriz inversa",
          "Determinantes: propiedades, regla de Cramer",
          "Geometría vectorial en R² y R³: vectores, producto punto, producto cruz, rectas y planos",
          "Espacios vectoriales: subespacios, base, dimensión",
          "Transformaciones lineales",
          "Valores y vectores propios (introducción)",
        ],
        match: ["algebra-lineal-gen"],
        matchLevel: "alto",
        splitDesde: "Álgebra Lineal (52 mód) cubre todo el syllabus: sistemas, matrices, determinantes, espacios vectoriales, valores propios. Match ~95%. PUCV agrega un módulo formal de geometría vectorial R²/R³ que también está cubierto en el curso base.",
        nota: "4 créditos (4h teóricas + 2h taller + 6h estudio personal). Detalle de unidad 3 (espacios vectoriales avanzados) inferido del syllabus parcial — no verificado al 100%.",
      },
      {
        nombre: "FIS1002 Física para Ingeniería",
        codigo: "FIS1002",
        area: "física",
        semestre: 2,
        prereqs: "FIS1035 Introducción a la Física + MAT1001",
        fuenteContenido: "https://eic.pucv.cl/wp-content/uploads/2023/01/2-FIS1002-Fisica-para-Ingenieria-FIN.pdf",
        contenidos: [
          "Mecánica Newtoniana: leyes de Newton, aplicaciones",
          "Trabajo, energía cinética y potencial, conservación",
          "Sistemas de partículas, centro de masa, colisiones",
          "Rotación de sólido rígido, momento angular",
          "Oscilaciones (MAS, amortiguado, forzado)",
          "Estática y elasticidad",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica Newtoniana de nivel ingeniería. Sin curso base en catálogo. Alta demanda en mercado chileno (ramo filtro en ingeniería). Candidato prioritario a producir.",
        nota: "Obligatorio. Bibliografía típica: Serway, Sears-Zemansky-Young.",
      },
      {
        nombre: "CIV-1006 Programación Aplicada",
        codigo: "CIV-1006",
        area: "programación",
        semestre: 2,
        prereqs: "MAT1001",
        fuenteContenido: "https://eic.pucv.cl/wp-content/uploads/2023/01/2-CIV-1006-Programacion-Aplicada.pdf",
        contenidos: [
          "Algoritmia básica: pseudocódigo, diagramas de flujo",
          "MS-Excel para ingeniería: fórmulas, funciones, VBA básico",
          "MATLAB: variables, matrices, scripts, funciones",
          "Resolución de problemas numéricos con MATLAB",
          "Generación de informes de ingeniería con análisis de datos",
          "Visualización: gráficos 2D/3D",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Programación aplicada con foco en MATLAB y Excel. Sin curso base en catálogo. Candidato a curso 'Programación para Ingeniería con MATLAB' — alto volumen porque otras escuelas (Industrial, Eléctrica, Mecánica) tienen ramos análogos. Código CIV-1006 es específico EIC; otras escuelas usan códigos INF/ICI distintos.",
        nota: "Bibliografía: manuales oficiales MATLAB + tutoriales propios PUCV.",
      },
      // ── SEMESTRE 3 ──
      {
        nombre: "MAT1003 Cálculo en Varias Variables",
        codigo: "MAT1003",
        area: "matemáticas",
        semestre: 3,
        prereqs: "MAT1002 Cálculo Diferencial e Integral",
        fuenteContenido: "https://eic.pucv.cl/wp-content/uploads/2023/01/3-MAT1003-Calculo-en-varias-variables-FIN.pdf",
        contenidos: [
          "Funciones de varias variables: dominio, recorrido, gráficos, curvas de nivel",
          "Límites y continuidad en R² y R³",
          "Derivadas parciales, derivada direccional, gradiente",
          "Plano tangente y aproximación lineal",
          "Regla de la cadena para funciones de varias variables",
          "Optimización: máximos/mínimos, multiplicadores de Lagrange",
          "Integrales dobles (cartesianas, polares) y triples (cartesianas, cilíndricas, esféricas)",
          "Aplicaciones: cálculo de volúmenes, centroides",
        ],
        match: ["calculo-vvar-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en Varias Variables (41 mód) cubre todo el syllabus: derivadas parciales, gradiente, Lagrange, integrales dobles/triples, coordenadas curvilíneas. Match ~95%.",
        nota: "Bibliografía: Cálculo Real y Vectorial en Varias Variables, Carlos Martínez (PUCV, 1ra ed.) — texto institucional del IMA. También Stewart Cálculo de varias variables.",
      },
      // ── SEMESTRE 4 ──
      {
        nombre: "MAT1005 Ecuaciones Diferenciales",
        codigo: "MAT1005",
        area: "matemáticas",
        semestre: 4,
        prereqs: "MAT1003 Cálculo en Varias Variables (probable, no verificado al 100%)",
        fuenteContenido: "https://www.studocu.com/cl/course/pontificia-universidad-catolica-de-valparaiso/ecuaciones-diferenciales/3241085",
        contenidos: [
          "EDO de primer orden: separables, lineales, exactas, factor integrante, Bernoulli",
          "EDO lineales de orden superior con coeficientes constantes: homogéneas y no homogéneas",
          "Métodos: coeficientes indeterminados, variación de parámetros, Wronskiano, Teorema de Abel",
          "Sistemas de EDO lineales: valores propios, matriz exponencial",
          "Transformada de Laplace y aplicaciones (probable, no verificado al 100%)",
          "Aplicaciones: mecánica (oscilaciones), circuitos RLC, modelos de población",
        ],
        match: ["ec-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Ecuaciones Diferenciales (42 mód) cubre el syllabus completo: EDO 1° y 2° orden, sistemas, Laplace, aplicaciones. Match ~90%. Faltaría confirmar si PUCV incluye series de Frobenius/Bessel (sí están en el curso base).",
        nota: "Sin syllabus oficial público confirmado — contenidos inferidos de material de clase pública en Studocu (Clase 13 Teorema de Abel) y del estándar EDO ingeniería chilena. Código antiguo equivalente: MAT1179. Prerrequisito formal con MAT1003 inferido por progresión semestre.",
      },
    ],
  },

  // ═══════════════════════════════════════
  // CARRERA 2 — Ingeniería Comercial (Escuela de Negocios y Economía)
  // ═══════════════════════════════════════
  {
    id: "ing-comercial",
    nombre: "Ingeniería Comercial",
    facultad: "Facultad de Ciencias Económicas y Administrativas · Escuela de Negocios y Economía (ENE)",
    duracion: "10 semestres (Licenciatura al 8°, Título profesional al 10°)",
    mallaUrl: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
    nota: "Plan nuevo basado en competencias implementado desde 2023 (incluye 4 asignaturas B-learning + talleres de habilidades blandas). PUCV usa sigla interna ICA para Ing. Comercial. Sede única Valparaíso, jornada diurna. NOTA IMPORTANTE: códigos de ramo individuales NO se pudieron verificar uno por uno — el PDF oficial no fue accesible vía fetch. Se recomienda completar códigos manualmente desde el navegador.",
    especialidades: [],
    ramos: [
      // ── SEMESTRE 1 ──
      {
        nombre: "Cálculo I",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "Funciones reales de variable real: dominio, recorrido, gráficos",
          "Funciones exponenciales y logarítmicas con aplicaciones económicas",
          "Límites y continuidad",
          "Derivadas y reglas de derivación",
          "Aplicaciones de la derivada: análisis marginal, elasticidad, optimización en economía",
          "Introducción a la integral (técnicas básicas y aplicaciones a área bajo demanda/oferta)",
        ],
        match: ["calculo-dif-gen", "calculo-1var-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Diferencial (52 mód) cubre derivadas y aplicaciones (incluyendo optimización, que es el core en Ing. Comercial). Cálculo en una Variable (85 mód) si el plan exige también integrales. Match ~80% — falta enfatizar aplicaciones económicas específicas (marginal, elasticidad).",
        nota: "Código ICA no verificado individualmente.",
      },
      {
        nombre: "Introducción al Álgebra Lineal",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "Vectores y operaciones",
          "Matrices, operaciones, matriz inversa",
          "Sistemas de ecuaciones lineales: Gauss, Cramer",
          "Determinantes",
          "Espacios vectoriales (introducción)",
          "Aplicaciones: modelos input-output, programación lineal introductoria",
        ],
        match: ["algebra-lineal-gen"],
        matchLevel: "alto",
        splitDesde: "Álgebra Lineal (52 mód) cubre matrices, sistemas, determinantes, espacios. Match ~85%. Las aplicaciones económicas (Leontief, IO) se cubren en Métodos Cuantitativos.",
        nota: "Código ICA no verificado. Semestre puede variar entre S1 y S2 según versión del plan.",
      },
      {
        nombre: "Contabilidad I",
        area: "economía",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "Ecuación contable fundamental",
          "Libro diario y libro mayor",
          "Estados financieros: ESF, Estado de Resultados, EFE",
          "Principios contables (NIIF/IFRS introductorias)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Contabilidad básica. Sin curso base en catálogo Se Remonta. Candidato a curso 'Contabilidad Financiera Básica' para alumnos de negocios — alta demanda en Ing. Comercial / Adm. Empresas.",
        nota: "Registrar para pipeline de cursos de negocios. Código ICA no verificado.",
      },
      // ── SEMESTRE 2 ──
      {
        nombre: "Cálculo II",
        area: "matemáticas",
        semestre: 2,
        prereqs: "Cálculo I",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "Integrales: técnicas y aplicaciones económicas (excedente del consumidor/productor)",
          "Funciones de varias variables",
          "Derivadas parciales y aplicaciones (productividad marginal, utilidad)",
          "Optimización en varias variables: máximos/mínimos, multiplicadores de Lagrange",
          "Integrales múltiples (introducción)",
        ],
        match: ["calculo-int-gen", "calculo-vvar-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Integral (48 mód) cubre la parte de integrales. Cálculo en Varias Variables (41 mód) cubre derivadas parciales y Lagrange. Combo cubre ~85%.",
        nota: "Código ICA no verificado.",
      },
      {
        nombre: "Microeconomía I",
        area: "economía",
        semestre: 2,
        prereqs: "Introducción a la Economía (S1, no listado por ser cualitativo)",
        fuenteContenido: "https://negociosyeconomia.pucv.cl/ingenieria-comercial",
        contenidos: [
          "Teoría del consumidor: preferencias, función de utilidad, restricción presupuestaria, demanda",
          "Teoría de la firma: tecnología, costos, oferta",
          "Equilibrio parcial competitivo",
          "Bienestar: excedentes del consumidor y productor",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Micro I es ramo cuantitativo (usa cálculo + álgebra). Sin curso base en catálogo. Candidato prioritario a producir: 'Microeconomía Intermedia para Ing. Comercial' — alta demanda PUCV/UC/USACH/UTFSM.",
        nota: "Código ICA no verificado.",
      },
      // ── SEMESTRE 3 ──
      {
        nombre: "Microeconomía II",
        area: "economía",
        semestre: 3,
        prereqs: "Microeconomía I",
        fuenteContenido: "https://negociosyeconomia.pucv.cl/ingenieria-comercial",
        contenidos: [
          "Estructuras de mercado no competitivas: monopolio, oligopolio, competencia monopolística",
          "Teoría de juegos: equilibrio de Nash, juegos repetidos",
          "Externalidades y bienes públicos",
          "Información asimétrica: selección adversa y riesgo moral",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Micro II — extensión natural de Micro I. Sin curso base. Mismo nicho de producción.",
        nota: "Código ICA no verificado.",
      },
      {
        nombre: "Macroeconomía I",
        area: "economía",
        semestre: 3,
        prereqs: "Microeconomía I",
        fuenteContenido: "https://negociosyeconomia.pucv.cl/ingenieria-comercial",
        contenidos: [
          "Identidades de cuentas nacionales: PIB, inflación, desempleo",
          "Modelo IS-LM",
          "Modelo AD-AS",
          "Política fiscal y monetaria",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Macro estándar. Sin curso base. Candidato a curso 'Macroeconomía Intermedia para Ing. Comercial'.",
        nota: "Mencionada explícitamente 'Macroeconomía 1' en PDF malla legacy.",
      },
      {
        nombre: "Estadística (Probabilidad)",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Cálculo I-II",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "Probabilidad: espacios muestrales, axiomas, condicional, independencia, Bayes",
          "Variables aleatorias discretas: binomial, Poisson",
          "Variables aleatorias continuas: uniforme, exponencial, normal",
          "Esperanza, varianza, momentos",
          "Distribuciones conjuntas (introducción)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Estadística/probabilidad. Sin curso base. Candidato prioritario a producir: 'Probabilidad y Estadística para Ingeniería' — cruza Ing. Comercial, Civil Industrial, Civil Informática.",
        nota: "Código ICA no verificado.",
      },
      // ── SEMESTRE 4 ──
      {
        nombre: "Macroeconomía II",
        area: "economía",
        semestre: 4,
        prereqs: "Macroeconomía I",
        fuenteContenido: "https://negociosyeconomia.pucv.cl/ingenieria-comercial",
        contenidos: [
          "Crecimiento económico: Solow, capital humano",
          "Economía abierta: tipo de cambio, balanza de pagos",
          "Expectativas racionales (introducción)",
          "Política económica avanzada",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Macro II — extensión. Sin curso base.",
        nota: "Mencionada explícitamente 'Macroeconomía 2' en PDF malla legacy.",
      },
      {
        nombre: "Inferencia Estadística",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Estadística",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "Estimación puntual y por intervalos",
          "Tests de hipótesis",
          "ANOVA (introducción)",
          "Regresión lineal simple",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Inferencia. Sin curso base. Puede combinarse con curso de probabilidad/estadística en un solo entregable de 2 partes.",
        nota: "Código ICA no verificado.",
      },
      {
        nombre: "Análisis Cuantitativo I (Investigación de Operaciones)",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Álgebra Lineal, Cálculo II",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "Programación lineal: formulación, método gráfico, método simplex",
          "Dualidad y análisis de sensibilidad",
          "Modelos de transporte y asignación",
          "Programación entera (introducción)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Investigación Operativa. Sin curso base. Candidato a curso 'IO para Negocios' — cruza Ing. Comercial e Industrial.",
        nota: "Código ICA no verificado.",
      },
      // ── SEMESTRE 5 ──
      {
        nombre: "Análisis Cuantitativo II",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Análisis Cuantitativo I",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "Programación entera completa",
          "Programación dinámica",
          "Modelos de redes (camino más corto, PERT/CPM)",
          "Simulación introductoria",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Extensión de IO. Sin curso base.",
        nota: "Mencionada literal como 'Cuantitativo 2' en PDF malla legacy.",
      },
      {
        nombre: "Finanzas I",
        area: "economía",
        semestre: 5,
        prereqs: "Contabilidad, Microeconomía, Estadística",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "Valor del dinero en el tiempo",
          "Valuación de bonos",
          "Valuación de acciones (DDM, FCF)",
          "Costo de capital (WACC)",
          "Estructura de capital",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Finanzas corporativas básicas. Sin curso base. Candidato muy fuerte a producir — alto valor de mercado para alumnos de Ing. Comercial/Negocios.",
        nota: "Mencionada literal como 'Finanzas 1' en PDF malla legacy.",
      },
      // ── SEMESTRE 6 ──
      {
        nombre: "Finanzas II",
        area: "economía",
        semestre: 6,
        prereqs: "Finanzas I",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "CAPM y teoría de portafolio (Markowitz)",
          "Derivados: forwards, futuros, opciones (Black-Scholes introductorio)",
          "Gestión de riesgo financiero",
          "Decisiones de inversión bajo incertidumbre",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Finanzas avanzadas. Sin curso base. Combinable con Finanzas I en un mismo entregable de 2 partes.",
        nota: "Mencionada literal como 'Finanzas 2' en PDF malla legacy.",
      },
      {
        nombre: "Econometría",
        area: "economía",
        semestre: 6,
        prereqs: "Inferencia Estadística, Microeconomía",
        fuenteContenido: "https://www.pucv.cl/uuaa/negocioseconomia/malla-curricular",
        contenidos: [
          "Modelo de regresión lineal múltiple, supuestos MCO",
          "Heteroscedasticidad, autocorrelación",
          "Variables instrumentales (introducción)",
          "Series de tiempo introductorias (AR, MA, ARIMA)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Econometría. Sin curso base. Candidato a producir — cruza Ing. Comercial + Lic. Economía si existe.",
        nota: "Mencionada explícitamente 'Econometría' en PDF malla legacy.",
      },
      // ── SEMESTRE 7-8 ──
      {
        nombre: "Evaluación de Proyectos",
        area: "economía",
        semestre: 7,
        prereqs: "Finanzas I-II, Análisis Cuantitativo",
        fuenteContenido: "https://www.pucv.cl/uuaa/site/docs/20181123/20181123195329/documentodocenteusodeopcionesrealesenlaevaluaciondeproy.pdf",
        contenidos: [
          "Flujos de caja proyectados",
          "VAN, TIR, payback",
          "Análisis de sensibilidad y escenarios",
          "Opciones reales",
          "Evaluación social de proyectos (precios sombra)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Ramo final aplicado de finanzas. Sin curso base. Buen candidato a entregable corto + práctico — alta demanda profesional.",
        nota: "Semestre exacto no verificado (7 u 8).",
      },
    ],
  },

  // ═══════════════════════════════════════
  // CARRERA 3 — Licenciatura en Matemáticas (Instituto de Matemáticas IMA)
  // ═══════════════════════════════════════
  {
    id: "licenciatura-matematicas",
    nombre: "Licenciatura en Matemáticas",
    facultad: "Facultad de Ciencias · Instituto de Matemáticas (IMA)",
    duracion: "8 semestres (plan vigente 2022)",
    mallaUrl: "http://ima.ucv.cl/programas/licenciatura/",
    nota: "Plan 2022 vigente. El IMA NO publica códigos MAT en la malla pública (solo nombres). Los códigos abajo donde aparecen están inferidos por equivalencia con Licenciatura en Física (que sí publica códigos verificados en fis.ucv.cl). Audiencia chica vs. ingeniería pero útil para identificar ramos avanzados (Análisis Real, Estructuras Algebraicas, Medida e Integración) que son gaps del catálogo Se Remonta.",
    especialidades: [],
    ramos: [
      // ── BÁSICOS (S1-S4) que mapean a Se Remonta ──
      {
        nombre: "Cálculo I",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Números reales, axiomas y propiedades",
          "Funciones reales de variable real",
          "Límites y continuidad (definición formal ε-δ)",
          "Derivadas y aplicaciones",
          "Integral de Riemann de una variable",
        ],
        match: ["calculo-1var-gen", "calculo-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en una Variable (85 mód) cubre completo. Match ~85% — Lic. Matemáticas pone más énfasis en rigor (ε-δ formal) pero los contenidos son los mismos.",
        nota: "Equivalente probable a MAT1115 de Lic. Física. Código MAT no publicado en malla IMA.",
      },
      {
        nombre: "Álgebra",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Lógica proposicional y cuantificadores",
          "Conjuntos y funciones",
          "Inducción matemática y principio del buen orden",
          "Números complejos: forma binómica, polar, raíces",
          "Polinomios: división, raíces, teorema fundamental del álgebra",
        ],
        match: ["precalculo-cero", "nivelacion-ing"],
        matchLevel: "alto",
        splitDesde: "Precálculo desde Cero + Nivelación Ingeniería cubren lógica, conjuntos, complejos, polinomios. Match ~80%. Lic. Matemáticas suele ir más profundo en inducción y demostración formal.",
        nota: "Equivalente probable a MAT1118.",
      },
      {
        nombre: "Geometría Analítica y Vectorial",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Sistema cartesiano, recta, distancia",
          "Cónicas (circunferencia, parábola, elipse, hipérbola)",
          "Vectores en R² y R³",
          "Productos punto y cruz",
          "Rectas y planos en el espacio",
        ],
        match: ["precalculo-cero"],
        matchLevel: "medio",
        splitDesde: "Precálculo desde Cero cubre geometría analítica plana (cónicas) y vectores básicos. Falta cubrir vectorial 3D con productos punto/cruz formales — eso está parcialmente en el curso pero podría requerir material complementario.",
        nota: "Código MAT no publicado.",
      },
      {
        nombre: "Cálculo II",
        area: "matemáticas",
        semestre: 2,
        prereqs: "Cálculo I",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Técnicas de integración avanzadas",
          "Aplicaciones de la integral (volúmenes, longitud, áreas paramétricas)",
          "Integrales impropias",
          "Sucesiones y series numéricas (criterios de convergencia)",
          "Series de potencias y Taylor",
        ],
        match: ["calculo-int-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Integral (48 mód) cubre integración, aplicaciones, sucesiones, series, Taylor. Match ~90%.",
        nota: "Equivalente probable a MAT1127.",
      },
      {
        nombre: "Álgebra Lineal I",
        area: "matemáticas",
        semestre: 2,
        prereqs: "Álgebra",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Espacios vectoriales abstractos: base, dimensión",
          "Transformaciones lineales y matrices",
          "Determinantes (definición formal)",
          "Sistemas de ecuaciones lineales",
          "Valores y vectores propios",
        ],
        match: ["algebra-lineal-gen"],
        matchLevel: "alto",
        splitDesde: "Álgebra Lineal (52 mód) cubre todo el syllabus. Lic. Matemáticas pone más rigor en demostraciones de espacios vectoriales y transformaciones lineales.",
        nota: "Código no publicado.",
      },
      {
        nombre: "Cálculo en Varias Variables (Cálculo III)",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Cálculo II, Álgebra Lineal I",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Funciones R^n → R^m",
          "Derivadas parciales, gradiente, diferencial",
          "Regla de la cadena",
          "Optimización: multiplicadores de Lagrange",
          "Integrales múltiples (cambio de variable, jacobiano)",
        ],
        match: ["calculo-vvar-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en Varias Variables (41 mód) cubre completo. Match ~90%.",
        nota: "Equivalente probable a MAT1210.",
      },
      {
        nombre: "Ecuaciones Diferenciales",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Cálculo II, Álgebra Lineal I",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "EDO de primer orden",
          "EDO lineales de orden superior",
          "Sistemas de EDO",
          "Transformada de Laplace",
          "Aplicaciones",
        ],
        match: ["ec-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Ecuaciones Diferenciales (42 mód) cubre el syllabus. Match ~90%.",
        nota: "Equivalente probable a MAT1220.",
      },
      {
        nombre: "Cálculo IV (Cálculo Vectorial)",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Cálculo III",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Curvas parametrizadas en R^n",
          "Integrales de línea",
          "Campos vectoriales, rotacional, divergencia",
          "Teoremas de Green, Stokes, divergencia (Gauss)",
          "Superficies parametrizadas",
        ],
        match: ["calculo-vec-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Vectorial (31 mód) cubre completo el syllabus. Match ~95%.",
        nota: "Equivalente probable a MAT1221.",
      },
      // ── AVANZADOS (S2-S8) — gaps de catálogo, registrar para producción ──
      {
        nombre: "Teoría de Números",
        area: "matemáticas",
        semestre: 2,
        prereqs: "Álgebra",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Divisibilidad y algoritmo de Euclides",
          "Congruencias y teorema chino del resto",
          "Función phi de Euler, teorema de Fermat",
          "Teorema fundamental de la aritmética",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Ramo específico de licenciatura. Sin curso base. Audiencia muy chica (sólo Lic. Mat). Bajo valor de producción.",
        nota: "Código no publicado.",
      },
      {
        nombre: "Estructuras Algebraicas I",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Álgebra, Álgebra Lineal I",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Grupos: definición, subgrupos, orden",
          "Homomorfismos y teoremas de isomorfismo",
          "Grupos cíclicos, simétricos, alternantes",
          "Teorema de Lagrange",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Álgebra abstracta — ramo filtro en Lic. Matemáticas. Sin curso base. Audiencia chica pero ramo emblemático para el segmento.",
        nota: "Código no publicado.",
      },
      {
        nombre: "Estructuras Algebraicas II",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Estructuras Algebraicas I",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Anillos: definición, ideales, anillo cociente",
          "Dominios de integridad, cuerpos",
          "Polinomios sobre anillos",
          "Introducción a teoría de Galois",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Continuación de álgebra abstracta. Sin curso base.",
        nota: "Código no publicado.",
      },
      {
        nombre: "Álgebra Lineal II",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Álgebra Lineal I",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Formas canónicas (Jordan)",
          "Espacios con producto interno",
          "Operadores autoadjuntos, unitarios, normales",
          "Teorema espectral",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Álgebra Lineal avanzada — más allá del curso base. Sin curso adicional en catálogo.",
        nota: "Código no publicado.",
      },
      {
        nombre: "Análisis Real",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Cálculo IV, Álgebra Lineal II",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Topología de R^n (abiertos, cerrados, compactos, conexos)",
          "Sucesiones y series en R^n",
          "Continuidad uniforme",
          "Diferenciación rigurosa (definición y teoremas)",
          "Teoremas del valor medio, función inversa, función implícita",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Análisis Real — el ramo filtro emblemático de Lic. Matemáticas. Sin curso base. CANDIDATO PRIORITARIO si se quiere atacar el segmento Lic./Ped. Matemáticas (también cursan Ing. Civil Matemática en UTFSM/USACH).",
        nota: "Código no publicado.",
      },
      {
        nombre: "Métodos Numéricos",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Cálculo IV, Álgebra Lineal II, Programación",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Interpolación polinomial",
          "Métodos iterativos para sistemas lineales",
          "Integración numérica",
          "EDO numéricas (Euler, Runge-Kutta)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Métodos numéricos. Sin curso base. Cruza con Ing. Civil Informática.",
        nota: "Código no publicado.",
      },
      {
        nombre: "Geometría Diferencial",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Cálculo IV",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Curvas en R³: longitud de arco, curvatura, torsión, Frenet",
          "Superficies regulares en R³",
          "Primera y segunda forma fundamental",
          "Curvaturas (gaussiana, media)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Ramo específico Lic. Matemáticas. Sin curso base. Audiencia chica.",
        nota: "Código no publicado.",
      },
      {
        nombre: "Espacios Métricos",
        area: "matemáticas",
        semestre: 6,
        prereqs: "Análisis Real",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Métricas y topología métrica",
          "Completitud, espacios de Banach (introducción)",
          "Compacidad y conexidad",
          "Teorema del punto fijo de Banach",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Equivalente a Topología General introductoria. Sin curso base. Audiencia muy chica.",
        nota: "Código no publicado. En plan 2015-2021 aparecía como 'Topología' explícita.",
      },
      {
        nombre: "Medida e Integración",
        area: "matemáticas",
        semestre: 6,
        prereqs: "Análisis Real, Espacios Métricos",
        fuenteContenido: "http://ima.ucv.cl/programas/licenciatura/",
        contenidos: [
          "Medida de Lebesgue en R^n",
          "Integral de Lebesgue, teoremas de convergencia",
          "Espacios L^p (introducción)",
          "Teoremas de Fubini y Tonelli",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Análisis avanzado. Sin curso base. Audiencia muy chica — sólo Lic. Mat.",
        nota: "Código no publicado.",
      },
    ],
  },

  // ═══════════════════════════════════════
  // CARRERA 4 — Licenciatura en Física (Instituto de Física)
  // ═══════════════════════════════════════
  {
    id: "licenciatura-fisica",
    nombre: "Licenciatura en Física",
    facultad: "Facultad de Ciencias · Instituto de Física (IF)",
    duracion: "8 semestres",
    mallaUrl: "https://fis.ucv.cl/licenciatura-en-fisica/",
    nota: "Plan vigente con códigos MAT/FIS verificados (syllabus oficiales en fis.ucv.cl/wp-content/uploads/2020/11/). Los códigos MAT compartidos PUCV-wide (MAT1115/1118/1127/1129/1210/1220/1221) son los que usan también otras Escuelas de Ingeniería NO-EIC y la Pedagogía en Física. Útil para identificar gap: Mecánica Clásica, Mecánica Cuántica, Electromagnetismo, Física Estadística — todos sin curso base en catálogo actual.",
    especialidades: [],
    ramos: [
      // ── BÁSICOS MAT (S1-S4) ──
      {
        nombre: "MAT1115 Cálculo I",
        codigo: "MAT1115",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://fis.ucv.cl/wp-content/uploads/2020/11/MAT1115-Cálculo-1.pdf",
        contenidos: [
          "Números reales e inecuaciones",
          "Funciones: dominio, recorrido, polinomiales, trigonométricas, exp/log",
          "Límites y continuidad",
          "Derivadas y aplicaciones",
          "Integrales: TFC, técnicas básicas",
        ],
        match: ["calculo-1var-gen", "calculo-dif-gen", "calculo-int-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en una Variable (85 mód) cubre todo. Cálculo Diferencial (52 mód) + Cálculo Integral (48 mód) por separado para split modular. Match ~90%.",
        nota: "Syllabus verificado. Código MAT1115 es PUCV-wide (también lo cursan otras escuelas de ingeniería y Pedagogía en Física).",
      },
      {
        nombre: "MAT1118 Álgebra",
        codigo: "MAT1118",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://fis.ucv.cl/wp-content/uploads/2020/11/MAT1118-Álgebra.pdf",
        contenidos: [
          "Lógica y conjuntos",
          "Inducción y sumatoria",
          "Números complejos",
          "Polinomios y ecuaciones algebraicas",
          "Combinatoria (introducción)",
        ],
        match: ["precalculo-cero", "nivelacion-ing"],
        matchLevel: "alto",
        splitDesde: "Precálculo desde Cero + Nivelación Ingeniería cubren conjuntos, inducción, complejos, polinomios. Match ~85%.",
        nota: "Syllabus verificado en fis.ucv.cl.",
      },
      {
        nombre: "MAT1127 Cálculo II",
        codigo: "MAT1127",
        area: "matemáticas",
        semestre: 2,
        prereqs: "MAT1115",
        fuenteContenido: "https://fis.ucv.cl/wp-content/uploads/2020/11/",
        contenidos: [
          "Técnicas avanzadas de integración",
          "Aplicaciones de la integral (áreas, volúmenes, longitud, polares)",
          "Integrales impropias",
          "Sucesiones y series numéricas",
          "Series de potencias y Taylor",
        ],
        match: ["calculo-int-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Integral (48 mód) cubre técnicas, aplicaciones, sucesiones, series, Taylor. Match ~95%.",
        nota: "Código PUCV-wide.",
      },
      {
        nombre: "MAT1129 Álgebra Lineal y Ecuaciones Diferenciales",
        codigo: "MAT1129",
        area: "matemáticas",
        semestre: 2,
        prereqs: "MAT1118",
        fuenteContenido: "https://fis.ucv.cl/wp-content/uploads/2020/11/",
        contenidos: [
          "Matrices, sistemas, determinantes",
          "Espacios vectoriales, base, dimensión",
          "Transformaciones lineales, valores propios",
          "EDO de primer orden (introducción)",
          "EDO lineales de orden superior (introducción)",
        ],
        match: ["algebra-lineal-gen", "ec-dif-gen"],
        matchLevel: "medio",
        splitDesde: "Álgebra Lineal (52 mód) cubre la parte de álgebra. Ecuaciones Diferenciales (42 mód) cubre la parte de EDO pero es introducción acá — el ramo posterior MAT1220 profundiza. Match combinado ~70% para los dos cursos base.",
        nota: "Código PUCV-wide. Combina álgebra lineal con introducción a EDO en un solo ramo.",
      },
      {
        nombre: "MAT1210 Cálculo III",
        codigo: "MAT1210",
        area: "matemáticas",
        semestre: 3,
        prereqs: "MAT1127, MAT1129",
        fuenteContenido: "https://fis.ucv.cl/wp-content/uploads/2020/11/",
        contenidos: [
          "Cálculo de varias variables",
          "Derivadas parciales, gradiente",
          "Optimización, Lagrange",
          "Integrales múltiples, cambio de variable",
          "Coordenadas curvilíneas",
        ],
        match: ["calculo-vvar-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en Varias Variables (41 mód) cubre completo. Match ~95%.",
        nota: "Código PUCV-wide.",
      },
      {
        nombre: "MAT1220 Ecuaciones Diferenciales",
        codigo: "MAT1220",
        area: "matemáticas",
        semestre: 3,
        prereqs: "MAT1129",
        fuenteContenido: "https://fis.ucv.cl/wp-content/uploads/2020/11/",
        contenidos: [
          "EDO de primer orden (separables, lineales, exactas, Bernoulli)",
          "EDO lineales de orden superior",
          "Sistemas de EDO",
          "Transformada de Laplace",
          "Aplicaciones físicas",
        ],
        match: ["ec-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Ecuaciones Diferenciales (42 mód) cubre completo. Match ~95%.",
        nota: "Código PUCV-wide. En Lic. Física se enfatizan aplicaciones físicas (oscilaciones, RLC, ondas).",
      },
      {
        nombre: "MAT1221 Cálculo IV",
        codigo: "MAT1221",
        area: "matemáticas",
        semestre: 4,
        prereqs: "MAT1210",
        fuenteContenido: "https://fis.ucv.cl/wp-content/uploads/2020/11/",
        contenidos: [
          "Curvas paramétricas",
          "Integrales de línea y superficie",
          "Campos vectoriales, rotacional, divergencia",
          "Teoremas de Green, Stokes, divergencia",
        ],
        match: ["calculo-vec-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Vectorial (31 mód) cubre todo. Match ~95%.",
        nota: "Código PUCV-wide. Crítico para Electromagnetismo posterior.",
      },
      // ── BÁSICOS FIS (S1-S4) ──
      {
        nombre: "FIS1111 Introducción a la Física",
        codigo: "FIS1111",
        area: "física",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Magnitudes, unidades, vectores",
          "Cinemática 1D y 2D",
          "Dinámica básica",
          "Introducción a métodos experimentales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Física básica. Sin curso base. Candidato a curso 'Física Universitaria Básica'.",
        nota: "Equivalente al FIS1035 de Ing. Civil pero con enfoque más teórico.",
      },
      {
        nombre: "FIS1126 Física General Mecánica",
        codigo: "FIS1126",
        area: "física",
        semestre: 2,
        prereqs: "FIS1111, MAT1115",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Leyes de Newton avanzadas",
          "Trabajo, energía, conservación",
          "Momento lineal, colisiones",
          "Rotación, momento angular",
          "Estática y oscilaciones",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica Newtoniana de nivel universitario. Sin curso base. Alta demanda: cruza ingenierías + Lic./Ped. Física. Candidato prioritario.",
        nota: "Acompañado de FIS1123 (laboratorio experimental).",
      },
      {
        nombre: "FIS1231 Física General Termodinámica",
        codigo: "FIS1231",
        area: "física",
        semestre: 3,
        prereqs: "FIS1126",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Temperatura y dilatación",
          "Calor, calor específico, cambios de fase",
          "Primera ley de la termodinámica",
          "Segunda ley, entropía, ciclos térmicos",
          "Teoría cinética de gases",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Termodinámica. Sin curso base. Candidato a producir.",
        nota: "Acompañado de FIS1230 (laboratorio).",
      },
      {
        nombre: "FIS1222 Física General Electromagnetismo",
        codigo: "FIS1222",
        area: "física",
        semestre: 4,
        prereqs: "FIS1231, MAT1221",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Electrostática: ley de Coulomb, campo y potencial eléctrico",
          "Capacitancia, dieléctricos",
          "Corriente eléctrica, circuitos DC",
          "Magnetismo: campo magnético, ley de Ampère",
          "Inducción de Faraday, leyes de Maxwell (introducción)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Electromagnetismo universitario. Sin curso base. Alta demanda — cruza muchas escuelas (Ing. Civil Eléctrica, Electrónica, Telecomunicaciones, Lic./Ped. Física).",
        nota: "Acompañado de FIS1224 (laboratorio). Candidato prioritario.",
      },
      // ── AVANZADOS (S4-S8) — gaps ──
      {
        nombre: "FIS1220 Programación",
        codigo: "FIS1220",
        area: "programación",
        semestre: 4,
        prereqs: "MAT1129",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Algoritmos básicos",
          "Lenguaje de programación (Python o C, según semestre)",
          "Aplicaciones a problemas de física",
          "Visualización y graficación científica",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Programación científica. Sin curso base.",
        nota: "Código PUCV.",
      },
      {
        nombre: "FIS1239 Mecánica",
        codigo: "FIS1239",
        area: "física",
        semestre: 4,
        prereqs: "FIS1126, MAT1220",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Cinemática y dinámica avanzada",
          "Sistemas de partículas",
          "Mecánica del sólido rígido",
          "Introducción al formalismo Lagrangiano (puente a FIS1335)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica intermedia. Sin curso base. Puente entre física general y mecánica clásica avanzada.",
        nota: "Específico Lic. Física.",
      },
      {
        nombre: "FIS1242 Métodos Matemáticos de la Física",
        codigo: "FIS1242",
        area: "matemáticas",
        semestre: 5,
        prereqs: "MAT1221, FIS1239",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Variable compleja: funciones analíticas, residuos",
          "Series de Fourier",
          "Transformada de Fourier",
          "Ecuaciones diferenciales parciales (clasificación, separación de variables)",
          "Funciones especiales (Bessel, Legendre, esféricas armónicas)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Métodos matemáticos para física teórica. Sin curso base. Audiencia chica pero core para Lic./Ped. Física.",
        nota: "Código específico IF-PUCV.",
      },
      {
        nombre: "FIS1335 Mecánica Clásica",
        codigo: "FIS1335",
        area: "física",
        semestre: 5,
        prereqs: "FIS1239, MAT1221",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Formalismo Lagrangiano: principio de mínima acción, ecuaciones de Euler-Lagrange",
          "Simetrías y teorema de Noether",
          "Formalismo Hamiltoniano",
          "Mecánica de cuerpos rígidos avanzada",
          "Pequeñas oscilaciones (modos normales)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica Clásica formal (Lagrangiano/Hamiltoniano). Sin curso base. CANDIDATO si se quiere atacar segmento Lic./Ped. Física. Bibliografía: Goldstein, Landau.",
        nota: "Ramo filtro emblemático de Lic. Física.",
      },
      {
        nombre: "FIS1336 Mecánica Cuántica I",
        codigo: "FIS1336",
        area: "física",
        semestre: 7,
        prereqs: "FIS1335, FIS1242",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Postulados de la mecánica cuántica",
          "Ecuación de Schrödinger (estacionaria y dependiente del tiempo)",
          "Oscilador armónico cuántico",
          "Momento angular cuántico",
          "Átomo de hidrógeno",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica Cuántica I. Sin curso base. Audiencia muy chica (solo Lic. Fís avanzada). Producir solo si se prioriza prestigio académico.",
        nota: "Bibliografía: Griffiths, Sakurai.",
      },
      {
        nombre: "FIS1348 Electrodinámica",
        codigo: "FIS1348",
        area: "física",
        semestre: 7,
        prereqs: "FIS1222, FIS1242",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Ecuaciones de Maxwell completas",
          "Ondas electromagnéticas en el vacío y medios",
          "Radiación de cargas aceleradas",
          "Electrodinámica relativista (introducción)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Electrodinámica nivel Jackson/Griffiths. Sin curso base. Audiencia chica.",
        nota: "Específico Lic. Física avanzada.",
      },
      {
        nombre: "FIS1422 Física Estadística",
        codigo: "FIS1422",
        area: "física",
        semestre: 8,
        prereqs: "FIS1335, FIS1336",
        fuenteContenido: "https://fis.ucv.cl/licenciatura-en-fisica/",
        contenidos: [
          "Conjuntos microcanónico, canónico, gran canónico",
          "Estadísticas de Maxwell-Boltzmann, Bose-Einstein, Fermi-Dirac",
          "Aplicaciones: gas ideal, sólidos, fotones, electrones",
          "Transiciones de fase",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Física Estadística avanzada. Sin curso base. Audiencia muy chica.",
        nota: "Específico Lic. Física.",
      },
    ],
  },

  // ═══════════════════════════════════════
  // CARRERA 5 — Pedagogía en Matemáticas (Instituto de Matemáticas IMA)
  // ═══════════════════════════════════════
  {
    id: "pedagogia-matematicas",
    nombre: "Pedagogía en Matemáticas",
    facultad: "Facultad de Ciencias · Instituto de Matemáticas (IMA)",
    duracion: "10 semestres (incluye práctica docente)",
    mallaUrl: "http://ima.ucv.cl/programas/pedagogia/",
    nota: "Plan 2022 vigente. Comparte ramos básicos con Licenciatura en Matemáticas (Cálculo I-III, Álgebra, Álgebra Lineal, EDO) en S1-S3 — los matches son los mismos. Esta entrada lista SÓLO los ramos disciplinares de matemática que difieren o complementan; excluye didáctica, práctica docente, psicología, filosofía e idiomas (fuera del nicho STEM).",
    especialidades: [],
    ramos: [
      {
        nombre: "Geometría 3D Euclidiana y Plana",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Geometría Analítica y Vectorial, Álgebra Lineal I",
        fuenteContenido: "http://ima.ucv.cl/programas/pedagogia/",
        contenidos: [
          "Geometría sintética clásica",
          "Construcciones con regla y compás",
          "Teoremas clásicos (Pitágoras, Tales, Euclides)",
          "Geometría espacial: poliedros, sólidos platónicos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Geometría clásica con enfoque pedagógico. Sin curso base directo. Parcialmente cubierto por Precálculo desde Cero (geometría analítica básica) pero la geometría sintética escolar formal no está cubierta.",
        nota: "Ramo específico de pedagogía (sirve para enseñar geometría escolar).",
      },
      {
        nombre: "Geometría no Euclidiana",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Geometría 3D Euclidiana y Plana",
        fuenteContenido: "http://ima.ucv.cl/programas/pedagogia/",
        contenidos: [
          "Axiomática de Euclides y el postulado de las paralelas",
          "Geometría hiperbólica",
          "Geometría esférica (introducción)",
          "Modelos de Klein y Poincaré",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Específico pedagogía. Sin curso base. Audiencia muy chica.",
        nota: "Ramo de cultura matemática.",
      },
      {
        nombre: "Análisis Real",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Cálculo III, Álgebra Lineal I",
        fuenteContenido: "http://ima.ucv.cl/programas/pedagogia/",
        contenidos: [
          "Topología de R (abiertos, cerrados, compactos)",
          "Sucesiones y series rigurosas",
          "Continuidad uniforme",
          "Diferenciación e integración rigurosa",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mismo ramo de Lic. Matemáticas. Sin curso base. CANDIDATO si se prioriza segmento Lic./Ped. Mat (combina Lic. Mat + Ped. Mat + Civil Matemática).",
        nota: "Comparte el ramo Análisis Real con Lic. Matemáticas — único curso base produciría serviría a ambas.",
      },
      {
        nombre: "Estadística 1",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Cálculo II",
        fuenteContenido: "http://ima.ucv.cl/programas/pedagogia/",
        contenidos: [
          "Estadística descriptiva",
          "Probabilidad básica",
          "Distribuciones discretas y continuas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Probabilidad/estadística básica. Sin curso base. Mismo candidato que aparece en Ing. Comercial — un curso de Probabilidad y Estadística sirve cruzado.",
        nota: "Código no publicado.",
      },
      {
        nombre: "Estadística 2",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Estadística 1",
        fuenteContenido: "http://ima.ucv.cl/programas/pedagogia/",
        contenidos: [
          "Inferencia estadística",
          "Tests de hipótesis",
          "Regresión lineal",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Inferencia. Sin curso base. Mismo gap que Ing. Comercial.",
        nota: "Código no publicado.",
      },
    ],
  },

  // ═══════════════════════════════════════
  // CARRERA 6 — Pedagogía en Física y Ciencias Naturales (Instituto de Física)
  // ═══════════════════════════════════════
  {
    id: "pedagogia-fisica",
    nombre: "Pedagogía en Física y Ciencias Naturales",
    facultad: "Facultad de Ciencias · Instituto de Física (IF)",
    duracion: "9 semestres (plan vigente; existe variante anterior de 10)",
    mallaUrl: "https://fis.ucv.cl/pedagogia-en-fisica-3/",
    nota: "Acreditación 5 años (Dic 2022 – Dic 2027). Comparte códigos MAT y FIS de primeros 4 semestres con Lic. Física (MAT1115/1118/1127/1129/1210, FIS1111/1126/1231/1222) — los matches y splits son los mismos. Esta entrada lista SÓLO los ramos disciplinares de física que difieren o son únicos de pedagogía; excluye didáctica, práctica docente y formación general.",
    especialidades: [],
    ramos: [
      {
        nombre: "FIS1113 Historia de la Física",
        codigo: "FIS1113",
        area: "física",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://fis.ucv.cl/pedagogia-en-fisica-3/",
        contenidos: [
          "Historia de la mecánica clásica",
          "Revolución del electromagnetismo",
          "Física moderna: relatividad y cuántica (panorama histórico)",
          "Personajes y experimentos clave",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Específico pedagogía (cultura científica). Sin curso base. Audiencia muy chica.",
        nota: "Específico Ped. Física.",
      },
      {
        nombre: "FIS1233 Mecánica Clásica (variante pedagogía)",
        codigo: "FIS1233",
        area: "física",
        semestre: 4,
        prereqs: "FIS1126, MAT1220",
        fuenteContenido: "https://fis.ucv.cl/pedagogia-en-fisica-3/",
        contenidos: [
          "Mecánica avanzada para enseñanza",
          "Formalismo Lagrangiano introductorio",
          "Aplicaciones didácticas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Variante didáctica de Mecánica Clásica. Sin curso base.",
        nota: "Cf. FIS1239 de Lic. Física — variante con menos formalismo y más aplicaciones de enseñanza.",
      },
      {
        nombre: "FIS1319 Física General Fluidos",
        codigo: "FIS1319",
        area: "física",
        semestre: 5,
        prereqs: "FIS1126",
        fuenteContenido: "https://fis.ucv.cl/pedagogia-en-fisica-3/",
        contenidos: [
          "Hidrostática: presión, principio de Pascal y Arquímedes",
          "Hidrodinámica: ecuación de continuidad, Bernoulli",
          "Viscosidad y flujo viscoso (introducción)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica de fluidos básica. Sin curso base. Acompañado de FIS1334 (laboratorio).",
        nota: "Específico pedagogía. No aparece en Lic. Física como ramo separado.",
      },
      {
        nombre: "FIS1339 Física General Ondas y Óptica",
        codigo: "FIS1339",
        area: "física",
        semestre: 6,
        prereqs: "FIS1126, FIS1222",
        fuenteContenido: "https://fis.ucv.cl/pedagogia-en-fisica-3/",
        contenidos: [
          "Ondas mecánicas y armónicas",
          "Acústica",
          "Óptica geométrica: reflexión, refracción, lentes",
          "Óptica física: interferencia y difracción (introductorio)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Ondas + Óptica básica. Sin curso base. Acompañado de FIS1332 (laboratorio).",
        nota: "Cf. FIS1329 de Lic. Física — variante con menos profundidad teórica.",
      },
      {
        nombre: "FIS1443 Ciencias de la Tierra y el Espacio",
        codigo: "FIS1443",
        area: "física",
        semestre: 6,
        prereqs: "FIS1231",
        fuenteContenido: "https://fis.ucv.cl/pedagogia-en-fisica-3/",
        contenidos: [
          "Geología básica para profesores",
          "Atmósfera y clima",
          "Astronomía descriptiva",
          "Tópicos de ciencias naturales para educación media",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Específico pedagogía (formación interdisciplinaria). Sin curso base. Audiencia muy chica.",
        nota: "No tiene equivalente en Lic. Física.",
      },
      {
        nombre: "FIS1424 Física Contemporánea (Física Moderna)",
        codigo: "FIS1424",
        area: "física",
        semestre: 7,
        prereqs: "FIS1222, FIS1233",
        fuenteContenido: "https://fis.ucv.cl/pedagogia-en-fisica-3/",
        contenidos: [
          "Relatividad especial (introductoria)",
          "Cuantización de la energía",
          "Modelo atómico de Bohr",
          "Dualidad onda-partícula",
          "Estructura nuclear básica",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Física moderna introductoria. Sin curso base. Acompañado de FIS1420 (laboratorio). Cf. FIS1346 de Lic. Física — variante con menos profundidad.",
        nota: "Específico pedagogía.",
      },
    ],
  },
];
