// ═══════════════════════════════════════════════════════════════
// DATOS VERIFICADOS - Investigación Ramos UDP (Universidad Diego Portales)
// Fuentes:
//   - Malla Plan Común Ing. Civil 2026 (PDF oficial FIC):
//     · https://ingenieriayciencias.udp.cl/cms/wp-content/uploads/2025/12/INGENIERIA-CIVIL-PLAN-COMUN_2026.pdf
//   - Malla Ing. Civil Industrial 2026 (PDF oficial EII):
//     · https://eii.udp.cl/cms/wp-content/uploads/2026/03/INGENIERIA-CIVIL-INDUSTRIAL_2026-2.pdf
//   - Malla Ing. Civil en Informática y Telecomunicaciones 2026 (PDF oficial EIT):
//     · https://eit.udp.cl/cms/wp-content/uploads/2025/12/INGENIERIA-CIVIL-EN-INFORMATICA-Y-TELECOMUNICACIONES.pdf
//   - Malla Ing. Civil en Ciencia de Datos e IA 2026 (carrera nueva, primera generación):
//     · https://admision.udp.cl/cms/wp-content/uploads/2025/09/INGENIERIA-CIVIL-EN-CIENCIA-DE-DATOS-E-INTELIGENCIA-ARTIFICIAL_2026.pdf
//   - Descriptores oficiales Industrial (malla 4.2/4.3, syllabi vigentes):
//     · https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf
//   - Syllabi 2026 EIT (índice público): https://eit.udp.cl/asignaturas/
//     · 40+ PDFs en https://eit.udp.cl/cms/wp-content/uploads/2026/01/ (CBM1100..CIT3621)
//   - Malla Ing. Comercial UDP (infografía PDF y página interactiva):
//     · https://www.udp.cl/cms/wp-content/uploads/2023/07/INGENIERIA-COMERCIAL-UDP.pdf
//     · https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/
//     · https://admision.udp.cl/carrera/ingenieria-comercial-mencion-economia/
//   - Verificación Bachillerato (existe en Ciencias Sociales y Humanidades, NO STEM):
//     · https://bachillerato.udp.cl/escuela/malla-curricular/  →  no se incluye carrera (no aporta ramos STEM)
// Fecha de investigación: Mayo 2026
// ═══════════════════════════════════════════════════════════════
//
// NOTAS DE CONTEXTO UDP:
// - Privada de Santiago (Campus República + Ciudad Empresarial), perfil socioeconómico medio-alto.
// - Acreditación institucional CNA-Chile nivel EXCELENCIA, vigente Nov 2023 - Nov 2029 (todas las áreas).
// - UDP rediseñó las mallas FIC para Admisión 2026 con nueva codificación (formato CBM1100,
//   sin guión). El descriptor 4.2/4.3 anterior usa formato CBM-1000 (con guión); algunos ramos
//   avanzados de Industrial sólo tienen syllabus público en el PDF antiguo aunque la malla 2026
//   ya migró el código. Se anota la equivalencia en cada ramo afectado.
// - Plan Común FIC = solo 2 semestres (NO 4-5 como en otras Us). Tras S2 el alumno elige carrera
//   específica; semestres 3-4 siguen siendo muy compartidos pero no se llaman "plan común".
// - Ing. Comercial NO publica códigos numéricos por ramo (solo SIES de carrera), por eso
//   el campo 'codigo' queda en "s/n" para esa malla.

import { useState } from "react";

// ─── CATÁLOGO COMPLETO SE REMONTA (cursos generales base) ─────
const seRemontaCursos = [
  { id: "precalculo-cero", nombre: "Precálculo desde Cero", tipo: "general", area: "matemáticas", modulos: 68, precio: 40000, color: "#8B5CF6",
    contenidos: ["Conjuntos y números", "Álgebra de expresiones", "Ecuaciones e inecuaciones", "Funciones", "Trigonometría", "Geometría analítica"] },
  { id: "nivelacion-ing", nombre: "Nivelación Ingeniería", tipo: "general", area: "matemáticas", modulos: 43, precio: 20000, color: "#7C3AED",
    contenidos: ["Repaso números reales", "Funciones elementales", "Trigonometría aplicada", "Vectores y geometría", "Lógica e inducción", "Polinomios"] },
  { id: "algebra-lineal-gen", nombre: "Álgebra Lineal", tipo: "general", area: "matemáticas", modulos: 52, precio: 40000, color: "#6366F1",
    contenidos: ["Espacio", "Sistemas de Ecuaciones", "Álgebra de Matrices", "Determinantes", "Espacios y Subespacios Vectoriales", "Valores y Vectores Propios", "Ortogonalidad", "Matrices Simétricas"] },
  { id: "calculo-1var-gen", nombre: "Cálculo en una Variable", tipo: "general", area: "matemáticas", modulos: 85, precio: 40000, color: "#3B82F6",
    contenidos: ["Límites y continuidad", "Derivadas", "Aplicaciones de la derivada", "Integrales", "Técnicas de integración", "Aplicaciones de la integral"] },
  { id: "calculo-dif-gen", nombre: "Cálculo Diferencial", tipo: "general", area: "matemáticas", modulos: 52, precio: 35000, color: "#0EA5E9",
    contenidos: ["Números reales e inecuaciones", "Funciones (dominio, recorrido, transformaciones, polinomiales, exp, log)", "Límites y continuidad", "Derivadas y reglas de derivación", "Aplicaciones de la derivada (TVM, L'Hôpital, optimización, graficación)"] },
  { id: "calculo-int-gen", nombre: "Cálculo Integral", tipo: "general", area: "matemáticas", modulos: 48, precio: 35000, color: "#06B6D4",
    contenidos: ["Antiderivadas e integral indefinida", "Teorema Fundamental del Cálculo", "Técnicas (sustitución, partes, fracciones parciales, sustitución trigonométrica)", "Aplicaciones (área, volúmenes, longitud de arco, parametrizadas, polares)", "Integrales impropias", "Sucesiones y series (criterios, Taylor, potencias)"] },
  { id: "calculo-vvar-gen", nombre: "Cálculo en Varias Variables", tipo: "general", area: "matemáticas", modulos: 41, precio: 40000, color: "#14B8A6",
    contenidos: ["Funciones de varias variables", "Derivadas parciales y gradiente", "Máximos y mínimos", "Multiplicadores de Lagrange", "Integrales dobles y triples", "Coordenadas curvilíneas"] },
  { id: "calculo-vec-gen", nombre: "Cálculo Vectorial", tipo: "general", area: "matemáticas", modulos: 31, precio: 40000, color: "#10B981",
    contenidos: ["Curvas paramétricas y vectoriales", "Integrales de línea (escalares y vectoriales)", "Teorema de Green", "Rotacional y divergencia", "Integrales de superficie", "Teorema de Stokes", "Teorema de la divergencia"] },
  { id: "ec-dif-gen", nombre: "Ecuaciones Diferenciales", tipo: "general", area: "matemáticas", modulos: 42, precio: 40000, color: "#EAB308",
    contenidos: ["EDO primer orden (separable, lineal, exacta, factor integrante, homogénea, Bernoulli)", "EDO segundo orden (coef constantes, Cauchy-Euler, coef indeterminados, variación parámetros)", "Sistemas de ED", "Transformada de Laplace (propiedades, traslación, escalón, convolución, Dirac)", "Soluciones por series (Bessel, Frobenius)", "Aplicaciones (mecánica, circuitos, modelos)"] },
];

const carreras = [
  // ═══════════════════════════════════════════════════════════════
  // CARRERA 1 — PLAN COMÚN INGENIERÍA CIVIL (S1-S2)
  // Compartido por las 4 especialidades civiles. Tras S2 el alumno elige.
  // ═══════════════════════════════════════════════════════════════
  {
    id: "plan-comun-ing-civil",
    nombre: "Plan Común Ingeniería Civil",
    facultad: "Facultad de Ingeniería y Ciencias (FIC) — Campus República",
    duracion: "2 semestres comunes (1 año) + especialidad (10-11 semestres totales según carrera)",
    mallaUrl: "https://ingenieriayciencias.udp.cl/cms/wp-content/uploads/2025/12/INGENIERIA-CIVIL-PLAN-COMUN_2026.pdf",
    nota: "Acreditación institucional UDP nivel Excelencia CNA Nov 2023 - Nov 2029. Plan Común UDP es corto (solo 2 semestres) — al finalizar 1° año el alumno elige una de 4 especialidades sin límite de cupos. Existe un electivo de especialidad en S2 (Programación Avanzada / Ingeniería en Materiales / Herramientas de Programación Industrial) que orienta la decisión. Códigos 2026: formato CBM1100 (sin guión). Plataforma Python desde S1 (cambió de C++ en malla anterior).",
    especialidades: [
      "Ingeniería Civil Industrial",
      "Ingeniería Civil en Obras Civiles",
      "Ingeniería Civil en Informática y Telecomunicaciones",
      "Ingeniería Civil en Ciencia de Datos e Inteligencia Artificial",
    ],
    ramos: [
      // ── SEMESTRE 1 ──
      {
        nombre: "Introducción al Álgebra",
        codigo: "CBM1100",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos (ramo de admisión)",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/01_CBM1100.pdf",
        contenidos: [
          "Teoría de conjuntos y lógica: pertenencia, contención, operatoria, diagramas de Venn; proposiciones simples y compuestas, conectores lógicos (conjunción, disyunción, negación, condicional, bicondicional), tablas de verdad, equivalencias, cuantificadores universal y existencial; cardinalidad y problemas de conteo",
          "Números complejos y polinomios: forma binomial, gráfica y polar (exponencial); operaciones (suma, producto, conjugado, módulo, división); potencias y teorema de De Moivre; ecuaciones polinomiales: factorización, raíces reales y complejas, multiplicidad",
          "Sumatorias e inducción: sumatorias finitas y propiedades; sumas notables (aritméticas, geométricas, cuadráticas, telescópicas); inducción matemática; teorema del binomio",
          "Trigonometría plana: ángulos y mediciones; círculo unitario y funciones trigonométricas; fórmulas de adición y variantes; ecuaciones trigonométricas; leyes del seno y coseno para resolución de triángulos",
        ],
        match: ["precalculo-cero", "nivelacion-ing"],
        matchLevel: "alto",
        splitDesde: "Precálculo desde Cero (68 mód) cubre conjuntos, complejos básicos, álgebra y trigonometría completa. Nivelación Ingeniería (43 mód) refuerza inducción y polinomios. Falta grabar: De Moivre formal y problemas de conteo combinatorio aplicado. Cobertura combinada ~85%.",
        nota: "Programa oficial verificado (PDF descriptor EIT 2026). Bibliografía: Swokowski Álgebra/Trigonometría/Geometría Analítica (Thomson); Zill & Dewar (McGraw-Hill); Stewart, Redlin, Watson Precálculo (Cengage).",
      },
      {
        nombre: "Introducción al Cálculo",
        codigo: "CBM1101",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos (ramo de admisión)",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/02_CBM1101.pdf",
        contenidos: [
          "Números reales: operaciones algebraicas (factorización, simplificación, racionalización); potencias, raíces, fracciones algebraicas; ecuaciones lineales, cuadráticas, racionales, irracionales, exponenciales; gráfica de y=mx+n y y=ax²+bx+c; orden en R, intervalos, inecuaciones lineales y cuadráticas",
          "Funciones reales de una variable: dominio, codominio, imagen; funciones polinomiales, racionales, irracionales, por tramos, valor absoluto; funciones trigonométricas (definición, identidades básicas, gráficas sinusoidales); funciones exponenciales y logarítmicas; operatoria con funciones (suma, producto, composición)",
          "Límites: concepto intuitivo y definición formal; cálculo de límites, formas indeterminadas, racionalización, factorización; límites notables y cambios de variable; continuidad",
          "Derivadas: definición, interpretación geométrica y física; reglas de derivación; problemas de variación o razón de cambio",
        ],
        match: ["precalculo-cero", "calculo-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Precálculo desde Cero cubre toda la parte de funciones (~50% del ramo). Cálculo Diferencial (52 mód) cubre límites, derivadas y reglas. Falta grabar: introducción rigurosa al concepto de límite (ε-δ light) que UDP enseña al inicio. Cobertura combinada ~80%.",
        nota: "Bibliografía: Stewart Cálculo conceptos y contextos (Cengage); Zill Cálculo de una variable (McGraw-Hill); Stewart-Redlin-Watson Precálculo (Thomson).",
      },
      {
        nombre: "Química",
        codigo: "CBQ1100",
        area: "química",
        semestre: 1,
        prereqs: "Sin prerrequisitos (ramo de admisión)",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/03_CBQ1100.pdf",
        contenidos: [
          "Estructura atómica de la materia: tabla periódica y configuración electrónica, posición de átomos según teoría de grupos y electronegatividad; enlace químico, estructura de Lewis; teoría de repulsión de pares de electrones de valencia (TRPEV); interacciones intermoleculares y propiedades físicas (solubilidad, punto de fusión/ebullición, conductividad)",
          "Reacciones químicas y estequiometría: identificación de componentes de una ecuación química; ley de conservación de masa; concepto de mol, masa molar y número de Avogadro; relaciones estequiométricas; reactivo limitante y en exceso",
          "Gases, equilibrio y disoluciones: comportamiento de gases (Boyle, Charles, Gay-Lussac, Avogadro); ecuación de gas ideal; estequiometría con gases; mezclas y concentración molar; reacciones en equilibrio; principio de Le Chatelier",
          "Química del agua: equilibrios ácido-base, cálculos de pH; precipitación; reacciones de óxido-reducción aplicadas a problemas ambientales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Química en Se Remonta. Es un ramo estándar de Química General universitaria — buen candidato para producir un curso base 'Química General Ingeniería' que cubriría también CBQ100I PUC, QUI001 USACH, etc.",
        nota: "Bibliografía: Chang Fundamentos de Química (McGraw-Hill); Petrucci Química General (Pearson); Brown-LeMay-Bursten Química La Ciencia Central (Pearson).",
      },
      {
        nombre: "Programación",
        codigo: "CIT1100",
        area: "programación",
        semestre: 1,
        prereqs: "Sin prerrequisitos (ramo de admisión)",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/04_CIT1100.pdf",
        contenidos: [
          "Componentes básicas del computador (memoria, disco, sistema de archivos); pseudocódigo y ruteo de variables",
          "Programación básica en Python: tipos de datos (enteros, cadenas), variables, operadores lógicos y aritméticos; estructuras de control (if, else, for, while); listas, tuplas, sets y diccionarios",
          "Manejo de archivos: lectura/escritura de CSV; ejercicios de suma, promedio, búsqueda, máximo, mínimo; visualización básica con gráficos de líneas",
          "Manipulación y transformación de datos: funciones y funciones lambda; filtrado y transformación; agregación y resumen; manejo de datos faltantes y duplicados; gráficos de barras con datos agrupados",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Programación en Se Remonta. UDP cambió de C++ a Python en malla 2026 — buen target para un curso base 'Introducción a Python para Ingeniería' que cubriría también ramos similares en USACH, UAI, UDD.",
        nota: "Cambio importante: anterior malla usaba C++, ahora es Python (Pandas en S1).",
      },
      // ── SEMESTRE 2 ──
      {
        nombre: "Álgebra Lineal",
        codigo: "CBM1102",
        area: "matemáticas",
        semestre: 2,
        prereqs: "CBM1100 Introducción al Álgebra",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/06_CBM1102.pdf",
        contenidos: [
          "Espacios vectoriales y sistemas de ecuaciones lineales: R^n (foco n=2,3); suma, resta y ponderación; combinaciones lineales; subespacios como rectas y planos; sistemas homogéneos y no homogéneos; operaciones elementales por fila; rango; dependencia/independencia lineal; bases",
          "R^n con producto punto: producto escalar, propiedades, norma, distancia, ortogonalidad; proyecciones ortogonales; ortogonalización de Gram-Schmidt; proyección sobre subespacios y distancia",
          "Operatoria con matrices, determinantes y matriz inversa: suma, producto, transposición; determinantes (cálculo y propiedades); regla de Cramer; matriz inversa; cálculo usando operaciones elementales",
          "Transformaciones lineales: definición, propiedades; matriz asociada; kernel e imagen; isomorfismos",
          "Valores y vectores propios: diagonalización de matrices; cónicas y matrices simétricas",
        ],
        match: ["algebra-lineal-gen"],
        matchLevel: "alto",
        splitDesde: "Álgebra Lineal Se Remonta (52 mód) cubre completo: espacios vectoriales, sistemas, matrices, determinantes, transformaciones, valores propios, ortogonalidad, matrices simétricas. Match >90% — split casi directo.",
        nota: "Bibliografía: Poole Álgebra Lineal una introducción moderna (Cengage); Grossman Álgebra Lineal; Nakos & Joyner Álgebra lineal con aplicaciones.",
      },
      {
        nombre: "Cálculo Diferencial e Integral",
        codigo: "CBM1103",
        area: "matemáticas",
        semestre: 2,
        prereqs: "CBM1101 Introducción al Cálculo",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/07_CBM1103.pdf",
        contenidos: [
          "Máximos, mínimos y optimización: propiedades de funciones (crecimiento, decrecimiento, concavidad, puntos de inflexión); análisis gráfico; problemas de optimización con variables, restricciones y objetivo; funciones costos, ingresos y utilidad",
          "Integración: integración indefinida y primitivas; métodos de integración (sustitución simple, por partes, sustitución trigonométrica, fracciones parciales); integral definida y propiedades; área bajo la curva; teorema fundamental del cálculo",
          "Integrales impropias: tipo I y tipo II; criterios de convergencia (prueba de comparación, p-integral)",
          "Series: definición, propiedades; series geométrica y telescópica; criterios de convergencia (razón, raíz); series de potencias (radio de convergencia); series de Taylor (aproximaciones locales); series de Fourier para funciones continuas y periódicas",
        ],
        match: ["calculo-1var-gen", "calculo-int-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en una Variable (85 mód) cubre aplicaciones de la derivada y todas las técnicas de integración. Cálculo Integral (48 mód) refuerza TFC, integrales impropias, sucesiones y series con Taylor. Falta grabar: Series de Fourier (UDP las introduce aquí, no estándar en otras Us).",
        nota: "Bibliografía: Stewart Cálculo conceptos y contextos (Cengage); Zill Cálculo de una variable; Edwards & Penney Cálculo con Geometría Analítica; Larson-Hostetler. UDP es de las pocas Us que mete Fourier en este ramo.",
      },
      {
        nombre: "Mecánica",
        codigo: "CBF1100",
        area: "física",
        semestre: 2,
        prereqs: "CBM1101 Introducción al Cálculo",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/08_CBF1100.pdf",
        contenidos: [
          "Cinemática, Dinámica y Leyes de Newton: magnitudes escalares y vectoriales, álgebra vectorial; cinemática de la partícula; concepto de fuerza y masa; primera, segunda y tercera ley de Newton; diagramas de cuerpo libre; fricción, tensiones, planos inclinados; movimiento rectilíneo y curvilíneo",
          "Conservación de energía y cantidad de movimiento: trabajo y energía cinética; energía potencial gravitatoria y elástica; teorema trabajo-energía; conservación de energía mecánica; impulso, cantidad de movimiento; colisiones elásticas e inelásticas; momento angular y conservación",
          "Estática y rotación de cuerpo rígido: centro de masa, centro de gravedad y torque; condiciones de equilibrio; momento de inercia; segunda ley en rotación, aceleración angular y roto-traslación",
          "Experimentación en mecánica: método científico; instrumentación y técnicas de medición; análisis de errores e incertidumbres; validación de modelos teóricos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Física en Se Remonta. Mecánica es el primer ramo de física en casi todas las ingenierías chilenas — alta prioridad para producir 'Física I (Mecánica)' que serviría a UDP, PUC (FIS1503/FIS1533), USACH, UAI y UTFSM (~5 splits inmediatos).",
        nota: "Bibliografía: Serway & Jewett Física para Ciencias e Ingeniería (Cengage); Young & Freedman Física Universitaria (Pearson).",
      },
      {
        nombre: "Programación Avanzada",
        codigo: "CIT1110",
        area: "programación",
        semestre: 2,
        prereqs: "CIT1100 Programación",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/09_CIT1110.pdf",
        contenidos: [
          "Clases y objetos: tipado, operadores, if/else, comparadores y bucles; definición e instanciación; atributos y métodos (estáticos y dinámicos); encapsulamiento y abstracción",
          "Herencia y polimorfismo: reutilización y extensión de funcionalidades",
          "Resolución de problemas con estructuras: listas, conjuntos, pilas, colas, diccionarios; búsqueda y ordenamiento",
          "Modelado y eficiencia: análisis de eficiencia (tiempo y memoria); algoritmos de búsqueda (secuencial y binaria); recursividad y memorización; ordenamientos (Selection e Insertion)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Programación en Se Remonta. POO en Python es el contenido — segundo curso natural después de uno de 'Intro Python'. Útil para split en EIT, Civil Industrial, Civil Ciencia de Datos UDP simultáneamente.",
        nota: "Es electivo de especialidad en S2 del Plan Común — quienes van a EIT/Industrial/Ciencia de Datos lo toman como obligatorio.",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CARRERA 2 — INGENIERÍA CIVIL INDUSTRIAL (S3-S11, post Plan Común)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "ing-civil-industrial",
    nombre: "Ingeniería Civil Industrial",
    facultad: "Escuela de Ingeniería Industrial (EII) — FIC, Campus República",
    duracion: "11 semestres (5,5 años + actividad de titulación). Comparte S1-S2 con Plan Común.",
    mallaUrl: "https://eii.udp.cl/cms/wp-content/uploads/2026/03/INGENIERIA-CIVIL-INDUSTRIAL_2026-2.pdf",
    nota: "Áreas de profundización vía electivos profesionales en S9-S10: Operaciones y Logística, Análisis de Datos, Energía Sostenible, Liderazgo y Gestión de Equipos. EII en proceso de visita de pares externos para certificación específica de carrera (institucional UDP es Excelencia CNA Nov 2023 - Nov 2029). En esta carrera el descriptor más detallado de syllabi sigue siendo el PDF 4.2/4.3 de 2021 (códigos formato CBM-XXXX/CII-XXXX); la malla 2026 mantiene los nombres pero algunos códigos migraron a formato sin guión.",
    especialidades: ["Operaciones y Logística", "Análisis de Datos", "Energía Sostenible", "Liderazgo y Gestión de Equipos Multidisciplinarios"],
    ramos: [
      // ── SEMESTRE 3 ──
      {
        nombre: "Ecuaciones Diferenciales",
        codigo: "CBM-1005 / CBM1105",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Álgebra Lineal (CBM1102), Cálculo Diferencial e Integral (CBM1103)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "EDOs de primer orden: métodos de solución (separación de variables, factor integrante); aplicaciones (crecimiento exponencial, modelo logístico, mezclas, Ley de Newton de enfriamiento, trayectorias ortogonales)",
          "EDOs lineales de orden n (segundo orden y mayores): homogéneas y no homogéneas; coeficientes constantes; método de variación de parámetros; aplicaciones a oscilaciones mecánicas, circuitos RLC, vibraciones",
          "Transformada de Laplace: propiedades; aplicación a EDOs lineales con condiciones iniciales o de borde; transformada inversa",
          "Sistemas lineales de primer orden y análisis cualitativo de sistemas no lineales",
          "Series de Fourier para funciones periódicas; ecuaciones diferenciales parciales por separación de variables (versión Industrial completa)",
        ],
        match: ["ec-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Ecuaciones Diferenciales (42 mód) cubre EDO 1er/2do orden completo, sistemas, Transformada de Laplace, Bessel/Frobenius. Falta grabar: análisis cualitativo de sistemas no lineales y EDPs por separación de variables (UDP las mete acá, no en ramo aparte). Cobertura ~80%.",
        nota: "Bibliografía: Zill & Cullen Matemáticas Avanzadas para Ingeniería I (McGraw-Hill); Edwards & Penney; Simmons.",
      },
      {
        nombre: "Cálculo III",
        codigo: "CBM-1006 / CBM1106",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Cálculo Diferencial e Integral (CBM1103)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Funciones vectoriales y curvas en el espacio: longitud de arco, curvatura",
          "Funciones reales de varias variables: derivadas parciales, derivadas direccionales; planos tangentes; regla de la cadena",
          "Optimización multivariable: máximos y mínimos locales y absolutos; extremos condicionados; multiplicadores de Lagrange",
          "Integración múltiple: integrales dobles (coordenadas polares); integrales triples (cilíndricas y esféricas); aplicaciones a volúmenes, áreas, centros de gravedad, momentos de inercia",
          "Cálculo vectorial: gradiente, divergencia, rotacional, Laplaciano; integrales de línea; teorema de Green",
        ],
        match: ["calculo-vvar-gen", "calculo-vec-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en Varias Variables (41 mód) cubre derivadas parciales, optimización, multiplicadores de Lagrange, integrales múltiples, coordenadas curvilíneas. Cálculo Vectorial (31 mód) cubre curvas vectoriales, gradiente/divergencia/rotacional, integrales de línea, Green. Match ~85% combinado. Falta grabar: longitud de arco y curvatura para curvas vectoriales (parte inicial UDP).",
        nota: "Bibliografía: Edwards & Penney; Marsden & Tromba Cálculo Vectorial (Addison Wesley); Stewart Cálculo varias variables (Cengage); Zill & Wright (McGraw-Hill).",
      },
      {
        nombre: "Calor y Ondas",
        codigo: "CBF-1001 / CBF1101",
        area: "física",
        semestre: 3,
        prereqs: "Cálculo II (CBM1103), Mecánica (CBF1100)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Calor y leyes de gases: densidad, presión y temperatura; expansión térmica y calorimetría; transferencia de calor; gases ideales y reales",
          "Termodinámica: primera y segunda ley; máquinas térmicas",
          "Ondas: vibraciones y ondas; función de onda y ecuación diferencial; velocidad de propagación en distintos medios",
          "Superposición de ondas; fenómeno de resonancia",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Es 'Física II' estándar (Termodinámica + Ondas) — buen candidato para producir 'Física II' como segundo curso después del de Mecánica.",
        nota: "Bibliografía: Serway & Jewett (Cengage); Çengel & Boles Termodinámica (McGraw-Hill); Young & Freedman.",
      },
      {
        nombre: "Contabilidad y Costos",
        codigo: "CII-1000",
        area: "economía",
        semestre: 3,
        prereqs: "Cálculo I (CBM1101)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Introducción a la contabilidad; ciclo de la contabilidad general; contabilizaciones específicas",
          "Estados financieros finales: balance general, estado de resultados",
          "Contabilidad de costos: estados de costos, sistemas de costos, métodos de costeo",
          "Análisis costo-volumen-utilidad",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Es Contabilidad/Costos para ingeniería — buen target para curso de 'Contabilidad y Costos para Ingenieros' (mismo ramo en PUC IIC2113, USACH, UAI Industrial).",
        nota: "Bibliografía: Meigs & Williams Contabilidad (McGraw-Hill); Torres Contabilidad información y control.",
      },
      // ── SEMESTRE 4 ──
      {
        nombre: "Probabilidades y Estadísticas",
        codigo: "CBE-2000",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Cálculo II (CBM1103)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Estadística descriptiva: medidas de tendencia central, dispersión, posición; visualización de datos",
          "Experimentos aleatorios y espacios de probabilidades; axiomas; probabilidad condicional; teorema de Bayes",
          "Variables aleatorias unidimensionales discretas (Bernoulli, Binomial, Poisson, Hipergeométrica) y continuas (Uniforme, Exponencial, Normal); esperanza, varianza, momentos",
          "Modelos de probabilidad y aplicaciones a ingeniería",
          "Introducción a la inferencia estadística (estimación por intervalos, pruebas de hipótesis)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Estadística/Probabilidades en Se Remonta. ALTA prioridad para producir — es ramo obligatorio en Industrial+Ciencia de Datos+Comercial UDP, y replica en PUC (EYP1113), USACH, UAI, UDD, UTFSM. Splits potenciales: 6+.",
        nota: "Bibliografía: Canavos Probabilidad y Estadística (McGraw-Hill); Montgomery & Runger Probabilidad y Estadística para Ingeniería (Wiley).",
      },
      {
        nombre: "Estática",
        codigo: "CII-2250",
        area: "física",
        semestre: 4,
        prereqs: "Mecánica (CBF1100)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Álgebra vectorial; fuerzas; equilibrio de partícula",
          "Estática de sistemas de partículas y cuerpo rígido; equilibrio de cuerpos rígidos",
          "Reticulados; centro de gravedad, centroides, fuerzas distribuidas",
          "Análisis estructural; esfuerzos internos en vigas",
          "Principios del trabajo virtual",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Es 'Estática' clásica de Hibbeler — útil principalmente para Industrial/Civil Obras. Prioridad media (replica en USACH, UAI Industrial). En la malla 2026 podría haber sido reemplazada por Electromagnetismo y Física Moderna en S4 — verificar.",
        nota: "Bibliografía: Hibbeler Ingeniería Mecánica Estática (Pearson). Verificar si fue reemplazada en malla 2026.",
      },
      {
        nombre: "Electricidad y Magnetismo",
        codigo: "CBF-1002 / CBF1102",
        area: "física",
        semestre: 4,
        prereqs: "Ecuaciones Diferenciales, Cálculo III",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Electrostática: carga eléctrica y fuerza eléctrica; campo eléctrico, potencial eléctrico",
          "Condensadores y dieléctricos",
          "Circuitos eléctricos: ley de Ohm, leyes de Kirchhoff",
          "Campo magnético y corrientes: ley de Ampere, Biot-Savart, ley de Faraday; inductancia",
          "Circuito RLC; ecuaciones de Maxwell y ondas electromagnéticas",
          "(En malla 2026 EIT añade Física Moderna: efecto fotoeléctrico, fotones, láser)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Es 'Física III (Electromagnetismo)' estándar — completar el set Física I/II/III sería estratégico (replica en PUC FIS1523, USACH, UAI).",
        nota: "Bibliografía: Serway & Jewett (Cengage); Young, Freedman, Sears, Zemansky; Tipler Física Tomo II.",
      },
      {
        nombre: "Introducción a la Economía",
        codigo: "CII-2100",
        area: "economía",
        semestre: 4,
        prereqs: "Cálculo II (CBM1103)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Demanda y conducta del consumidor",
          "Oferta y teoría de la firma",
          "Competencia perfecta",
          "Fallas de mercado",
          "Conceptos introductorios de macroeconomía",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Economía. Replica fuerte en Ing. Comercial UDP, PUC EAE, USACH, UAI Industrial — alta prioridad para producir 'Introducción a la Economía / Microeconomía I'.",
        nota: "Bibliografía: Mankiw Principios de Economía (Thomson); Bernanke & Frank (McGraw-Hill).",
      },
      // ── SEMESTRE 5 ──
      {
        nombre: "Inferencia Estadística",
        codigo: "CII-2751",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Probabilidades y Estadística (CBE-2000)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Introducción a la inferencia: estimadores puntuales, sesgo, eficiencia, consistencia",
          "Intervalos de confianza para media, proporción, varianza, diferencia de medias",
          "Pruebas de hipótesis: nula, alternativa, errores tipo I y II, p-valor; pruebas paramétricas comunes",
          "Modelos de regresión lineal simple y múltiple; mínimos cuadrados",
          "Pruebas de bondad de ajuste (chi-cuadrado, Kolmogorov-Smirnov)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Estadística. Es continuación natural de Probabilidades — el mismo curso base 'Estadística e Inferencia' podría cubrir ambos (CBE-2000 + CII-2751) y otros equivalentes en otras Us.",
        nota: "Bibliografía: Canavos; Devore Probabilidad y Estadística para Ingeniería; Montgomery & Runger; Walpole-Myers-Ye.",
      },
      {
        nombre: "Mecánica de Fluidos",
        codigo: "CII-2401",
        area: "física",
        semestre: 5,
        prereqs: "Estática (CII-2250), Electricidad y Magnetismo (CBF-1002)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Definición de fluido; hipótesis del continuo; sistema y volumen de control",
          "Teorema de transporte de Reynolds; conservación de masa, momentum y energía",
          "Ley de viscosidad de Newton; ecuación de Bernoulli; hidrostática",
          "Pérdidas de carga y dimensionamiento de sistemas de tuberías",
          "Primera ley de la termodinámica aplicada a fluidos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Mecánica de Fluidos es un ramo muy específico — baja prioridad de producción a menos que se quiera abrir línea Civil/Mecánica.",
        nota: "Bibliografía: Çengel & Cimbala Mecánica de Fluidos (McGraw-Hill); White; Wiggert.",
      },
      {
        nombre: "Optimización",
        codigo: "CII-2750",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Álgebra Lineal (CBM1102), Cálculo III (CBM1106)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Nociones fundamentales de optimización; modelos matemáticos; restricciones; investigación de operaciones",
          "Modelos de optimización: soluciones óptimas, modelos equivalentes, teorema de relajación; resolución gráfica con curvas de nivel",
          "Convexidad: conjuntos y funciones convexas",
          "Programación no lineal: modelamiento, teorema de Lagrange, multiplicadores; teorema de Karush-Kuhn-Tucker (KKT); óptimos locales y globales",
          "Programación lineal: formato estándar, soluciones básicas, puntos extremos; teorema fundamental; método simplex (tabla y formato matricial); simplex revisado; teoría de dualidad",
          "Análisis de sensibilidad",
          "Modelos especiales: asignación, programación lineal entera, flujos en redes",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Optimización/Investigación Operativa. ALTA prioridad — es ramo obligatorio en Industrial+EIT+Comercial UDP, y replica en PUC ICS1113, USACH, UAI Industrial, UTFSM. Splits potenciales: 6+.",
        nota: "Bibliografía: Ortiz, Varas, Vera Optimización y Modelos para la Gestión (Dolmen); Hillier & Lieberman (McGraw-Hill); Taha Investigación de Operaciones (Prentice Hall).",
      },
      // ── SEMESTRE 6 ──
      {
        nombre: "Termodinámica",
        codigo: "CII-2402",
        area: "física",
        semestre: 6,
        prereqs: "Calor y Ondas (CBF-1001), Mecánica de Fluidos (CII-2401)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Propiedades de sustancias puras",
          "Primera ley de la termodinámica en sistemas cerrados y abiertos",
          "Segunda ley; concepto de entropía y exergía",
          "Ciclos de potencia y refrigeración",
          "Eficiencia energética",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Termodinámica avanzada — mismo razonamiento que Mec. Fluidos: nicho específico, baja prioridad.",
        nota: "Bibliografía: Çengel & Boles Termodinámica (McGraw-Hill); Moran-Shapiro Fundamentals of engineering thermodynamics (Wiley).",
      },
      {
        nombre: "Modelos Estocásticos",
        codigo: "CII-2755",
        area: "matemáticas",
        semestre: 6,
        prereqs: "Probabilidades y Estadísticas (CBE-2000), Optimización (CII-2750)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Repaso teoría de probabilidades",
          "Proceso de Poisson",
          "Cadenas de Markov en tiempo discreto",
          "Cadenas de Markov en tiempo continuo",
          "Sistemas de espera (teoría de colas)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Procesos Estocásticos / Cadenas de Markov / Colas — ramo de tercer año en Industrial chileno. Replica en PUC ICS2123, USACH. Prioridad media.",
        nota: "Bibliografía: Ross Introduction to probability models (Academic Press); Gazmuri Modelos Estocásticos para la Gestión de Sistemas (UC).",
      },
      {
        nombre: "Microeconomía",
        codigo: "CII-2101",
        area: "economía",
        semestre: 6,
        prereqs: "Introducción a la Economía (CII-2100), Optimización (CII-2750)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Teoría del consumidor formal: preferencias, utilidad, demanda compensada y marshalliana",
          "Teoría del productor: tecnología, costos, maximización de beneficios",
          "Equilibrio en competencia perfecta",
          "Intervenciones: impuestos y subsidios",
          "Fallas de mercado; externalidades",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Microeconomía. Replica en Ing. Comercial UDP (Microeconomía II), PUC EAE2010, USACH, UAI. Alta prioridad para producir 'Microeconomía Intermedia' con cálculo y Lagrange.",
        nota: "Bibliografía: Nicholson Teoría Microeconómica (Cengage); Pindyck & Rubinfeld Microeconomía (Prentice Hall); Varian Microeconomía Intermedia (Antoni Bosch).",
      },
      {
        nombre: "Ingeniería Económica",
        codigo: "CII-2002",
        area: "economía",
        semestre: 6,
        prereqs: "Contabilidad y Costos (CII-1000)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Matemáticas financieras; valor del dinero en el tiempo",
          "Criterios de evaluación de proyectos (VAN, TIR, PRI, B/C)",
          "Inflación y estimación de costos",
          "Depreciación, agotamiento, impuestos y flujo de caja",
          "Sensibilidad, incertidumbre y aversión al riesgo",
          "Análisis financiero y proyecciones",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Es 'Ingeniería Económica / Evaluación de Proyectos' — buen candidato para Industrial+Comercial cross-sell.",
        nota: "Bibliografía: Tarquin & Blank Ingeniería Económica (McGraw-Hill); Fontaine Evaluación Social de Proyectos (UC); Newnan Análisis Económico en Ingeniería.",
      },
      // ── SEMESTRE 7 ──
      {
        nombre: "Econometría",
        codigo: "CII-2756",
        area: "economía",
        semestre: 7,
        prereqs: "Inferencia Estadística (CII-2751), Microeconomía (CII-2101)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Repaso de estadística y álgebra lineal",
          "Modelo de regresión simple y múltiple",
          "Estimación por mínimos cuadrados ordinarios (MCO)",
          "Violaciones de supuestos clásicos: multicolinealidad, heterocedasticidad, autocorrelación",
          "Aplicación con software estadístico (Stata/R/EViews)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Econometría. Replica en Ing. Comercial UDP, PUC EAE3050, USACH, UAI Comercial. Alta prioridad para curso 'Econometría I'.",
        nota: "Bibliografía: Gujarati Econometría (McGraw-Hill); Pindyck & Rubinfeld Econometría modelos y pronósticos; Greene Análisis Econométrico (Prentice Hall).",
      },
      {
        nombre: "Producción",
        codigo: "CII-2253",
        area: "otra",
        semestre: 7,
        prereqs: "Optimización (CII-2750)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Definición de gestión de operaciones; productividad; calidad",
          "Diseño de red; planificación de producción",
          "Pronóstico de la demanda",
          "Modelos de inventarios (EOQ, modelos probabilísticos)",
          "Distribución de instalaciones",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Gestión de Operaciones es ramo específico de Industrial — baja prioridad de producción individual; podría incluirse como módulo dentro de un curso Optimización aplicada.",
        nota: "Bibliografía: Chase, Jacobs & Aquilano Administración de la producción y Operaciones (McGraw-Hill); Schroeder Gestión de Operaciones.",
      },
      {
        nombre: "Finanzas",
        codigo: "CII-2003",
        area: "economía",
        semestre: 7,
        prereqs: "Ingeniería Económica (CII-2002)",
        fuenteContenido: "Sin syllabus público completo en descriptor — contenidos inferidos del estándar chileno UDP",
        contenidos: [
          "Estados financieros y razones financieras",
          "Estructura de capital y costo de capital (WACC)",
          "Modelo de valoración de activos (CAPM)",
          "Decisiones de financiamiento e inversión corporativa",
          "Mercados de capitales: bonos, acciones, derivados básicos",
          "Valoración de empresas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Finanzas. Replica en Ing. Comercial Finanzas I/II UDP, PUC EAE3520, UAI. Alta prioridad para 'Finanzas Corporativas' como curso base económico.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y de la bibliografía citada en Evaluación de Proyectos. Bibliografía estándar: Brealey, Myers & Allen; Jaffe-Ross-Westerfield Finanzas Corporativas.",
      },
      // ── SEMESTRE 8 ──
      {
        nombre: "Data Science",
        codigo: "CII-2504",
        area: "programación",
        semestre: 8,
        prereqs: "Inferencia Estadística (CII-2751), Optimización (CII-2750)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Introducción a R; repaso inferencia estadística",
          "Regresión: lineales múltiples, selección de modelos, validación cruzada",
          "Clasificación: paradigma entrenamiento/validación; regresiones logísticas; K-vecinos más cercanos; árboles de decisión y Random Forest; Support Vector Machines",
          "Aprendizaje no supervisado: clustering (k-means, jerárquico); componentes principales (PCA)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Data Science / ML aplicado en R — replica en EIT, Civil Ciencia de Datos, Comercial UDP. Mucha demanda. Alta prioridad para 'Introducción a Machine Learning con R/Python'.",
        nota: "Bibliografía: Wickham & Grolemund R for Data Science; James-Witten-Hastie-Tibshirani An Introduction to Statistical Learning.",
      },
      {
        nombre: "Simulación",
        codigo: "CII-2757",
        area: "matemáticas",
        semestre: 8,
        prereqs: "Modelos Estocásticos (CII-2755)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Sistemas y simulación; cuándo usar simulación",
          "Generación de números aleatorios",
          "Generación de variables aleatorias",
          "Modelamiento de datos de entrada",
          "Construcción y validación de modelos; análisis de resultados",
          "Simulación de eventos discretos (software Arena)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Ramo de nicho que sigue a Estocásticos — baja prioridad como curso base independiente.",
        nota: "Bibliografía: Banks-Carson-Nelson-Nicol Discrete-event System Simulation (Prentice Hall); Kelton-Sadowski-Shurrock Simulación con software Arena (McGraw-Hill).",
      },
      {
        nombre: "Logística",
        codigo: "CII-2254",
        area: "otra",
        semestre: 8,
        prereqs: "Producción (CII-2253)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Introducción a logística y cadena de suministro",
          "Programación matemática aplicada a logística",
          "Flujo en redes, distribución y transporte",
          "Administración de inventarios",
          "Localización de instalaciones",
          "Heurísticas y métodos aproximados",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Aplicación específica de Optimización a SCM — baja prioridad individual.",
        nota: "Bibliografía: Simchi-Levi Designing and Managing the Supply Chain (McGraw-Hill); Chase & Aquilano.",
      },
      {
        nombre: "Evaluación de Proyectos",
        codigo: "CII-2004",
        area: "economía",
        semestre: 8,
        prereqs: "Finanzas (CII-2003)",
        fuenteContenido: "https://eii.udp.cl/cms/wp-content/uploads/2021/08/DESCRIPTORES-DE-PROGRAMAS-DE-ASIGNATURAS.pdf",
        contenidos: [
          "Mercado de capitales, consumo e inversión",
          "Construcción de flujo de caja del proyecto",
          "Modelo de valoración de activos CAPM",
          "Estructura de capital y costo de capital",
          "Valoración de empresas",
          "Modelos de pronóstico de demanda",
          "Evaluación con incertidumbre; teoría de opciones reales",
          "Análisis de riesgos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Continuación natural de Finanzas + Ingeniería Económica — buen candidato para curso conjunto 'Evaluación de Proyectos'.",
        nota: "Bibliografía: Jaffe-Ross-Westerfield Finanzas Corporativas (McGraw-Hill); Copeland & Weston Financial Theory and Corporate Policy (Addison-Wesley).",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CARRERA 3 — INGENIERÍA CIVIL EN INFORMÁTICA Y TELECOMUNICACIONES (EIT)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "ing-civil-informatica-telecomunicaciones",
    nombre: "Ingeniería Civil en Informática y Telecomunicaciones",
    facultad: "Escuela de Informática y Telecomunicaciones (EIT) — FIC, Campus República",
    duracion: "11 semestres (5,5 años + actividad de titulación). Pasantía Laboral I entre S4-S5 y II entre S8-S9 (200 hrs c/u). Comparte S1-S2 con Plan Común.",
    mallaUrl: "https://eit.udp.cl/cms/wp-content/uploads/2025/12/INGENIERIA-CIVIL-EN-INFORMATICA-Y-TELECOMUNICACIONES.pdf",
    nota: "Acreditación de carrera por Qualitas, 7 años (Ene 2017 - Ene 2024) — actualmente en proceso de re-acreditación. Acreditación institucional UDP Excelencia CNA Nov 2023 - Nov 2029. EIT publicó 40+ syllabi 2026 en sitio público (eit.udp.cl/asignaturas/) — fuente más rica entre carreras UDP. Líneas de profundización en electivos: Informática, Telecomunicaciones.",
    especialidades: ["Informática (electivos)", "Telecomunicaciones (electivos)"],
    ramos: [
      // ── SEMESTRE 3 ──
      {
        nombre: "Ecuaciones Diferenciales",
        codigo: "CBM1105",
        area: "matemáticas",
        semestre: 3,
        prereqs: "CBM1102 Álgebra Lineal, CBM1103 Cálculo Diferencial e Integral",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/10_CBM1105.pdf",
        contenidos: [
          "EDOs de primer orden: definición, clasificación (lineales y no lineales), orden y grado; métodos de resolución (separación de variables, factor integrante, integración directa); ecuaciones lineales de primer orden",
          "Modelado: modelo de Malthus, ley de enfriamiento de Newton, problema de mezclas, modelo logístico, trayectorias ortogonales",
          "EDOs lineales de segundo orden: homogéneas con coeficientes constantes; método de variación de parámetros para no homogéneas; aplicaciones a oscilaciones mecánicas, circuitos RLC, vibraciones en estructuras",
          "Transformada de Laplace: propiedades; aplicación a EDOs lineales con condiciones iniciales o de borde; transformada inversa",
        ],
        match: ["ec-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Ecuaciones Diferenciales (42 mód) cubre completo el syllabus EIT (versión más liviana que la de Industrial — sin sistemas no lineales ni Series de Fourier). Match >90%.",
        nota: "Versión EIT más acotada que la de Industrial. Bibliografía estándar: Zill, Edwards & Penney.",
      },
      {
        nombre: "Cálculo en Varias Variables",
        codigo: "CBM1106",
        area: "matemáticas",
        semestre: 3,
        prereqs: "CBM1103 Cálculo Diferencial e Integral",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/11_CBM1106.pdf",
        contenidos: [
          "Funciones reales de varias variables: dominio, recorrido, curvas y superficies de nivel; superficies cuadráticas; límites y continuidad; derivadas parciales y de orden superior; planos tangentes; regla de la cadena; diferenciación implícita",
          "Optimización multivariable: máximos, mínimos y puntos de silla; multiplicadores de Lagrange; aplicaciones (maximización de eficiencia, minimización de costos)",
          "Integración múltiple: integrales dobles y triples; integración iterada y cambio de orden; cambios de coordenadas a polares, cilíndricas y esféricas; cálculo de áreas y volúmenes",
          "Operadores diferenciales: gradiente, divergencia, rotacional, Laplaciano; integrales de línea y de superficie; teorema de Gauss y teorema de Stokes; aplicaciones a campos eléctricos/magnéticos y flujos",
        ],
        match: ["calculo-vvar-gen", "calculo-vec-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en Varias Variables (41 mód) cubre derivadas parciales, optimización, Lagrange, integrales múltiples, coordenadas curvilíneas. Cálculo Vectorial (31 mód) cubre gradiente/divergencia/rotacional, integrales de línea y superficie, Stokes, Gauss. Match combinado ~90%.",
        nota: "Mismo nombre/contenido que CBM1106 Industrial pero distinto syllabus EIT (más enfático en aplicaciones a EM).",
      },
      {
        nombre: "Calor y Ondas",
        codigo: "CBF1101",
        area: "física",
        semestre: 3,
        prereqs: "CBM1103 Cálculo Diferencial e Integral, CBF1100 Mecánica",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/12_CBF1101.pdf",
        contenidos: [
          "Calor y leyes de gases; transferencia de calor; calorimetría",
          "Termodinámica: primera y segunda ley; máquinas térmicas",
          "Ondas: vibraciones, función de onda y ecuación diferencial; velocidad de propagación",
          "Superposición y resonancia",
          "Componente experimental con laboratorios",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mismo razonamiento que CBF-1001 Industrial — Física II / Termodinámica + Ondas. Sin curso base en Se Remonta.",
        nota: "Bibliografía estándar: Serway, Young & Freedman.",
      },
      {
        nombre: "Estructuras de Datos y Algoritmos",
        codigo: "CIT2306",
        area: "programación",
        semestre: 3,
        prereqs: "CIT1110 Programación Avanzada",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/13_CIT2306.pdf",
        contenidos: [
          "Análisis y diseño de algoritmos; complejidad computacional",
          "Notación asintótica (O grande, Omega, Theta) para comparar algoritmos",
          "Estudios empíricos: tiempo de ejecución, uso de memoria, escalabilidad",
          "Estructuras de datos avanzadas: árboles, grafos, tablas hash",
          "Algoritmos de ordenamiento avanzados (merge sort, quicksort, heapsort)",
          "Algoritmos en grafos (BFS, DFS, caminos mínimos)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Es 'Estructuras de Datos' clásico — replica en PUC IIC2133, USACH, UAI Informática. Prioridad media-alta para línea CS.",
        nota: "Sin syllabus completo público — contenidos inferidos del estándar (Cormen Introduction to Algorithms).",
      },
      {
        nombre: "Redes de Datos",
        codigo: "CIT2414",
        area: "otra",
        semestre: 3,
        prereqs: "CIT1110 Programación Avanzada",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/14_CIT2414.pdf",
        contenidos: [
          "Modelo OSI y TCP/IP",
          "Capa física y de enlace de datos",
          "Redes LAN: diseño e implementación",
          "Configuración de equipos de networking; protocolos de enrutamiento",
          "Direccionamiento IPv4/IPv6, subnetting",
          "Servicios de red (DNS, DHCP, HTTP)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Networking — fuera del foco STEM cuantitativo de Se Remonta.",
        nota: "Sin syllabus público completo — contenidos inferidos del estándar (Tanenbaum, Kurose & Ross).",
      },
      // ── SEMESTRE 4 ──
      {
        nombre: "Probabilidades y Estadísticas",
        codigo: "CIT2504",
        area: "matemáticas",
        semestre: 4,
        prereqs: "CBM1103 Cálculo Diferencial e Integral",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/15_CIT2504.pdf",
        contenidos: [
          "Estadística descriptiva: población y muestra; variables cualitativas/cuantitativas; distribuciones de frecuencias; estadígrafos de tendencia central (media, mediana, moda) y de dispersión (rango, desviación estándar, coeficiente de variación)",
          "Probabilidades: experimentos aleatorios, espacios muestrales, eventos; probabilidad como frecuencia relativa; métodos de conteo; axiomas; probabilidad condicional e independencia; teorema de probabilidad total; teorema de Bayes",
          "Variables aleatorias unidimensionales: discretas (Bernoulli, Binomial, Hipergeométrica, Poisson) y continuas (Uniforme, Exponencial, Normal); función de densidad/cuantía; función de distribución acumulada; esperanza y varianza",
          "Variables aleatorias bidimensionales: función conjunta y marginales (discretas y continuas); covarianza, correlación",
          "Inferencia estadística básica: estimación, intervalos de confianza, pruebas de hipótesis",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Equivalente al CBE-2000 de Industrial — sin curso base de Estadística en Se Remonta. Mismo target de producción que CBE-2000.",
        nota: "Bibliografía estándar: Canavos, Devore, Montgomery & Runger.",
      },
      {
        nombre: "Electrónica y Electrotecnia",
        codigo: "CIT2407",
        area: "física",
        semestre: 4,
        prereqs: "CBM1105 Ecuaciones Diferenciales, CBF1101 Calor y Ondas",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/16_CIT2407.pdf",
        contenidos: [
          "Sistemas eléctricos; análisis de circuitos resistivos",
          "Leyes de Ohm y Kirchhoff",
          "Análisis nodal y de mallas",
          "Circuitos RLC; régimen transitorio y permanente",
          "Componentes electrónicos: diodos, transistores",
          "Amplificadores operacionales básicos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Circuitos eléctricos — ramo específico de carreras eléctricas/EIT. Baja prioridad.",
        nota: "Sin syllabus público completo — contenidos inferidos del estándar (Sadiku Fundamentos de Circuitos Eléctricos).",
      },
      {
        nombre: "Electromagnetismo y Física Moderna",
        codigo: "CBF1102",
        area: "física",
        semestre: 4,
        prereqs: "CBM1105 Ecuaciones Diferenciales, CBM1106 Cálculo en varias variables",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/17_CBF1102.pdf",
        contenidos: [
          "Electrostática: campo y potencial eléctrico",
          "Capacitores y dieléctricos; circuitos",
          "Magnetismo: ley de Ampere, Biot-Savart, ley de Faraday",
          "Inductancia, circuito RLC; ecuaciones de Maxwell; ondas electromagnéticas",
          "Física moderna: efecto fotoeléctrico, fotones, relatividad básica, mecánica cuántica introductoria, láser",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Versión EIT de Electricidad y Magnetismo + Física Moderna combinados. Mismo razonamiento que CBF-1002 Industrial.",
        nota: "Bibliografía estándar: Serway, Tipler, Young & Freedman.",
      },
      {
        nombre: "Bases de Datos",
        codigo: "CIT2307",
        area: "programación",
        semestre: 4,
        prereqs: "CIT2306 Estructuras de Datos y Algoritmos",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/18_CIT2307.pdf",
        contenidos: [
          "Modelamiento de datos: modelo entidad-relación (MER); conversión a modelo relacional",
          "Diseño de bases de datos relacionales; normalización (1FN, 2FN, 3FN, BCNF)",
          "Lenguaje SQL: consultas, joins, agregaciones, subconsultas",
          "Administración de BD: índices, transacciones, integridad referencial",
          "Optimización de consultas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Bases de datos relacionales — fuera del foco STEM cuantitativo Se Remonta.",
        nota: "Bibliografía: Ullman & Widom A First Course in Database Systems; Silberschatz, Korth & Sudarshan Database Systems Concepts. Contenidos parcialmente inferidos del descriptor antiguo CII-2501.",
      },
      {
        nombre: "Desarrollo Web y Móvil",
        codigo: "CIT2308",
        area: "programación",
        semestre: 4,
        prereqs: "CIT1110 Programación Avanzada",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/19_CIT2308.pdf",
        contenidos: [
          "Configuración de entornos de desarrollo",
          "Despliegue en servidores reales",
          "Construcción de interfaces inclusivas y accesibles",
          "Frameworks de desarrollo web (frontend y backend)",
          "Desarrollo móvil multiplataforma",
          "Trabajo basado en proyectos con organizaciones externas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Desarrollo web/móvil — fuera del foco Se Remonta.",
        nota: "Sin bibliografía obligatoria especificada en syllabus 2026.",
      },
      // ── SEMESTRE 5 ──
      {
        nombre: "Optimización",
        codigo: "CIT1410",
        area: "matemáticas",
        semestre: 5,
        prereqs: "CBM1102 Álgebra Lineal, CBM1106 Cálculo en Varias Variables",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/21_CIT1410.pdf",
        contenidos: [
          "Nociones fundamentales de optimización: investigación de operaciones, toma de decisiones",
          "Modelos de optimización: soluciones óptimas, valor óptimo, modelos equivalentes, teorema de relajación, resolución gráfica con curvas de nivel",
          "Convexidad: conjuntos y funciones convexas",
          "Programación no lineal: teorema de Lagrange, multiplicadores; teorema de Karush-Kuhn-Tucker (KKT); óptimos locales y globales",
          "Programación lineal: formato estándar, soluciones básicas, puntos extremos; método simplex (tabla y matricial); simplex revisado; teorema de dualidad",
          "Análisis de sensibilidad",
          "Modelos especiales: asignación, programación lineal entera, flujos en redes",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mismo contenido que CII-2750 Industrial pero énfasis en aplicaciones a IA. Sin curso base — alta prioridad de producción (ver CII-2750).",
        nota: "Bibliografía: Hillier & Lieberman; Taha; Ortiz, Varas, Vera (estándar UDP). Versión EIT con énfasis en aplicaciones a IA, mientras Industrial enfatiza gestión.",
      },
      {
        nombre: "Big Data",
        codigo: "CIT2309",
        area: "programación",
        semestre: 5,
        prereqs: "CIT2307 Bases de Datos",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/24_CIT2309.pdf",
        contenidos: [
          "Optimización de gestión y recuperación de grandes volúmenes de datos",
          "Almacenamiento distribuido (Hadoop, HDFS)",
          "Procesamiento paralelo (MapReduce, Spark)",
          "Bases de datos NoSQL (clave-valor, documentos, columnar, grafos)",
          "Estrategias de caching en memoria",
          "Comparación entre data warehouses y data lakes",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Big Data / sistemas distribuidos — fuera del foco Se Remonta.",
        nota: "Bibliografía estándar: White Hadoop The Definitive Guide.",
      },
      // ── SEMESTRE 6 ──
      {
        nombre: "Arquitectura y Organización de Computadores",
        codigo: "CIT2409",
        area: "programación",
        semestre: 6,
        prereqs: "CIT2407 Electrónica y Electrotecnia",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/26_CIT2409.pdf",
        contenidos: [
          "Arquitectura interna de un computador",
          "Diseño y funcionalidades de hardware",
          "Lógica digital, álgebra de Boole",
          "Procesadores, set de instrucciones (ISA)",
          "Memoria: jerarquía, caché, virtual",
          "Buses, sistemas de E/S",
          "Pipelining y paralelismo a nivel de instrucción",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Arquitectura de computadores — fuera del foco Se Remonta.",
        nota: "Sin syllabus público completo — contenidos inferidos del estándar (Patterson & Hennessy Computer Organization and Design).",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CARRERA 4 — INGENIERÍA CIVIL EN CIENCIA DE DATOS E INTELIGENCIA ARTIFICIAL
  // Carrera nueva, primera generación admisión 2026
  // ═══════════════════════════════════════════════════════════════
  {
    id: "ing-civil-ciencia-datos-ia",
    nombre: "Ingeniería Civil en Ciencia de Datos e Inteligencia Artificial",
    facultad: "Escuela de Informática y Telecomunicaciones (EIT) — FIC, Campus República",
    duracion: "11 semestres (5,5 años + actividad de titulación). Primera generación admisión 2026.",
    mallaUrl: "https://admision.udp.cl/cms/wp-content/uploads/2025/09/INGENIERIA-CIVIL-EN-CIENCIA-DE-DATOS-E-INTELIGENCIA-ARTIFICIAL_2026.pdf",
    nota: "Carrera NUEVA abierta para Admisión 2026 (primera generación). 262 postulaciones, puntaje promedio admisión 763,27. UDP NO dicta 'Ingeniería en Estadística' ni 'Ciencia de Datos' como carrera independiente — esta es la única opción pregrado del área (también existe un Diplomado en Ciencia de Datos posgrado). Comparte S1-S2 con Plan Común FIC. Stack didáctico: Python desde S1.",
    especialidades: ["Machine Learning", "Big Data y Data Engineering", "Visualización Avanzada", "Gobernanza de Datos"],
    ramos: [
      // ── SEMESTRE 1 (compartido con Plan Común — solo se listan ramos diferentes o nuevos) ──
      {
        nombre: "Introducción a la Ingeniería",
        codigo: "FIC1100",
        area: "otra",
        semestre: 1,
        prereqs: "Sin prerrequisitos (ramo de admisión)",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-civil-en-ciencia-de-datos-e-inteligencia-artificial/",
        contenidos: [
          "Proyecto integrador inicial de ciencia de datos",
          "Metodologías de trabajo en ingeniería",
          "Desarrollo de habilidades transversales (trabajo en equipo, comunicación)",
          "Introducción a herramientas de ingeniería",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Ramo introductorio sin contenido cuantitativo profundo — fuera del foco Se Remonta.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar de ramos 'Introducción a la Ingeniería' chilenos. Resto de S1-S2 (Intro Álgebra, Intro Cálculo, Química, Programación, Álgebra Lineal, Cálculo Dif e Integral, Mecánica, Programación Avanzada) se hereda del Plan Común FIC — ver carrera 'plan-comun-ing-civil' arriba.",
      },
      // ── SEMESTRE 3 (post Plan Común) ──
      {
        nombre: "Cálculo en Varias Variables",
        codigo: "CBM1106",
        area: "matemáticas",
        semestre: 3,
        prereqs: "CBM1103 Cálculo Diferencial e Integral",
        fuenteContenido: "https://eit.udp.cl/cms/wp-content/uploads/2026/01/11_CBM1106.pdf",
        contenidos: [
          "Funciones reales de varias variables: dominio, recorrido, curvas y superficies de nivel; derivadas parciales; planos tangentes; regla de la cadena",
          "Optimización multivariable: máximos, mínimos, puntos de silla; multiplicadores de Lagrange",
          "Integración múltiple: integrales dobles y triples; cambios de coordenadas (polares, cilíndricas, esféricas)",
          "Operadores diferenciales: gradiente, divergencia, rotacional; integrales de línea y de superficie; teorema de Gauss y Stokes",
        ],
        match: ["calculo-vvar-gen", "calculo-vec-gen"],
        matchLevel: "alto",
        splitDesde: "Mismo CBM1106 que EIT — Cálculo Varias Variables (41 mód) + Cálculo Vectorial (31 mód) cubre ~90%.",
        nota: "Compartido con malla EIT — mismo syllabus.",
      },
      {
        nombre: "Estadística / Teoría Estadística",
        codigo: "s/n",
        area: "matemáticas",
        semestre: 3,
        prereqs: "CBM1103 Cálculo Diferencial e Integral",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-civil-en-ciencia-de-datos-e-inteligencia-artificial/",
        contenidos: [
          "Teoría estadística básica para análisis de datos",
          "Modelos probabilísticos aplicados a problemas de ingeniería",
          "Variables aleatorias y distribuciones",
          "Estadística descriptiva e inferencial introductoria",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Equivalente al CIT2504 EIT / CBE-2000 Industrial — alta prioridad de producción.",
        nota: "Sin syllabus público verificado para esta carrera (recién abierta). Contenidos inferidos del estándar y del CIT2504 EIT que es muy probable sea el mismo ramo.",
      },
      // ── RAMOS DEL CICLO PROFESIONAL S4-S11 ──
      {
        nombre: "Machine Learning (estimado S4-S6)",
        codigo: "s/n",
        area: "programación",
        semestre: 5,
        prereqs: "Estadística, Programación Avanzada, Cálculo en Varias Variables",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-civil-en-ciencia-de-datos-e-inteligencia-artificial/",
        contenidos: [
          "Aprendizaje supervisado: regresión lineal, regresión logística, árboles, random forest, SVM, redes neuronales introductorias",
          "Aprendizaje no supervisado: clustering (k-means, jerárquico, DBSCAN), PCA, reducción de dimensionalidad",
          "Validación cruzada, hiperparámetros, regularización (L1, L2)",
          "Evaluación de modelos: matriz de confusión, ROC-AUC, métricas de regresión",
          "Implementación práctica en Python (scikit-learn)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. ML aplicado — replica con CII-2504 Industrial. Alta prioridad para curso base 'Machine Learning con Python' que serviría a Industrial+EIT+Ciencia de Datos UDP, PUC ICS, USACH, UAI.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar. Semestre estimado — la malla 2026 PDF no se pudo descargar en investigación. Otros ramos del ciclo profesional (Big Data, Visualización Avanzada, Gobernanza de Datos, Infraestructura, Integración de Sistemas vía APIs, Gestión de Proyectos) están mencionados en la descripción oficial pero sin asignación semestral confirmada.",
      },
      {
        nombre: "Big Data e Infraestructura (estimado S5-S7)",
        codigo: "s/n",
        area: "programación",
        semestre: 6,
        prereqs: "Bases de Datos, Programación Avanzada",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-civil-en-ciencia-de-datos-e-inteligencia-artificial/",
        contenidos: [
          "Arquitecturas de Big Data (Hadoop, Spark)",
          "Bases de datos NoSQL y data warehouses",
          "Pipelines de ingesta y transformación de datos (ETL/ELT)",
          "Cloud computing aplicado a data engineering (AWS, GCP, Azure)",
          "Integración de sistemas vía APIs",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Data engineering — fuera del foco STEM cuantitativo Se Remonta.",
        nota: "Sin syllabus público verificado para esta carrera nueva, contenidos inferidos del estándar y de CIT2309 EIT. Semestre estimado.",
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CARRERA 5 — INGENIERÍA COMERCIAL (Facultad de Administración y Economía / FAE)
  // Modelo 4+1: 4 años Licenciatura + 1 año Magíster de especialidad
  // ═══════════════════════════════════════════════════════════════
  {
    id: "ing-comercial",
    nombre: "Ingeniería Comercial",
    facultad: "Facultad de Administración y Economía (FAE) — Campus Ciudad Empresarial (Huechuraba) + Campus República",
    duracion: "10 semestres (5 años) en modelo 4+1: 4 años de Licenciatura + 1 año de Magíster de Especialidad. Egresa con título de Ingeniero/a Comercial + Magíster.",
    mallaUrl: "https://www.udp.cl/cms/wp-content/uploads/2023/07/INGENIERIA-COMERCIAL-UDP.pdf",
    nota: "Acreditación institucional UDP nivel Excelencia CNA Nov 2023 - Nov 2029. Código DEMRE 38003, SIES I3S1C2J1V1. Ponderaciones PAES: NEM 10% / Ranking 35% / Lectora 10% / Matemática 1 35% / Historia o Ciencias 10% (peso fuerte en mate). Empleabilidad 78% al 1er año, 87,4% al 2do año. Arancel 2026: $7.750.000. La malla NO publica códigos numéricos por ramo (solo SIES de carrera) — campo codigo queda en 's/n'. Stack didáctico: R desde S1, Python desde S6. La página economiayempresa.udp.cl/ingenieria-comercial/malla-curricular/ aparece en buscadores pero devuelve 404 — usar admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/ como fuente vigente. La especialización es en S5: Mención Administración / Economía / Emprendimiento; el Magíster en S9-S10 es en Negocios Digitales / Personas y Organizaciones / Marketing / Finanzas.",
    especialidades: ["Mención Administración", "Mención Economía", "Mención Emprendimiento", "Magíster Negocios Digitales", "Magíster Personas y Organizaciones", "Magíster Marketing", "Magíster Finanzas"],
    ramos: [
      // ── SEMESTRE 1 ──
      {
        nombre: "Matemática I",
        codigo: "s/n",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos (ramo de entrada)",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Progresiones aritméticas y geométricas; sumatorias",
          "Funciones reales: dominio, recorrido, composición; funciones lineales, cuadráticas, exponenciales, logarítmicas (énfasis aplicado a economía)",
          "Concepto de límite y continuidad de funciones de una variable",
          "Derivada: definición, reglas de derivación, regla de la cadena, derivadas implícitas",
          "Aplicaciones de la derivada: optimización (máximos y mínimos), análisis marginal, elasticidad",
          "Argumentación matemática y modelación de problemas económicos/administrativos",
        ],
        match: ["precalculo-cero", "calculo-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Equivalente a Cálculo I light + Precálculo aplicado a economía. Precálculo desde Cero (68 mód) cubre funciones, exp/log, álgebra. Cálculo Diferencial (52 mód) cubre límites, derivadas, aplicaciones de la derivada. Falta grabar: enfoque económico explícito (análisis marginal, elasticidad). Cobertura combinada ~80%.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar chileno + descripción oficial UDP. Bibliografía típica: Hoffmann-Bradley Cálculo Aplicado a Administración y Economía; Haeussler-Paul Matemáticas para Administración y Economía.",
      },
      {
        nombre: "Programación",
        codigo: "s/n",
        area: "programación",
        semestre: 1,
        prereqs: "Sin prerrequisitos (ramo de entrada)",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Programación básica e intermedia en R",
          "Análisis de datos en Microsoft Excel (nivel intermedio: fórmulas, tablas dinámicas, lógica condicional)",
          "Estructuras de control, vectores, data frames, importación de datos",
          "Reproducibilidad: documentación de código y comunicación escrita de procedimientos y resultados",
          "Proyecto de análisis de datos en equipo",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. NO es CS clásica — es R + Excel orientado a negocios. Buen target para curso base 'R para Negocios' diferenciado del Python de Ingeniería.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y de la descripción oficial UDP. Stack: R + Excel. Bibliografía típica: Wickham R for Data Science.",
      },
      // ── SEMESTRE 2 ──
      {
        nombre: "Contabilidad I",
        codigo: "s/n",
        area: "economía",
        semestre: 2,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Marco conceptual de la información financiera (IFRS)",
          "Ecuación contable, plan de cuentas, registro de transacciones (libro diario, mayor)",
          "Estados financieros básicos: Estado de Situación Financiera, Estado de Resultados, Flujo de Efectivo",
          "Ajustes y cierre del ejercicio; análisis de partidas (activos, pasivos, patrimonio)",
          "Interpretación de la información contable para decisiones económicas y financieras",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Contabilidad. Replica con CII-1000 Industrial UDP, PUC EAA1110, USACH. Alta prioridad para 'Contabilidad Financiera I'.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Horngren-Harrison Contabilidad Financiera; Meigs.",
      },
      {
        nombre: "Matemáticas II",
        codigo: "s/n",
        area: "matemáticas",
        semestre: 2,
        prereqs: "Matemática I",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Series numéricas: convergencia, criterios",
          "Derivadas avanzadas (orden superior, Taylor) y aplicaciones a optimización univariada",
          "Integral indefinida y definida: técnicas (sustitución, por partes, fracciones parciales)",
          "Aplicaciones de la integral: cálculo de áreas, excedente del consumidor/productor, valor presente de flujos continuos",
          "Modelación matemática de problemas de economía y administración con funciones de una variable",
        ],
        match: ["calculo-1var-gen", "calculo-int-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en una Variable (85 mód) cubre series, integrales, técnicas. Cálculo Integral (48 mód) refuerza aplicaciones e integrales impropias. Falta grabar: aplicaciones específicas a economía (excedentes, valor presente continuo). Cobertura ~80%.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Hoffmann-Bradley; Sydsæter-Hammond Matemáticas para el Análisis Económico.",
      },
      {
        nombre: "Microeconomía I",
        codigo: "s/n",
        area: "economía",
        semestre: 2,
        prereqs: "Sin prerrequisitos (paralelo con Matemática I/II)",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Pensamiento económico, costo de oportunidad, frontera de posibilidades de producción",
          "Demanda y oferta; equilibrio de mercado; elasticidades",
          "Teoría del consumidor: utilidad, restricción presupuestaria, elección óptima",
          "Teoría de la firma: producción, costos, maximización de beneficios",
          "Estructuras de mercado: competencia perfecta (introducción)",
          "Toma de decisiones lógico-cuantitativa; movimiento de variables clave en mercados",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Economía/Microeconomía. Replica masiva (CII-2100/2101 UDP, PUC EAE, USACH, UAI) — alta prioridad para 'Microeconomía I'.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Mankiw Principios de Economía; Pindyck-Rubinfeld.",
      },
      // ── SEMESTRE 3 ──
      {
        nombre: "Estadística I",
        codigo: "s/n",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Matemáticas II (implícito)",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Estadística descriptiva: medidas de tendencia central, dispersión, posición",
          "Visualización de datos y exploración inicial",
          "Probabilidad básica: espacios muestrales, eventos, axiomas, condicional, Bayes",
          "Variables aleatorias discretas y continuas; distribuciones (binomial, Poisson, normal)",
          "Modelos simples de relación entre variables (correlación, regresión introductoria)",
          "Implementación práctica en R",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Estadística — alta prioridad ya consignada en CBE-2000 Industrial.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Newbold Estadística para Administración y Economía.",
      },
      {
        nombre: "Macroeconomía I",
        codigo: "s/n",
        area: "economía",
        semestre: 3,
        prereqs: "Microeconomía I",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Variables macroeconómicas agregadas: PIB, inflación, desempleo, balanza de pagos",
          "Modelo de demanda y oferta agregada",
          "Mercado de bienes y mercado de dinero (introducción IS-LM)",
          "Política fiscal y monetaria a nivel introductorio",
          "Ciclos económicos; razonamiento analítico aplicado a problemas agregados",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Macroeconomía. Replica en PUC EAE, USACH, UAI Comercial. Producción complementaria a Microeconomía.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Mankiw Macroeconomía; Blanchard.",
      },
      {
        nombre: "Matemáticas III",
        codigo: "s/n",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Matemáticas II",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Aplicaciones avanzadas de la integral (continúa S2): integrales impropias, valor presente continuo",
          "Álgebra lineal: matrices, operaciones, determinantes, inversa, sistemas de ecuaciones lineales (Gauss/Gauss-Jordan)",
          "Espacios vectoriales: combinaciones lineales, independencia, base, dimensión",
          "Transformaciones lineales; valores y vectores propios (introducción)",
          "Series (continuación) y aplicaciones a series geométricas en finanzas",
          "Modelación matricial de problemas económicos",
        ],
        match: ["algebra-lineal-gen", "calculo-int-gen"],
        matchLevel: "alto",
        splitDesde: "Álgebra Lineal (52 mód) cubre matrices, sistemas, espacios, transformaciones, valores propios — el grueso del ramo. Cálculo Integral (48 mód) cubre series e impropias. Falta grabar: enfoque matricial de problemas económicos. Cobertura ~85%.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Es el ramo 'Álgebra Lineal' funcional dentro de la carrera. Bibliografía típica: Grossman; Sydsæter-Hammond.",
      },
      {
        nombre: "Tecnología y Empresas",
        codigo: "s/n",
        area: "programación",
        semestre: 3,
        prereqs: "Programación",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Impacto de las TI en la creación de valor organizacional",
          "Sistemas de información empresariales (ERP, CRM, BI — nivel introductorio)",
          "Mapeo de problemas de negocio a soluciones tecnológicas",
          "Procesos digitales y datos en la empresa",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Tecnología/Sistemas de Información para negocios — fuera del foco STEM cuantitativo Se Remonta.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Marginalmente cuantitativo.",
      },
      // ── SEMESTRE 4 ──
      {
        nombre: "Contabilidad II",
        codigo: "s/n",
        area: "economía",
        semestre: 4,
        prereqs: "Contabilidad I",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Contabilidad de costos: clasificación (fijos/variables, directos/indirectos), costeo por órdenes y por procesos",
          "Costeo absorbente vs. costeo variable; punto de equilibrio",
          "Presupuestos operativos y financieros",
          "Análisis de variaciones; toma de decisiones gerenciales basadas en costos",
          "Información para gestión interna (vs. financiera externa)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Contabilidad de Costos — replica con CII-1000 (parte costos) Industrial, PUC EAA. Producción complementaria a Contabilidad I.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Horngren Contabilidad de Costos.",
      },
      {
        nombre: "Estadística II",
        codigo: "s/n",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Estadística I",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Inferencia estadística: estimación puntual y por intervalos",
          "Pruebas de hipótesis: una y dos muestras, paramétricas",
          "Distribuciones muestrales (t, chi-cuadrado, F)",
          "Análisis de varianza (ANOVA introductorio)",
          "Regresión lineal simple y múltiple (introducción)",
          "Aplicación con R sobre muestras concretas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Continuación de Estadística I — mismo target que CII-2751 Industrial.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Newbold; Wackerly.",
      },
      {
        nombre: "Microeconomía II",
        codigo: "s/n",
        area: "economía",
        semestre: 4,
        prereqs: "Microeconomía I + Matemáticas II",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Teoría del consumidor formal: preferencias, utilidad, demanda compensada y marshalliana, ecuación de Slutsky",
          "Teoría de la producción y costos con cálculo y optimización (Lagrange)",
          "Estructuras de mercado: monopolio, oligopolio, competencia monopolística",
          "Decisiones bajo escasez con herramientas formales de optimización",
          "Aplicaciones: trabajadores, hogares, emprendedores",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Microeconomía intermedia con cálculo y Lagrange — fuertemente cuantitativa. Mismo target que CII-2101 Industrial.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Varian Microeconomía Intermedia; Nicholson.",
      },
      // ── SEMESTRE 5 ──
      {
        nombre: "Econometría I",
        codigo: "s/n",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Estadística II",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Modelo de regresión lineal simple y múltiple (MCO)",
          "Supuestos clásicos: linealidad, exogeneidad, homocedasticidad, no autocorrelación, normalidad",
          "Inferencia: tests t y F, intervalos de confianza para coeficientes",
          "Diagnóstico y violaciones de supuestos (multicolinealidad, heterocedasticidad básica)",
          "Predicción y bondad de ajuste (R², R² ajustado)",
          "Implementación completa en R",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base de Econometría. Mismo target que CII-2756 Industrial — alta prioridad de producción.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Wooldridge Introducción a la Econometría; Stock-Watson.",
      },
      {
        nombre: "Finanzas I",
        codigo: "s/n",
        area: "economía",
        semestre: 5,
        prereqs: "Matemáticas III + Contabilidad I",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Valor del dinero en el tiempo; valor presente y futuro; anualidades, perpetuidades",
          "Valoración de bonos y acciones (modelos de descuento de dividendos)",
          "Riesgo y retorno; portafolios; frontera eficiente",
          "CAPM (Capital Asset Pricing Model); diversificación",
          "Decisiones de inversión: VAN, TIR, payback",
          "Implementación práctica en R",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Finanzas Corporativas I — mismo target que CII-2003 Industrial.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Brealey-Myers-Allen Principios de Finanzas Corporativas; Bodie-Kane-Marcus.",
      },
      {
        nombre: "Macroeconomía II",
        codigo: "s/n",
        area: "economía",
        semestre: 5,
        prereqs: "Macroeconomía I",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Profundización del modelo IS-LM y modelo de Mundell-Fleming (economía abierta)",
          "Política monetaria del Banco Central (regla de Taylor introductoria)",
          "Política fiscal y déficit público",
          "Inflación: causas, costos, expectativas",
          "Desempleo: tipos, curva de Phillips",
          "Coyuntura macroeconómica chilena",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Macroeconomía intermedia — buen complemento del par Micro/Macro para producir.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Blanchard; De Gregorio Macroeconomía.",
      },
      // ── SEMESTRE 6 ──
      {
        nombre: "Ciencia de Datos",
        codigo: "s/n",
        area: "programación",
        semestre: 6,
        prereqs: "Estadística II + Programación + Econometría I",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Programación en Python (pandas, numpy, matplotlib)",
          "Adquisición y limpieza de datos (web scraping introductorio, APIs, CSV)",
          "Transformación, agregación y feature engineering",
          "Visualización de datos y dashboards con Shiny",
          "Métricas de negocio; modelado predictivo introductorio",
          "Comunicación de resultados para problemas de negocio",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Ciencia de Datos aplicada a negocios — replica con CII-2504 Industrial. Alta prioridad.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: McKinney Python for Data Analysis.",
      },
      {
        nombre: "Gestión de Operaciones",
        codigo: "s/n",
        area: "matemáticas",
        semestre: 6,
        prereqs: "Matemáticas III + Estadística II",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Modelación matemática de problemas de decisión operacional",
          "Programación lineal: formulación, método símplex, interpretación dual",
          "Modelos determinísticos vs. estocásticos",
          "Gestión de inventarios (EOQ, modelos probabilísticos)",
          "Teoría de colas (introducción)",
          "Pronósticos de demanda; planeamiento agregado",
          "Optimización con software",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Equivalente civil a Investigación Operativa / Optimización — replica con CII-2750 Industrial. Alta prioridad.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Hillier-Lieberman; Anderson-Sweeney.",
      },
      {
        nombre: "Marketing",
        codigo: "s/n",
        area: "economía",
        semestre: 6,
        prereqs: "Sin prerrequisitos explícitos",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Conceptos y metodologías base de marketing",
          "Segmentación, targeting, posicionamiento (STP)",
          "Marketing mix (4P): producto, precio, plaza, promoción",
          "Comportamiento del consumidor; investigación de mercados (introducción)",
          "Aplicación a contextos organizacionales reales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Marketing es ramo cualitativo — fuera del foco STEM cuantitativo Se Remonta.",
        nota: "Sin syllabus público verificado, contenidos inferidos del estándar y descripción UDP. Bibliografía típica: Kotler-Keller.",
      },
      // ── SEMESTRES 7-8 — RAMOS ESPECÍFICOS DE MENCIÓN ECONOMÍA ──
      {
        nombre: "Econometría II",
        codigo: "s/n",
        area: "matemáticas",
        semestre: 7,
        prereqs: "Econometría I (Mención Economía)",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-economia/",
        contenidos: [
          "Modelos para variables dependientes limitadas (logit, probit)",
          "Datos de panel (efectos fijos, efectos aleatorios)",
          "Series de tiempo (introducción a AR, MA, ARMA, estacionariedad)",
          "Variables instrumentales y problemas de endogeneidad",
          "Diferencias-en-diferencias y métodos cuasi-experimentales (introducción)",
          "Implementación avanzada en R",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Econometría avanzada — mismo target que Econometría I.",
        nota: "Específico de Mención Economía. Sin syllabus público verificado, contenidos inferidos del estándar. Bibliografía típica: Wooldridge Cross Section and Panel Data; Stock-Watson.",
      },
      {
        nombre: "Matemáticas para Economía",
        codigo: "s/n",
        area: "matemáticas",
        semestre: 7,
        prereqs: "Matemáticas III + Microeconomía II (Mención Economía)",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-economia/",
        contenidos: [
          "Cálculo en varias variables: derivadas parciales, gradiente, regla de la cadena multivariable",
          "Optimización multivariable sin restricciones (Hessiano, condiciones de 2do orden)",
          "Optimización con restricciones: multiplicadores de Lagrange (igualdad), Karush-Kuhn-Tucker (desigualdad)",
          "Funciones cóncavas/convexas; teorema de la envolvente",
          "Estática comparativa; aplicaciones a teoría del consumidor y del productor",
          "Programación dinámica introductoria (opcional)",
        ],
        match: ["calculo-vvar-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo en Varias Variables (41 mód) cubre derivadas parciales, gradiente, optimización multivariable, Lagrange. Falta grabar: KKT formal, teorema de la envolvente, estática comparativa económica. Cobertura ~75%.",
        nota: "Específico de Mención Economía. Es el ramo más cuantitativo de la mención. Sin syllabus público verificado, contenidos inferidos del estándar. Bibliografía típica: Sydsæter-Hammond Matemáticas para el Análisis Económico; Simon-Blume Mathematics for Economists.",
      },
      {
        nombre: "Teoría de Juegos",
        codigo: "s/n",
        area: "economía",
        semestre: 7,
        prereqs: "Microeconomía II + Matemáticas III (Mención Economía)",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-economia/",
        contenidos: [
          "Juegos en forma normal: estrategias dominantes, equilibrio de Nash",
          "Juegos en forma extensiva; inducción hacia atrás; equilibrio perfecto en subjuegos",
          "Información incompleta: equilibrio bayesiano",
          "Juegos repetidos; estrategias gatillo",
          "Aplicaciones: oligopolio (Cournot, Bertrand, Stackelberg), subastas, negociación",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Teoría de Juegos — ramo de nicho avanzado, baja prioridad de producción.",
        nota: "Específico de Mención Economía. Sin syllabus público verificado, contenidos inferidos del estándar. Bibliografía típica: Gibbons Game Theory for Applied Economists; Osborne.",
      },
      {
        nombre: "Finanzas II",
        codigo: "s/n",
        area: "economía",
        semestre: 7,
        prereqs: "Finanzas I (Mención Administración)",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Finanzas corporativas: estructura de capital (Modigliani-Miller)",
          "Política de dividendos",
          "Decisiones de financiamiento: deuda vs. patrimonio; WACC",
          "Gobernanza corporativa",
          "Valoración de empresas (DCF, múltiplos)",
          "Implementación computacional en R",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Finanzas avanzadas — mismo target que Finanzas I + Evaluación de Proyectos.",
        nota: "Específico de Mención Administración. Sin syllabus público verificado, contenidos inferidos del estándar. Bibliografía típica: Brealey-Myers-Allen; Damodaran Valuation.",
      },
      {
        nombre: "Ciencia de Datos para los Negocios",
        codigo: "s/n",
        area: "programación",
        semestre: 8,
        prereqs: "Ciencia de Datos (Mención Administración)",
        fuenteContenido: "https://admision.udp.cl/carrera/ingenieria-comercial-mencion-administracion/",
        contenidos: [
          "Modelos predictivos para problemas de negocio (clasificación, regresión)",
          "Machine learning en Python (scikit-learn)",
          "Customer analytics; churn; segmentación",
          "Ética y comunicación de modelos a stakeholders no técnicos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sin curso base. Continuación de Ciencia de Datos — mismo target que CII-2504 Industrial / Machine Learning Civil Ciencia de Datos.",
        nota: "Específico de Mención Administración. Sin syllabus público verificado, contenidos inferidos del estándar.",
      },
    ],
  },
];
