// ═══════════════════════════════════════════════════════════════
// DATOS VERIFICADOS - Investigación Ramos UNAB (Universidad Andrés Bello)
// Fuentes:
//   - Malla Ingeniería Civil (PDF oficial UNAB):
//       https://www.unab.cl/carreras/mallas/ing_civil.pdf
//   - Malla Ingeniería Civil Industrial (PDF oficial UNAB):
//       https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf
//   - Malla Ingeniería Civil Informática (PDF oficial UNAB):
//       https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf
//   - Malla Ingeniería Comercial (PDF oficial UNAB):
//       https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf
//   - Sitio Admisión UNAB (descripciones generales):
//       https://admision.unab.cl/carreras/ingenieria-civil-industrial/
//       https://admision.unab.cl/carreras/ingenieria-civil-informatica/
//       https://admision.unab.cl/carreras/ingenieria-comercial/
//   - Itinerarios formativos Advance UNAB:
//       https://unabonline.cl/itinerarios-formativos-programas-advance/
// Fecha de investigación: ABRIL 2026
//
// Notas generales:
//   - UNAB tiene "100% movilidad en el primer año" entre Ing. Civil Industrial,
//     Ing. Civil Informática, Ing. Civil Eléctrica e Ingeniería en Computación
//     e Informática: comparten la malla del primer año (no es un Plan Común
//     formal, pero funciona como tal para los splits).
//   - Ing. Civil "puro" (orientado a obras civiles, hidráulica, estructuras)
//     tiene una malla distinta de 11 semestres con énfasis en construcción.
//   - Cursos sin syllabus público detallado: contenidos inferidos de la
//     reseña oficial de la asignatura en el PDF de la malla y del estándar
//     chileno de ingeniería/negocios.
//   - Se omiten ramos puramente de idiomas (Inglés I-IV, Business English) y
//     humanidades transversales (Habilidades Comunicativas, Pensamiento
//     Crítico, Responsabilidad Social) por estar fuera del nicho STEM+negocios.
// ═══════════════════════════════════════════════════════════════

import { useState } from "react";

const seRemontaCursos = [
  // ─── MATEMÁTICAS (catálogo activo) ───
  {
    id: "precalculo-cero",
    nombre: "Precálculo desde Cero",
    tipo: "general",
    area: "matemáticas",
    modulos: 68,
    precio: 40000,
    color: "#8B5CF6",
    contenidos: [
      "Conjuntos y números",
      "Álgebra de expresiones",
      "Ecuaciones e inecuaciones",
      "Funciones",
      "Trigonometría",
      "Geometría analítica",
    ],
  },
  {
    id: "nivelacion-ing",
    nombre: "Nivelación Ingeniería",
    tipo: "general",
    area: "matemáticas",
    modulos: 43,
    precio: 20000,
    color: "#7C3AED",
    contenidos: [
      "Repaso números reales",
      "Funciones elementales",
      "Trigonometría aplicada",
      "Vectores y geometría",
      "Lógica e inducción",
      "Polinomios",
    ],
  },
  {
    id: "algebra-lineal-gen",
    nombre: "Álgebra Lineal",
    tipo: "general",
    area: "matemáticas",
    modulos: 52,
    precio: 40000,
    color: "#6366F1",
    contenidos: [
      "Espacio",
      "Sistemas de Ecuaciones",
      "Álgebra de Matrices",
      "Determinantes",
      "Espacios y Subespacios Vectoriales",
      "Valores y Vectores Propios",
      "Ortogonalidad",
      "Matrices Simétricas",
    ],
  },
  {
    id: "calculo-1var-gen",
    nombre: "Cálculo en una Variable",
    tipo: "general",
    area: "matemáticas",
    modulos: 85,
    precio: 40000,
    color: "#3B82F6",
    contenidos: [
      "Límites y continuidad",
      "Derivadas",
      "Aplicaciones de la derivada",
      "Integrales",
      "Técnicas de integración",
      "Aplicaciones de la integral",
    ],
  },
  {
    id: "calculo-dif-gen",
    nombre: "Cálculo Diferencial",
    tipo: "general",
    area: "matemáticas",
    modulos: 52,
    precio: 35000,
    color: "#0EA5E9",
    contenidos: [
      "Números reales e inecuaciones",
      "Funciones (dominio, recorrido, transformaciones, polinomiales, exp, log)",
      "Límites y continuidad",
      "Derivadas y reglas de derivación",
      "Aplicaciones de la derivada (TVM, L'Hôpital, optimización, graficación)",
    ],
  },
  {
    id: "calculo-int-gen",
    nombre: "Cálculo Integral",
    tipo: "general",
    area: "matemáticas",
    modulos: 48,
    precio: 35000,
    color: "#06B6D4",
    contenidos: [
      "Antiderivadas e integral indefinida",
      "Teorema Fundamental del Cálculo",
      "Técnicas (sustitución, partes, fracciones parciales, sustitución trigonométrica)",
      "Aplicaciones (área, volúmenes, longitud de arco, parametrizadas, polares)",
      "Integrales impropias",
      "Sucesiones y series (criterios, Taylor, potencias)",
    ],
  },
  {
    id: "calculo-vvar-gen",
    nombre: "Cálculo en Varias Variables",
    tipo: "general",
    area: "matemáticas",
    modulos: 41,
    precio: 40000,
    color: "#14B8A6",
    contenidos: [
      "Funciones de varias variables",
      "Derivadas parciales y gradiente",
      "Máximos y mínimos",
      "Multiplicadores de Lagrange",
      "Integrales dobles y triples",
      "Coordenadas curvilíneas",
    ],
  },
  {
    id: "calculo-vec-gen",
    nombre: "Cálculo Vectorial",
    tipo: "general",
    area: "matemáticas",
    modulos: 31,
    precio: 40000,
    color: "#10B981",
    contenidos: [
      "Curvas paramétricas y vectoriales",
      "Integrales de línea (escalares y vectoriales)",
      "Teorema de Green",
      "Rotacional y divergencia",
      "Integrales de superficie",
      "Teorema de Stokes",
      "Teorema de la divergencia",
    ],
  },
  {
    id: "ec-dif-gen",
    nombre: "Ecuaciones Diferenciales",
    tipo: "general",
    area: "matemáticas",
    modulos: 42,
    precio: 40000,
    color: "#EAB308",
    contenidos: [
      "EDO primer orden (separable, lineal, exacta, factor integrante, homogénea, Bernoulli)",
      "EDO segundo orden (coef constantes, Cauchy-Euler, coef indeterminados, variación parámetros)",
      "Sistemas de ED",
      "Transformada de Laplace (propiedades, traslación, escalón, convolución, Dirac)",
      "Soluciones por series (Bessel, Frobenius)",
      "Aplicaciones (mecánica, circuitos, modelos)",
    ],
  },
];

const carreras = [
  {
    id: "ing-civil",
    nombre: "Ingeniería Civil",
    facultad: "Facultad de Ingeniería",
    duracion: "11 semestres (5 años y medio) - Bachiller a los 4 sem, Licenciatura a los 8 sem, Título a los 11 sem",
    especialidades: [
      "Ingeniería Estructural",
      "Geotecnia",
      "Construcción",
      "Hidráulica - Hidrología",
    ],
    mallaUrl: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
    nota: "Carrera Acreditada por 5 años (oct 2020 - oct 2025) por el Consejo de Tecnología de la Agencia Acreditadora de Chile. Acreditación internacional CONAC (México). Sede: Santiago, Campus República. Beca Ingenia para mujeres (cubre 100% matrícula). Régimen diurno. Foco en obras civiles: estructuras, hidráulica, mecánica de suelos, construcción.",
    ramos: [
      {
        nombre: "Introducción a la Ingeniería Civil",
        codigo: "",
        area: "otra",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Áreas de desempeño del ingeniero civil",
          "Responsabilidades del ejercicio profesional",
          "Visión general de la disciplina",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso introductorio profesional sin componente matemático fuerte. No aplica split desde catálogo actual.",
      },
      {
        nombre: "Introducción a las Matemáticas",
        codigo: "",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Conjuntos numéricos y operatoria",
          "Resolución de ecuaciones de primer y segundo grado",
          "Lenguaje matemático",
          "Concepto de función",
          "Polinomios",
          "Nociones básicas de trigonometría",
        ],
        match: ["nivelacion-ing", "precalculo-cero"],
        matchLevel: "alto",
        splitDesde: "Nivelación Ingeniería cubre 100% del syllabus (números reales, funciones, polinomios, trigonometría, lógica). Precálculo desde Cero también encaja para alumnos con base más débil. Split directo posible.",
      },
      {
        nombre: "Química General",
        codigo: "",
        area: "química",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Estructura electrónica y enlace químico",
          "Estequiometría",
          "Soluciones",
          "Equilibrio químico",
          "Electroquímica",
          "Cinética química",
          "Resolución de ejercicios y problemas básicos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso de química general universitaria. Catálogo Se Remonta no tiene cursos base de química — oportunidad clara para producir 'Química General' como primer curso del área (alta demanda en ing. civil, civil industrial, civil química, salud).",
      },
      {
        nombre: "Física General",
        codigo: "",
        area: "física",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Bases conceptuales de la física",
          "Modelamiento de fenómenos cotidianos",
          "Aplicación de principios y leyes físicas",
          "Resolución de problemas elementales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso introductorio de física a nivel universitario. Catálogo Se Remonta no tiene cursos base de física — pendiente producir 'Física General' (mecánica, termodinámica básica) que sirva a varias ingenierías.",
      },
      {
        nombre: "Modelamiento y Programación de Sistemas",
        codigo: "",
        area: "programación",
        semestre: 2,
        prereqs: "Introducción a las Matemáticas",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Pensamiento lógico y estructurado",
          "Algoritmos para resolver problemas de ingeniería",
          "Lenguaje de programación MATLAB",
          "Programación aplicada a ingeniería",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso de programación con MATLAB como herramienta. Catálogo no tiene cursos base de programación — oportunidad para producir 'Programación para Ingeniería' (Python o MATLAB) que sirva para civil, industrial, comercial, y como gateway a informática.",
      },
      {
        nombre: "Cálculo Diferencial",
        codigo: "",
        area: "matemáticas",
        semestre: 2,
        prereqs: "Introducción a las Matemáticas",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Análisis y aplicación del concepto de límite",
          "Continuidad",
          "Derivadas",
          "Reglas de derivación",
          "Aplicaciones de la derivada",
          "Matrices (introducción)",
        ],
        match: ["calculo-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Diferencial Se Remonta cubre límites, continuidad, derivadas y aplicaciones (>70%). Falta complementar la unidad de matrices que UNAB incluye al final del curso — se cubre con Álgebra Lineal Se Remonta.",
      },
      {
        nombre: "Representación Gráfica de la Ingeniería",
        codigo: "",
        area: "otra",
        semestre: 2,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Visión espacial y dibujo técnico",
          "Modelado virtual con software BIM",
          "Dibujos 2D y modelos 3D de proyectos de edificación",
          "Documentos técnicos para diseño conceptual y de detalle",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso técnico-aplicado de BIM/dibujo de ingeniería civil. Fuera del scope del catálogo Se Remonta (matemáticas/ciencias).",
      },
      {
        nombre: "Cálculo Integral",
        codigo: "",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Cálculo Diferencial",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Elementos principales del cálculo integral",
          "Sucesiones y series",
          "Series de potencias para representar funciones",
          "Ecuaciones de rectas y planos en R3",
          "Continuidad y derivadas de funciones de varias variables",
          "Cálculo de extremos de funciones",
        ],
        match: ["calculo-int-gen", "calculo-vvar-gen"],
        matchLevel: "alto",
        splitDesde: "Curso híbrido que mezcla integral 1var (sucesiones, series) con introducción a varias variables. Cálculo Integral Se Remonta cubre toda la parte de integrales/series/Taylor; Cálculo en Varias Variables cubre planos R3, derivadas parciales y extremos. Split combinando ambos cursos.",
      },
      {
        nombre: "Introducción a la Mecánica",
        codigo: "",
        area: "física",
        semestre: 3,
        prereqs: "Física General, Cálculo Diferencial",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Modelamiento físico de causas del movimiento",
          "Cinemática y dinámica de cuerpos",
          "Interacciones conservativas y no conservativas",
          "Análisis del estado de un sistema físico",
          "Estado de movimiento de los sistemas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica clásica (cinemática, dinámica, energía). Sin curso base de física en catálogo — oportunidad para producir 'Mecánica I' o módulo dentro de Física General.",
      },
      {
        nombre: "Topografía",
        codigo: "",
        area: "otra",
        semestre: 3,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Levantamientos topográficos",
          "Planos plani-altimétricos de terrenos",
          "Movimientos de tierra y perfiles",
          "Equipo topográfico y software asociado",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso técnico-aplicado de obras civiles. Fuera del scope del catálogo Se Remonta.",
      },
      {
        nombre: "Sistema y Ecuaciones Diferenciales Lineales",
        codigo: "",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Cálculo Integral",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Modelado de problemas con ecuaciones diferenciales",
          "Métodos de solución de EDO de primer orden",
          "EDO de segundo orden",
          "Sistemas de ecuaciones diferenciales lineales",
          "Aplicaciones en ingeniería",
        ],
        match: ["ec-dif-gen", "algebra-lineal-gen"],
        matchLevel: "alto",
        splitDesde: "Ecuaciones Diferenciales Se Remonta cubre EDO 1er y 2do orden + sistemas (>70%). Para los sistemas lineales, Álgebra Lineal Se Remonta complementa con autovalores y autovectores. Split directo posible.",
      },
      {
        nombre: "Probabilidades y Estadísticas",
        codigo: "",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Cálculo Integral",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Estadística descriptiva",
          "Probabilidad",
          "Variables aleatorias y distribuciones",
          "Inferencia estadística",
          "Manejo científico de información",
          "Análisis de datos en proyectos de investigación",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Estadística y probabilidad para ingeniería. No hay curso base de estadística en catálogo — oportunidad de alta prioridad (presente en TODAS las ingenierías y en Ing. Comercial).",
      },
      {
        nombre: "Electricidad y Magnetismo",
        codigo: "",
        area: "física",
        semestre: 4,
        prereqs: "Introducción a la Mecánica",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Conceptos fundamentales del electromagnetismo",
          "Campo eléctrico y campo magnético",
          "Leyes del electromagnetismo (Coulomb, Gauss, Ampère, Faraday)",
          "Inducción electromagnética",
          "Aplicaciones a problemas de ingeniería",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso de electromagnetismo nivel universitario (típicamente 'Física II'). Sin curso base de física en catálogo — pendiente producir 'Electromagnetismo' como segundo curso de física.",
      },
      {
        nombre: "Materiales de Ingeniería",
        codigo: "",
        area: "química",
        semestre: 4,
        prereqs: "Química General",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Comportamiento y características de materiales",
          "Materiales en industria de la construcción",
          "Propiedades mecánicas y químicas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso de ciencia de materiales aplicado. Pendiente catálogo de química/materiales.",
      },
      {
        nombre: "Física Experimental",
        codigo: "",
        area: "física",
        semestre: 5,
        prereqs: "Introducción a la Mecánica",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Destrezas experimentales y analíticas",
          "Magnitudes físicas fundamentales",
          "Tratamiento y análisis de datos experimentales",
          "Trabajo en equipo y comunicación científico-técnica",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Laboratorio experimental de física. Difícil de digitalizar — quizá un curso teórico-conceptual de 'Métodos experimentales y análisis de errores'.",
      },
      {
        nombre: "Matemáticas Avanzadas I",
        codigo: "",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Cálculo Integral, Sistema y Ecuaciones Diferenciales Lineales",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Integrales de línea",
          "Integrales de superficie",
          "Teoremas integrales (Green, Stokes, divergencia)",
          "Integrales múltiples",
          "Cambio de variables",
          "Ecuaciones diferenciales parciales (introducción)",
        ],
        match: ["calculo-vec-gen", "calculo-vvar-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Vectorial Se Remonta cubre integrales de línea/superficie + teoremas (Green, Stokes, divergencia) directamente (>70%). Cálculo en Varias Variables aporta integrales múltiples y cambio de variables. Falta grabar específicamente el módulo introductorio de EDP (separación de variables, ecuación de calor/onda).",
      },
      {
        nombre: "Estática",
        codigo: "",
        area: "física",
        semestre: 5,
        prereqs: "Introducción a la Mecánica",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Análisis estructural interno y externo",
          "Estructuras isostáticas",
          "Equilibrio de cuerpos rígidos",
          "Diagramas de cuerpo libre",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica de cuerpo rígido orientada a estructuras. Tema típico de Mecánica/Física II. Pendiente curso base.",
      },
      {
        nombre: "Tecnología del Hormigón",
        codigo: "",
        area: "otra",
        semestre: 5,
        prereqs: "Materiales de Ingeniería",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Propiedades del hormigón",
          "Aplicaciones en construcción",
          "Validación experimental",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso técnico-aplicado de obras civiles. Fuera del scope del catálogo Se Remonta.",
      },
      {
        nombre: "Matemáticas Avanzadas II",
        codigo: "",
        area: "matemáticas",
        semestre: 6,
        prereqs: "Matemáticas Avanzadas I",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Métodos del cálculo numérico",
          "Resolución numérica de ecuaciones",
          "Métodos iterativos",
          "Interpolación y aproximación",
          "Integración y derivación numérica",
          "Aplicaciones a problemas de ingeniería",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso de análisis numérico/métodos numéricos. No hay curso base — oportunidad para producir 'Métodos Numéricos' (Python/Octave) como curso avanzado de matemáticas aplicadas.",
      },
      {
        nombre: "Economía",
        codigo: "",
        area: "economía",
        semestre: 6,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Principios básicos de Economía e Ingeniería Económica",
          "Análisis científico-matemático",
          "Toma de decisiones económicas",
          "Valor del dinero en el tiempo",
          "Factores en el desarrollo económico",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Ingeniería económica / valor del dinero en el tiempo. No hay curso base de economía — oportunidad alta (Civil, Civil Industrial, Comercial todos lo requieren).",
      },
      {
        nombre: "Investigación de Operaciones",
        codigo: "",
        area: "matemáticas",
        semestre: 6,
        prereqs: "Probabilidades y Estadísticas, Cálculo Integral",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Formulación, análisis e interpretación de modelos",
          "Programación matemática (lineal, entera)",
          "Optimización bajo certidumbre",
          "Aplicaciones en ingeniería",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Optimización y programación lineal. No hay curso base — oportunidad de prioridad media (presente en Civil, Industrial, Informática, Comercial).",
      },
      {
        nombre: "Mecánica de Sólidos",
        codigo: "",
        area: "física",
        semestre: 6,
        prereqs: "Estática",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Análisis estructural de esfuerzos internos",
          "Esfuerzos combinados",
          "Deformaciones",
          "Resistencia de materiales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Resistencia de materiales / mecánica de sólidos. Curso de física aplicada a estructuras. Pendiente catálogo física/ingeniería estructural.",
      },
      {
        nombre: "Ingeniería de Construcción",
        codigo: "",
        area: "otra",
        semestre: 6,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Tipos de proyectos y organizaciones de construcción",
          "Etapas de un proyecto",
          "Operaciones, procesos y técnicas constructivas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso técnico-aplicado de obras civiles. Fuera del scope del catálogo Se Remonta.",
      },
      {
        nombre: "Análisis Estructural",
        codigo: "",
        area: "otra",
        semestre: 7,
        prereqs: "Mecánica de Sólidos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Análisis de sistemas mecánicos lineales e hiperestáticos",
          "Métodos modernos de resolución",
          "Herramientas de Ingeniería Estructural",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización ingeniería civil estructural. Fuera del scope.",
      },
      {
        nombre: "Mecánica de Suelos I",
        codigo: "",
        area: "otra",
        semestre: 7,
        prereqs: "Mecánica de Sólidos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Clasificación de suelos",
          "Análisis de esfuerzos geoestáticos",
          "Cálculo de desplazamientos elásticos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización geotécnica. Fuera del scope.",
      },
      {
        nombre: "Mecánica de Fluidos",
        codigo: "",
        area: "física",
        semestre: 7,
        prereqs: "Matemáticas Avanzadas I",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Fenómenos del movimiento de fluidos",
          "Diseño hidráulico de redes en presión",
          "Singularidades hidráulicas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica de fluidos. Tema típico de física III/ingeniería. Pendiente catálogo física avanzada.",
      },
      {
        nombre: "Gestión de Operaciones de Construcción",
        codigo: "",
        area: "otra",
        semestre: 7,
        prereqs: "Ingeniería de Construcción",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Planificación y gestión en terreno",
          "Modelado de operaciones",
          "Información de producción",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización gestión de obras. Fuera del scope.",
      },
      {
        nombre: "Dinámica de Estructuras",
        codigo: "",
        area: "otra",
        semestre: 8,
        prereqs: "Análisis Estructural, Sistema y Ecuaciones Diferenciales Lineales",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Sistemas dinámicos de uno o varios grados de libertad",
          "Solicitaciones impulsivas y armónicas",
          "Control de respuesta dinámica",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización ingeniería estructural. Fuera del scope.",
      },
      {
        nombre: "Mecánica de Suelos II",
        codigo: "",
        area: "otra",
        semestre: 8,
        prereqs: "Mecánica de Suelos I",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Formulaciones teóricas avanzadas",
          "Resolución de problemas geotécnicos clásicos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización geotécnica. Fuera del scope.",
      },
      {
        nombre: "Ingeniería Hidráulica",
        codigo: "",
        area: "otra",
        semestre: 8,
        prereqs: "Mecánica de Fluidos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Diseño hidráulico de canales",
          "Lámina libre",
          "Aplicaciones en obras civiles",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización hidráulica. Fuera del scope.",
      },
      {
        nombre: "Planificación y Control de Proyectos",
        codigo: "",
        area: "otra",
        semestre: 8,
        prereqs: "Ingeniería de Construcción",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Planificación tradicional",
          "Modelos BIM (3D y 4D)",
          "Last Planner System",
          "Seguimiento y control de plazos y recursos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización gestión de proyectos de construcción. Fuera del scope.",
      },
      {
        nombre: "Costos y Presupuestos de Obras",
        codigo: "",
        area: "economía",
        semestre: 8,
        prereqs: "Economía",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Principios de la contabilidad financiera",
          "Estimación de costos",
          "Análisis económico de propuestas",
          "Control de costos en proyectos de construcción",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Contabilidad de costos aplicada a obras. Sin curso base de economía/contabilidad.",
      },
      {
        nombre: "Desarrollo de Proyectos Inmobiliarios",
        codigo: "",
        area: "economía",
        semestre: 9,
        prereqs: "Costos y Presupuestos de Obras",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Evaluación técnica y económica de proyectos",
          "Sectores público y privado",
          "Construcción inmobiliaria",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Evaluación de proyectos inmobiliarios. Sin curso base de evaluación de proyectos.",
      },
      {
        nombre: "Diseño de Elementos de Acero",
        codigo: "",
        area: "otra",
        semestre: 9,
        prereqs: "Análisis Estructural",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Diseño de elementos de acero",
          "Esfuerzos internos combinados",
          "Estructuras metálicas tridimensionales",
          "Proceso iterativo de diseño",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización estructural. Fuera del scope.",
      },
      {
        nombre: "Fundaciones",
        codigo: "",
        area: "otra",
        semestre: 9,
        prereqs: "Mecánica de Suelos II",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Fundaciones superficiales y profundas",
          "Diseño en suelos especiales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización geotécnica. Fuera del scope.",
      },
      {
        nombre: "Hormigón Armado",
        codigo: "",
        area: "otra",
        semestre: 9,
        prereqs: "Análisis Estructural, Tecnología del Hormigón",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Diseño de elementos estructurales de hormigón armado",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización estructural. Fuera del scope.",
      },
      {
        nombre: "Hidrología",
        codigo: "",
        area: "otra",
        semestre: 9,
        prereqs: "Mecánica de Fluidos, Probabilidades y Estadísticas",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Disponibilidad de recursos hídricos superficiales",
          "Aguas subterráneas",
          "Eventos extremos de avenida",
          "Análisis probabilístico",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización hidrología. Fuera del scope.",
      },
      {
        nombre: "Ingeniería Sísmica",
        codigo: "",
        area: "otra",
        semestre: 10,
        prereqs: "Dinámica de Estructuras",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil.pdf",
        contenidos: [
          "Diseño sísmico de elementos estructurales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización sísmica. Fuera del scope.",
      },
    ],
  },
  {
    id: "ing-civil-industrial",
    nombre: "Ingeniería Civil Industrial",
    facultad: "Facultad de Ingeniería",
    duracion: "10 semestres (5 años) - Bachiller a los 4 sem, Licenciatura a los 8 sem, Título a los 10 sem",
    especialidades: [
      "Inteligencia de Negocios",
      "Sistemas Productivos y de Servicios",
      "Transformación Digital",
      "Cadena de Suministro",
    ],
    mallaUrl: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
    nota: "100% movilidad en el primer año entre Civil Industrial, Civil Informática, Civil Eléctrica e Ing. en Computación e Informática (mismo Plan Común). Sedes: Santiago (Casona Las Condes y Antonio Varas), Viña del Mar, Concepción. Sello en Inteligencia de Negocios. Convenios con Missouri State, Universidad Europea de Madrid, ASU. Certificaciones IBM en Ciencia de Datos, IA, Ciberseguridad. 90,2% empleabilidad al 2do año (mifuturo.cl 2025).",
    ramos: [
      {
        nombre: "Física General",
        codigo: "",
        area: "física",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Bases conceptuales de la física",
          "Modelos físicos simples",
          "Principios y leyes físicas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso introductorio de física. Pendiente catálogo de física.",
      },
      {
        nombre: "Introducción a las Matemáticas",
        codigo: "",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Bases necesarias de matemáticas para ingeniería",
          "Punto de partida común para cursos posteriores",
          "Operatoria con números reales",
          "Ecuaciones e inecuaciones",
          "Funciones y polinomios",
        ],
        match: ["nivelacion-ing", "precalculo-cero"],
        matchLevel: "alto",
        splitDesde: "Nivelación Ingeniería Se Remonta cubre el syllabus directo. Para alumnos con base más débil, Precálculo desde Cero. Split directo posible.",
      },
      {
        nombre: "Introducción a la Programación",
        codigo: "",
        area: "programación",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Pensamiento computacional",
          "Modelado de datos y diseño de algoritmos",
          "Construcción y depuración de programas",
          "Resolución de problemas con programación",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Programación introductoria. Sin curso base de programación — oportunidad alta (presente en Civil Industrial, Informática, Comercial).",
      },
      {
        nombre: "Introducción a la Ingeniería",
        codigo: "",
        area: "otra",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Detección de problemáticas sociales",
          "Propuestas de soluciones innovadoras con base tecnológica",
          "Aporte de valor",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso transversal introductorio. Fuera del scope.",
      },
      {
        nombre: "Cálculo Diferencial",
        codigo: "",
        area: "matemáticas",
        semestre: 2,
        prereqs: "Introducción a las Matemáticas",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Análisis y aplicación de límites",
          "Continuidad",
          "Derivadas",
          "Matrices (introducción)",
          "Bases para asignaturas disciplinares",
        ],
        match: ["calculo-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Diferencial Se Remonta cubre directamente límites/continuidad/derivadas. Para la unidad de matrices se complementa con Álgebra Lineal Se Remonta. Split directo.",
      },
      {
        nombre: "Física Experimental",
        codigo: "",
        area: "física",
        semestre: 2,
        prereqs: "Física General",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Métodos de obtención de datos",
          "Tratamiento estadístico de datos experimentales",
          "Relaciones entre variables físicas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Laboratorio experimental. Fuera del scope inmediato.",
      },
      {
        nombre: "Química y Ambiente",
        codigo: "",
        area: "química",
        semestre: 2,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Principios básicos de la química",
          "Interrelación con otras ciencias naturales",
          "Aplicaciones ambientales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Química general con énfasis ambiental. Pendiente curso base.",
      },
      {
        nombre: "Base de Datos",
        codigo: "",
        area: "programación",
        semestre: 2,
        prereqs: "Introducción a la Programación",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Modelos de datos eficientes y escalables",
          "Reglas de integridad",
          "SQL",
          "Información de calidad para empresas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso de bases de datos / SQL. Sin catálogo de programación — oportunidad de prioridad media.",
      },
      {
        nombre: "Mecánica",
        codigo: "",
        area: "física",
        semestre: 3,
        prereqs: "Cálculo Diferencial, Física General",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Mecánica clásica newtoniana",
          "Movimiento, fuerza, trabajo y energía",
          "Sistemas de partículas",
          "Análisis con álgebra y cálculo",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica clásica. Pendiente catálogo de física.",
      },
      {
        nombre: "Cálculo Integral",
        codigo: "",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Cálculo Diferencial",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Elementos principales del cálculo integral",
          "Métodos de integración",
          "Aplicación a diferentes funciones",
        ],
        match: ["calculo-int-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Integral Se Remonta cubre antiderivadas, técnicas de integración, aplicaciones, integrales impropias y series (>70%). Split directo.",
      },
      {
        nombre: "Compliance & Accountability",
        codigo: "",
        area: "otra",
        semestre: 3,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Principales normativas del derecho",
          "Responsabilidad social empresarial",
          "Compliance corporativo",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso legal/business. Fuera del scope STEM.",
      },
      {
        nombre: "Procesos Industriales",
        codigo: "",
        area: "otra",
        semestre: 3,
        prereqs: "Química y Ambiente, Física General",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Aplicación de ciencias básicas e ingeniería",
          "Balances de masa y energía",
          "Formulación de problemas industriales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso industrial aplicado. Pendiente catálogo física/química aplicada.",
      },
      {
        nombre: "Electricidad y Magnetismo",
        codigo: "",
        area: "física",
        semestre: 4,
        prereqs: "Mecánica",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Cargas distribuidas y corrientes eléctricas",
          "Campo eléctrico y magnético",
          "Inducción electromagnética",
          "Aplicaciones en ciencia e ingeniería",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Electromagnetismo nivel universitario. Pendiente catálogo física.",
      },
      {
        nombre: "Sistemas y Ecuaciones Diferenciales Lineales",
        codigo: "",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Cálculo Integral",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Modelado matemático con ecuaciones diferenciales",
          "Métodos de solución de EDO",
          "Sistemas lineales",
        ],
        match: ["ec-dif-gen", "algebra-lineal-gen"],
        matchLevel: "alto",
        splitDesde: "Ecuaciones Diferenciales Se Remonta cubre EDO 1er/2do orden y sistemas. Álgebra Lineal aporta el lenguaje matricial requerido para sistemas lineales. Split directo.",
      },
      {
        nombre: "Métodos Cuantitativos",
        codigo: "",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Cálculo Integral",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Manejo científico de información",
          "Estadística descriptiva e inferencial",
          "Probabilidad",
          "Aplicaciones en proyectos de ingeniería",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Estadística + probabilidad para ingeniería industrial. Sin curso base — oportunidad alta.",
      },
      {
        nombre: "Economía",
        codigo: "",
        area: "economía",
        semestre: 5,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Herramientas teórico-prácticas de economía",
          "Toma de decisiones económicas",
          "Microeconomía y macroeconomía básicas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Fundamentos de economía para ingeniería. Sin curso base — oportunidad alta.",
      },
      {
        nombre: "Investigación de Operaciones",
        codigo: "",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Métodos Cuantitativos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Modelos de investigación de operaciones",
          "Programación lineal y entera",
          "Toma de decisión bajo certidumbre",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Optimización aplicada. Sin curso base — oportunidad media.",
      },
      {
        nombre: "Economía Circular",
        codigo: "",
        area: "economía",
        semestre: 5,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Cambio de paradigma en economía",
          "Casos prácticos de economía circular",
          "Estrategias empresariales sustentables",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso aplicado de sustentabilidad/economía circular. Pendiente catálogo economía.",
      },
      {
        nombre: "Minería de Datos",
        codigo: "",
        area: "programación",
        semestre: 6,
        prereqs: "Métodos Cuantitativos, Base de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Razonamiento científico aplicado a datos",
          "Generación y verificación de hipótesis",
          "Técnicas de minería de datos",
          "Modelos predictivos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Data mining / análisis exploratorio. Sin curso base de programación o estadística avanzada.",
      },
      {
        nombre: "Costos y Presupuestos",
        codigo: "",
        area: "economía",
        semestre: 6,
        prereqs: "Economía",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Roles de información y control en contabilidad",
          "Estructura de costos y presupuestos",
          "Contabilidad financiera básica",
          "Interpretación y uso",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Contabilidad de costos. Pendiente catálogo economía/contabilidad.",
      },
      {
        nombre: "Redes y Sistemas Estocásticos en Ingeniería",
        codigo: "",
        area: "matemáticas",
        semestre: 6,
        prereqs: "Investigación de Operaciones, Métodos Cuantitativos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Sistemas con componentes probabilísticos/aleatorios",
          "Simulación y modelación",
          "Resolución de problemas en ambientes complejos",
          "Procesos estocásticos básicos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Procesos estocásticos / simulación. Curso avanzado, requiere estadística previa. Pendiente catálogo.",
      },
      {
        nombre: "Gestión de la Cadena de Suministro",
        codigo: "",
        area: "otra",
        semestre: 6,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Sistemas logísticos de suministro y distribución",
          "Manufactura y servicios",
          "Herramientas de gestión",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización supply chain. Fuera del scope.",
      },
      {
        nombre: "Gestión de la Transformación Digital",
        codigo: "",
        area: "otra",
        semestre: 7,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Plan de transformación digital",
          "Mejora del valor organizacional",
          "Cumplimiento de normativas",
          "Gestión del cambio cultural",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso de gestión digital. Fuera del scope STEM.",
      },
      {
        nombre: "Ingeniería Económica",
        codigo: "",
        area: "economía",
        semestre: 7,
        prereqs: "Economía",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Matemáticas financieras",
          "Distinción de opciones de inversión",
          "Construcción de flujos de caja",
          "Indicadores económico-financieros (VAN, TIR)",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Matemáticas financieras / evaluación económica. Sin curso base de finanzas — oportunidad alta.",
      },
      {
        nombre: "Toma de Decisiones Bajo Incertidumbre",
        codigo: "",
        area: "matemáticas",
        semestre: 7,
        prereqs: "Redes y Sistemas Estocásticos en Ingeniería",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Modelos de IO con incertidumbre",
          "Programación estocástica",
          "Análisis de decisiones",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Optimización estocástica avanzada. Pendiente catálogo.",
      },
      {
        nombre: "Toma de Decisiones en la Cadena de Suministro",
        codigo: "",
        area: "otra",
        semestre: 7,
        prereqs: "Gestión de la Cadena de Suministro",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Actividades logísticas",
          "Mirada integradora y sistémica",
          "Funcionamiento de cadenas de suministros",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización supply chain. Fuera del scope.",
      },
      {
        nombre: "Evaluación de Proyectos",
        codigo: "",
        area: "economía",
        semestre: 8,
        prereqs: "Ingeniería Económica",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Preparación, formulación y evaluación de proyectos",
          "Estudios de viabilidad: mercado, técnica, legal, organizacional, económica",
          "Proyectos privados y sociales",
          "Nivel de prefactibilidad",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Evaluación de proyectos privados/sociales. Sin curso base — oportunidad alta para ramos de ingeniería + comercial.",
      },
      {
        nombre: "Simulación de Sistemas",
        codigo: "",
        area: "programación",
        semestre: 8,
        prereqs: "Redes y Sistemas Estocásticos en Ingeniería",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Modelos de simulación discreta",
          "Toma de decisiones basada en simulación",
          "Software de simulación",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Simulación de eventos discretos. Pendiente catálogo.",
      },
      {
        nombre: "Estrategia y Sustentabilidad en Cadena de Suministro",
        codigo: "",
        area: "otra",
        semestre: 8,
        prereqs: "Gestión de la Cadena de Suministro",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Desafíos de sustentabilidad en logística",
          "Procesos de cadena de abastecimiento",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Especialización supply chain. Fuera del scope.",
      },
      {
        nombre: "Analítica",
        codigo: "",
        area: "programación",
        semestre: 8,
        prereqs: "Minería de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Técnicas analíticas sobre Big Data",
          "Sistemas productivos y de servicios",
          "Toma de decisiones basada en datos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Big Data / analítica avanzada. Pendiente catálogo programación.",
      },
      {
        nombre: "Finanzas Corporativas",
        codigo: "",
        area: "economía",
        semestre: 9,
        prereqs: "Ingeniería Económica, Evaluación de Proyectos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Mercados financieros",
          "Medición del riesgo",
          "Políticas financieras de largo plazo",
          "Mercado de capitales nacional e internacional",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Finanzas corporativas avanzadas. Sin curso base de finanzas.",
      },
      {
        nombre: "Inteligencia de Negocios",
        codigo: "",
        area: "programación",
        semestre: 9,
        prereqs: "Base de Datos, Minería de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Procesamiento analítico en línea (OLAP)",
          "Tratamiento de datos",
          "Reporting y dashboards",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "BI / OLAP. Pendiente catálogo programación.",
      },
      {
        nombre: "Marketing",
        codigo: "",
        area: "economía",
        semestre: 9,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Plan de marketing",
          "Marketing tradicional y digital",
          "Herramientas y conceptos clave",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Marketing introductorio. Sin curso base de marketing/negocios.",
      },
      {
        nombre: "Gestión Estratégica",
        codigo: "",
        area: "otra",
        semestre: 9,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_industrial.pdf",
        contenidos: [
          "Modelos de diseño estratégico",
          "Plan estratégico global",
          "Aplicación a empresas y negocios",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Gestión estratégica. Fuera del scope STEM.",
      },
    ],
  },
  {
    id: "ing-civil-informatica",
    nombre: "Ingeniería Civil Informática",
    facultad: "Facultad de Ingeniería",
    duracion: "10 semestres (5 años) - Bachiller a los 4 sem, Licenciatura a los 8 sem, Título a los 10 sem",
    especialidades: [
      "Inteligencia Artificial",
      "Productos Tecnológicos",
      "Transformación Digital",
      "Ciencia de Datos",
      "Ciberseguridad",
    ],
    mallaUrl: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
    nota: "Acreditada internacionalmente 3 años (mayo 2023 - mayo 2026) por EQANIE - EURO INF. 100% movilidad primer año (mismo Plan Común Civil Industrial). Sedes: Casona Las Condes, Antonio Varas, Viña del Mar, Concepción. Certificaciones IBM en Ciencia de Datos, IA, Ciberseguridad. Convenios con ASU. 86% empleabilidad al 1er año / 93,3% al 2do año (mifuturo.cl 2025).",
    ramos: [
      {
        nombre: "Introducción a la Programación",
        codigo: "",
        area: "programación",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Pensamiento computacional",
          "Modelado de datos y diseño de algoritmos",
          "Construcción y depuración de programas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Programación introductoria. Sin curso base.",
      },
      {
        nombre: "Introducción a la Ingeniería",
        codigo: "",
        area: "otra",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Rol de la ingeniería en la sociedad",
          "Identificación de problemáticas",
          "Soluciones de alto impacto",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso introductorio. Fuera del scope.",
      },
      {
        nombre: "Introducción a las Matemáticas",
        codigo: "",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Operaciones con números reales",
          "Ecuaciones e inecuaciones",
          "Lógica y conjuntos matemáticos",
          "Polinomios",
          "Funciones de modelación",
        ],
        match: ["nivelacion-ing", "precalculo-cero"],
        matchLevel: "alto",
        splitDesde: "Nivelación Ingeniería cubre el syllabus directo. Split directo.",
      },
      {
        nombre: "Física General",
        codigo: "",
        area: "física",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Principios físicos fundamentales",
          "Razonamiento científico",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Física introductoria. Pendiente catálogo física.",
      },
      {
        nombre: "Base de Datos",
        codigo: "",
        area: "programación",
        semestre: 2,
        prereqs: "Introducción a la Programación",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Modelos de datos eficientes y escalables",
          "Información de calidad y oportuna",
          "Bases relacionales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Bases de datos. Pendiente catálogo programación.",
      },
      {
        nombre: "Cálculo Diferencial",
        codigo: "",
        area: "matemáticas",
        semestre: 2,
        prereqs: "Introducción a las Matemáticas",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Límites y continuidad",
          "Derivadas",
          "Matrices (introducción)",
        ],
        match: ["calculo-dif-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Diferencial Se Remonta cubre el syllabus directo. Para matrices, complementar con Álgebra Lineal Se Remonta. Split directo.",
      },
      {
        nombre: "Física Experimental",
        codigo: "",
        area: "física",
        semestre: 2,
        prereqs: "Física General",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Métodos de obtención y tratamiento de datos",
          "Relaciones entre variables físicas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Laboratorio de física. Fuera del scope inmediato.",
      },
      {
        nombre: "Química y Ambiente",
        codigo: "",
        area: "química",
        semestre: 2,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Principios básicos de la química",
          "Interrelación con ciencias naturales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Química general. Pendiente catálogo química.",
      },
      {
        nombre: "Compliance & Accountability",
        codigo: "",
        area: "otra",
        semestre: 3,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Conceptos normativos",
          "Contexto corporativo normativo externo",
          "Insumo para transformación digital",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso legal/business. Fuera del scope.",
      },
      {
        nombre: "Algoritmos y Estructuras de Datos",
        codigo: "",
        area: "programación",
        semestre: 3,
        prereqs: "Introducción a la Programación",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Estructuras de datos clásicas (listas, árboles, grafos)",
          "Algoritmos asociados",
          "Resolución de problemas computacionales",
          "Selección de estructura adecuada",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso central de informática. Sin catálogo programación — oportunidad alta para curso de Algoritmos y Estructuras de Datos.",
      },
      {
        nombre: "Cálculo Integral",
        codigo: "",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Cálculo Diferencial",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Conceptos fundamentales de programación aplicada",
          "Estructuras de datos y complejidad algorítmica (en algunos programas)",
          "Integral indefinida y definida",
          "Técnicas de integración",
          "Aplicaciones",
        ],
        match: ["calculo-int-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Integral Se Remonta cubre el syllabus estándar de integral. (Nota: la reseña UNAB tiene texto que parece pegado de otro ramo — se verifica el syllabus estándar). Split directo.",
        nota: "La reseña oficial UNAB es ambigua/cortada; contenidos validados contra estándar de Cálculo Integral universitario.",
      },
      {
        nombre: "Mecánica",
        codigo: "",
        area: "física",
        semestre: 3,
        prereqs: "Cálculo Diferencial, Física General",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Mecánica clásica newtoniana",
          "Movimiento, fuerza, trabajo, energía",
          "Sistemas de partículas y sólido rígido",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Mecánica clásica. Pendiente catálogo física.",
      },
      {
        nombre: "Sistemas y Ecuaciones Diferenciales Lineales",
        codigo: "",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Cálculo Integral",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Modelado con ecuaciones diferenciales",
          "Métodos de solución",
          "Sistemas lineales",
        ],
        match: ["ec-dif-gen", "algebra-lineal-gen"],
        matchLevel: "alto",
        splitDesde: "Ecuaciones Diferenciales + Álgebra Lineal Se Remonta cubren el syllabus. Split directo.",
      },
      {
        nombre: "Electricidad y Magnetismo",
        codigo: "",
        area: "física",
        semestre: 4,
        prereqs: "Mecánica",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Cargas distribuidas y corrientes eléctricas",
          "Campo eléctrico y magnético",
          "Inducción electromagnética",
          "Aplicaciones",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Electromagnetismo. Pendiente catálogo física.",
      },
      {
        nombre: "Métodos Cuantitativos",
        codigo: "",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Cálculo Integral",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Manejo científico de información",
          "Estadística descriptiva e inferencial",
          "Probabilidad",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Estadística para informática. Sin curso base — oportunidad alta.",
      },
      {
        nombre: "Paradigmas de Programación",
        codigo: "",
        area: "programación",
        semestre: 5,
        prereqs: "Algoritmos y Estructuras de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Paradigma imperativo, funcional, lógico, orientado a objetos",
          "Selección de paradigma según requisitos",
          "Resolución computacional de problemas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso teórico de paradigmas. Pendiente catálogo programación.",
      },
      {
        nombre: "Fundamentos de Computación de Alto Desempeño",
        codigo: "",
        area: "programación",
        semestre: 5,
        prereqs: "Paradigmas de Programación, Algoritmos y Estructuras de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Optimización de programas",
          "Procesador y sistema operativo",
          "Programación paralela",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "HPC / programación paralela. Curso avanzado, fuera del scope inmediato.",
      },
      {
        nombre: "Análisis y Diseño de Algoritmos",
        codigo: "",
        area: "programación",
        semestre: 5,
        prereqs: "Algoritmos y Estructuras de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Técnicas de diseño de algoritmos (divide y vencerás, programación dinámica, voraz)",
          "Análisis de complejidad",
          "Algoritmos eficientes",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso clave de informática. Pendiente catálogo programación.",
      },
      {
        nombre: "Minería de Datos",
        codigo: "",
        area: "programación",
        semestre: 6,
        prereqs: "Métodos Cuantitativos, Base de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Razonamiento científico aplicado a datos",
          "Generación y verificación de hipótesis",
          "Técnicas de minería de datos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Data mining. Pendiente catálogo programación/estadística.",
      },
      {
        nombre: "Desarrollo Web y Móvil",
        codigo: "",
        area: "programación",
        semestre: 6,
        prereqs: "Paradigmas de Programación, Base de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Plataformas web",
          "Aplicaciones móviles",
          "Solución de problemáticas organizacionales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Web y mobile dev. Pendiente catálogo programación.",
      },
      {
        nombre: "Infraestructura TI",
        codigo: "",
        area: "programación",
        semestre: 6,
        prereqs: "Sin prerrequisitos especificados",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Infraestructura tecnológica",
          "Estándares y buenas prácticas de operación",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Infraestructura TI / DevOps. Fuera del scope inmediato.",
      },
      {
        nombre: "Fundamentos de Inteligencia Artificial",
        codigo: "",
        area: "programación",
        semestre: 6,
        prereqs: "Algoritmos y Estructuras de Datos, Métodos Cuantitativos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Técnicas de inteligencia artificial",
          "Modelado y resolución de problemas",
          "Contextos reales y simulados",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Fundamentos de IA. Sin catálogo programación — oportunidad alta.",
      },
      {
        nombre: "Ingeniería de Software I",
        codigo: "",
        area: "programación",
        semestre: 7,
        prereqs: "Paradigmas de Programación",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Herramientas, métodos y técnicas para proyectos de software",
          "Metodologías de desarrollo",
          "Calidad y costos",
          "Etapas formales de ingeniería de software",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Ingeniería de software. Pendiente catálogo programación.",
      },
      {
        nombre: "Aprendizaje de Máquina",
        codigo: "",
        area: "programación",
        semestre: 7,
        prereqs: "Fundamentos de Inteligencia Artificial, Métodos Cuantitativos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Software basado en aprendizaje automático",
          "Modelos supervisados y no supervisados",
          "Aporte de valor a organizaciones",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Machine Learning. Pendiente catálogo programación/estadística avanzada.",
      },
      {
        nombre: "Optimización",
        codigo: "",
        area: "matemáticas",
        semestre: 7,
        prereqs: "Métodos Cuantitativos, Algoritmos y Estructuras de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Explosión combinatoria y NP-completitud",
          "Programación lineal entera mixta",
          "Búsqueda incompleta",
          "Propagación de restricciones",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Optimización combinatoria. Pendiente catálogo.",
      },
      {
        nombre: "Gestión de la Transformación Digital",
        codigo: "",
        area: "otra",
        semestre: 8,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Plan de transformación digital",
          "Mejora del valor organizacional",
          "Cumplimiento normativo",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Gestión digital. Fuera del scope STEM.",
      },
      {
        nombre: "Ingeniería de Software II",
        codigo: "",
        area: "programación",
        semestre: 8,
        prereqs: "Ingeniería de Software I",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Desarrollo de producto desde concepción a deployment",
          "Gestión de proyectos informáticos",
          "Procesos, técnicas y herramientas",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Ingeniería de software avanzada. Pendiente catálogo.",
      },
      {
        nombre: "Ciberseguridad",
        codigo: "",
        area: "programación",
        semestre: 8,
        prereqs: "Infraestructura TI, Ingeniería de Software I",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Diagnóstico de seguridad de infraestructura",
          "Identificación de ataques y vulnerabilidades",
          "Herramientas de software para seguridad",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Ciberseguridad. Pendiente catálogo programación.",
      },
      {
        nombre: "Administración Financiera de Proyectos I+D+i",
        codigo: "",
        area: "economía",
        semestre: 9,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Producto de base tecnológica",
          "Evaluación financiera",
          "Aporte económico y social",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Finanzas para I+D. Pendiente catálogo economía.",
      },
      {
        nombre: "Ciencia de Datos",
        codigo: "",
        area: "programación",
        semestre: 9,
        prereqs: "Aprendizaje de Máquina, Minería de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_civil_informatica.pdf",
        contenidos: [
          "Proyectos de ciencia de datos alineados a estrategia",
          "Plataformas tecnológicas",
          "Visualización y minería de datos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Data Science aplicada. Pendiente catálogo programación.",
      },
    ],
  },
  {
    id: "ing-comercial",
    nombre: "Ingeniería Comercial",
    facultad: "Facultad de Economía y Negocios",
    duracion: "10 semestres (5 años) - Licenciatura a los 7 sem, Título a los 10 sem",
    especialidades: [
      "Cursos de Especialización (varían por sede y semestre)",
      "Posibilidad de Magíster integrado",
    ],
    mallaUrl: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
    nota: "Acreditada Internacionalmente 10 años (2018-2028) por ACBSP. Doble titulación con Missouri State, Neoma BS, Kedge BS, SNHU, Univ. Europea de Madrid, De Montfort, Univ. Salamanca. Convenios con UC Irvine y ASU. Sedes: Santiago (Casona Las Condes, Bellavista), Viña del Mar, Concepción (diurno) y Santiago/Viña/Concepción (vespertino). 82,1% empleabilidad al 2do año (mifuturo.cl 2025). Malla innovada con énfasis en Emprendimiento, Innovación, Tecnología y Sostenibilidad.",
    ramos: [
      {
        nombre: "Fundamentos de Economía",
        codigo: "",
        area: "economía",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Conceptos y nociones básicas de Economía",
          "El problema económico",
          "Introducción a la teoría económica",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Curso introductorio de economía. Sin curso base de economía — oportunidad alta para producir 'Fundamentos de Economía' (alta demanda en Comercial, Civil Industrial, Civil Informática).",
      },
      {
        nombre: "Juego de Negocios",
        codigo: "",
        area: "economía",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Conceptos fundamentales de los negocios",
          "Entorno empresarial simulado",
          "Toma de decisiones empresariales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Simulador de negocios. Curso aplicado-vivencial. Pendiente catálogo negocios.",
      },
      {
        nombre: "Gestión de Organizaciones",
        codigo: "",
        area: "otra",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Conceptos básicos de Administración",
          "Retos y situaciones de las organizaciones",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Administración general. Pendiente catálogo negocios.",
      },
      {
        nombre: "Matemática I",
        codigo: "",
        area: "matemáticas",
        semestre: 1,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Álgebra elemental",
          "Lógica y conjuntos",
          "Geometría analítica",
          "Suma y progresiones",
          "Técnicas de factorización",
          "Resolución de ecuaciones",
          "Operaciones con polinomios",
        ],
        match: ["nivelacion-ing", "precalculo-cero"],
        matchLevel: "alto",
        splitDesde: "Nivelación Ingeniería + Precálculo desde Cero cubren todo el syllabus de Matemática I (álgebra, lógica, conjuntos, geometría analítica, polinomios). Split directo posible — el curso es esencialmente precálculo aplicado a negocios.",
      },
      {
        nombre: "Microeconomía I",
        codigo: "",
        area: "economía",
        semestre: 2,
        prereqs: "Fundamentos de Economía",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Teoría de la conducta del consumidor",
          "Teoría de la firma",
          "Demanda y oferta",
          "Mercado en competencia perfecta",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Microeconomía I clásica. Sin curso base — oportunidad alta para producir 'Microeconomía I' (presente en TODO programa de comercial/economía).",
      },
      {
        nombre: "Aplicaciones Informáticas para los Negocios",
        codigo: "",
        area: "programación",
        semestre: 2,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Excel avanzado para negocios",
          "Herramientas tecnológicas para gestión",
          "Análisis de datos básico",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Excel/herramientas tech para negocios. Pendiente catálogo programación.",
      },
      {
        nombre: "Contabilidad",
        codigo: "",
        area: "economía",
        semestre: 2,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Sistemas de información contable",
          "Rol en la gestión empresarial",
          "Principios contables básicos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Contabilidad básica. Sin curso base — oportunidad alta.",
      },
      {
        nombre: "Matemática II",
        codigo: "",
        area: "matemáticas",
        semestre: 2,
        prereqs: "Matemática I",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Cálculo en una variable",
          "Inecuaciones",
          "Funciones, límites y derivadas",
          "Aplicaciones en negocios y economía",
        ],
        match: ["calculo-dif-gen", "calculo-1var-gen"],
        matchLevel: "alto",
        splitDesde: "Cálculo Diferencial Se Remonta cubre el syllabus directo (límites, derivadas, aplicaciones). Cálculo en una Variable también encaja por incluir aplicaciones. Split directo, mostrando ejemplos aplicados a economía/negocios.",
      },
      {
        nombre: "Macroeconomía I",
        codigo: "",
        area: "economía",
        semestre: 3,
        prereqs: "Microeconomía I, Fundamentos de Economía",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Modelo IS-LM-Demanda Agregada-Oferta Agregada",
          "Políticas fiscales y monetarias",
          "Economía cerrada",
          "Corto, mediano y largo plazo",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Macroeconomía I. Sin curso base — oportunidad alta.",
      },
      {
        nombre: "Contabilidad Gerencial",
        codigo: "",
        area: "economía",
        semestre: 3,
        prereqs: "Contabilidad",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Contabilidad gerencial",
          "Contabilidad de costos",
          "Análisis presupuestario",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Contabilidad gerencial. Pendiente catálogo economía/contabilidad.",
      },
      {
        nombre: "Matemática III",
        codigo: "",
        area: "matemáticas",
        semestre: 3,
        prereqs: "Matemática II",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Cálculo en varias variables (derivadas parciales, gradientes)",
          "Cálculo integral (1var y multivariable)",
          "Programación lineal",
          "Aplicaciones en negocios y economía",
        ],
        match: ["calculo-int-gen", "calculo-vvar-gen"],
        matchLevel: "medio",
        splitDesde: "Cálculo Integral cubre la integral 1var; Cálculo en Varias Variables cubre derivadas parciales y multiplicadores de Lagrange (~50-60%). Falta grabar específicamente la unidad de programación lineal (típica de comercial/industrial), que es ~30-40% del syllabus.",
      },
      {
        nombre: "Macroeconomía II",
        codigo: "",
        area: "economía",
        semestre: 4,
        prereqs: "Macroeconomía I",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Modelo IS-LM-DA-OA para economías abiertas",
          "Tipo de cambio",
          "Políticas fiscales y monetarias",
          "Corto, mediano y largo plazo",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Macroeconomía II (economía abierta). Pendiente catálogo economía.",
      },
      {
        nombre: "Dirección Financiera",
        codigo: "",
        area: "economía",
        semestre: 4,
        prereqs: "Contabilidad, Matemática II",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Funciones del administrador financiero de corto plazo",
          "Capital de trabajo",
          "Decisiones de financiamiento",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Finanzas de corto plazo. Pendiente catálogo finanzas.",
      },
      {
        nombre: "Estadística I",
        codigo: "",
        area: "matemáticas",
        semestre: 4,
        prereqs: "Matemática II",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Estadística descriptiva",
          "Probabilidad",
          "Variables aleatorias y distribuciones",
          "Pilares de la inferencia estadística",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Estadística descriptiva + probabilidad. Sin curso base — oportunidad alta (presente en TODOS los programas de ingeniería/comercial/economía).",
      },
      {
        nombre: "Microeconomía II",
        codigo: "",
        area: "economía",
        semestre: 5,
        prereqs: "Microeconomía I",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Fallas de mercado",
          "Competencia imperfecta",
          "Mecanismos para abordar fallas",
          "Externalidades, bienes públicos, asimetría de información",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Microeconomía II. Pendiente catálogo economía.",
      },
      {
        nombre: "Dirección de Marketing",
        codigo: "",
        area: "economía",
        semestre: 5,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Creación y comunicación de valor de marca",
          "Necesidades y deseos del consumidor",
          "Estrategia de marca",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Marketing introductorio. Pendiente catálogo negocios.",
      },
      {
        nombre: "Estadística II",
        codigo: "",
        area: "matemáticas",
        semestre: 5,
        prereqs: "Estadística I",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Muestreo",
          "Modelos de regresión lineal simple",
          "Correlación lineal simple",
          "Inferencia estadística aplicada",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Estadística inferencial + regresión. Pendiente catálogo estadística.",
      },
      {
        nombre: "Econometría",
        codigo: "",
        area: "economía",
        semestre: 6,
        prereqs: "Estadística II, Macroeconomía II",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Modelos de regresión simple y múltiple",
          "Estimación de parámetros",
          "Funciones de comportamiento",
          "Modelos económicos y financieros",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Econometría. Pendiente catálogo (curso avanzado, requiere estadística).",
      },
      {
        nombre: "Gestión de Operaciones",
        codigo: "",
        area: "otra",
        semestre: 6,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Proceso de operaciones",
          "Interacción con áreas de la empresa",
          "Herramientas analíticas para toma de decisiones",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Gestión de operaciones. Pendiente catálogo negocios.",
      },
      {
        nombre: "Dirección de Empresas",
        codigo: "",
        area: "otra",
        semestre: 6,
        prereqs: "Gestión de Organizaciones",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Identificación de necesidades",
          "Propuesta y evaluación de ideas",
          "Plan de negocios",
          "Espíritu emprendedor",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Plan de negocios / emprendimiento. Fuera del scope inmediato.",
      },
      {
        nombre: "Derecho y Empresa",
        codigo: "",
        area: "otra",
        semestre: 6,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Legislación civil y mercantil",
          "Marco legal de la actividad empresarial chilena",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Derecho comercial. Fuera del scope STEM.",
      },
      {
        nombre: "Marketing para la Toma de Decisiones",
        codigo: "",
        area: "economía",
        semestre: 7,
        prereqs: "Dirección de Marketing",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Diseño de plan de marketing estratégico",
          "Implementación organizacional",
          "Decisiones de marketing",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Marketing estratégico. Pendiente catálogo negocios.",
      },
      {
        nombre: "Finanzas Corporativas",
        codigo: "",
        area: "economía",
        semestre: 7,
        prereqs: "Dirección Financiera",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Decisiones financieras de largo plazo",
          "Mercado de capitales",
          "Comportamiento del consumidor en mercado de capitales",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Finanzas corporativas. Pendiente catálogo finanzas.",
      },
      {
        nombre: "Ciencia de Datos",
        codigo: "",
        area: "programación",
        semestre: 8,
        prereqs: "Estadística II, Aplicaciones Informáticas para los Negocios",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Análisis de fuentes de datos",
          "Patrones y estimaciones",
          "Toma de decisiones basada en datos",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Data Science para negocios. Pendiente catálogo programación.",
      },
      {
        nombre: "Dirección Estratégica",
        codigo: "",
        area: "otra",
        semestre: 8,
        prereqs: "Dirección de Empresas",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Conceptos, modelos y herramientas estratégicas",
          "Diseño y ejecución de estrategia",
          "Análisis competitivo y organizacional",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Gestión estratégica. Fuera del scope STEM.",
      },
      {
        nombre: "Negocios Sostenibles",
        codigo: "",
        area: "otra",
        semestre: 8,
        prereqs: "Sin prerrequisitos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Preocupaciones sociales y medioambientales",
          "Gestión organizacional sustentable",
          "Bien Común",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Sostenibilidad empresarial. Fuera del scope.",
      },
      {
        nombre: "Inteligencia de Negocios",
        codigo: "",
        area: "programación",
        semestre: 9,
        prereqs: "Ciencia de Datos",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "BI y dashboards",
          "Procesamiento analítico",
          "Toma de decisiones basada en información",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "BI para negocios. Pendiente catálogo programación.",
      },
      {
        nombre: "Control de Gestión",
        codigo: "",
        area: "economía",
        semestre: 9,
        prereqs: "Contabilidad Gerencial, Dirección Financiera",
        fuenteContenido: "https://www.unab.cl/carreras/mallas/ing_comercial_plan_comun_vespertino.pdf",
        contenidos: [
          "Sistemas de control de gestión",
          "Indicadores de desempeño",
          "Balanced Scorecard",
        ],
        match: [],
        matchLevel: "ninguno",
        splitDesde: "Control de gestión. Pendiente catálogo economía.",
        nota: "Contenidos inferidos del estándar (no aparece en la reseña detallada del PDF, sólo en el grid de la malla).",
      },
    ],
  },
];
